/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { ApiError } from '../../errors/ApiError'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { serializeError } from '../../middleware/logger'
import { ErrorCode } from '../../models/errorCode'
import { isDuplicateKeyError } from '../../utils/mongo'
import { createId } from '../../utils/id'
import { defaultLang } from '../../emails/localization'
import { createOtp, otpDigits } from '../../utils/otp'
import { sendInviteEmail } from '../../utils/smtp'
import { requiredValue } from '../../utils/values'
import { zValidator } from '../api.validator'
import {
  PostApiV1UsersInviteContext,
  GetApiV1UsersInvitesContext,
  DeleteApiV1UsersInvitesInviteIdContext,
} from './user-invites.context'
import {
  PostApiV1UsersInviteBody,
  PostApiV1UsersInviteResponse,
  GetApiV1UsersInvitesResponse,
  DeleteApiV1UsersInvitesInviteIdParams,
} from './user-invites.zod'

const factory = createFactory()

const DEFAULT_EXPIRY_DAYS = 7

function duplicateInvite(): ApiError {
  return new ApiError(
    ErrorCode.UserAlreadyInvitedOrRegistered,
    'A user or pending invite with this email already exists',
  )
}

export const postApiV1UsersInviteHandlers = factory.createHandlers(
  zValidator('json', PostApiV1UsersInviteBody),
  async (c: PostApiV1UsersInviteContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { email, message, expiryDays, lang } = c.req.valid('json')

    if (await c.var.db.users.getByEmail(email)) {
      throw duplicateInvite()
    }

    const existingInvite = await c.var.db.userInvites.getByEmail(email)

    if (existingInvite) {
      if (existingInvite.expiration > new Date().toISOString()) {
        throw duplicateInvite()
      }
      await c.var.db.userInvites.delete(existingInvite.id)
    }

    const now = new Date().toISOString()
    const expiresAtEpoch =
      Date.now() + (expiryDays || DEFAULT_EXPIRY_DAYS) * 24 * 60 * 60 * 1000

    try {
      const invite = await c.var.db.userInvites.add({
        id: createId('invite'),
        email,
        message,
        expiration: new Date(expiresAtEpoch).toISOString(),
        audit: {
          createdAt: now,
          createdBy: user.id,
          modifiedAt: now,
          modifiedBy: user.id,
        },
      })

      const challengeId = createId('auth_challenge')
      const otp = createOtp(otpDigits(c.env.OTP_DIGITS))

      await c.var.db.authChallenges.insert({
        challengeId,
        type: 'otp',
        code: otp,
        attempts: 0,
        email,
        expiresAtEpoch,
      })

      try {
        const resolvedLang = lang ?? defaultLang(c.env.DEFAULT_LANG)
        const frontendUrl = requiredValue(c.env, 'FRONTEND_URL')
        const inviteUrl = `${frontendUrl}?challengeId=${challengeId}&otp=${otp}&lang=${resolvedLang}`

        await sendInviteEmail(email, inviteUrl, resolvedLang, c.env)
      } catch (error) {
        try {
          await c.var.db.authChallenges.delete(challengeId)
          await c.var.db.userInvites.delete(invite.id)
        } catch (cleanupError) {
          c.var.logger.error('Invite cleanup after email failure threw', {
            challengeId,
            inviteId: invite.id,
            error: serializeError(cleanupError),
          })
        }

        c.var.logger.error('Invite email delivery failed', {
          challengeId,
          inviteId: invite.id,
          error: serializeError(error),
        })
        throw error
      }

      return c.json(invite, 201)
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        throw duplicateInvite()
      }
      throw error
    }
  },
)
export const getApiV1UsersInvitesHandlers = factory.createHandlers(
  zValidator('response', GetApiV1UsersInvitesResponse),
  async (c: GetApiV1UsersInvitesContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    return c.json(await c.var.db.userInvites.listPending())
  },
)
export const deleteApiV1UsersInvitesInviteIdHandlers = factory.createHandlers(
  zValidator('param', DeleteApiV1UsersInvitesInviteIdParams),
  async (c: DeleteApiV1UsersInvitesInviteIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { inviteId } = c.req.valid('param')

    if (!(await c.var.db.userInvites.delete(inviteId))) {
      throw new ApiError(ErrorCode.InvalidInput, 'User invite was not found')
    }

    return c.body(null, 204)
  },
)
