/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { ApiError } from '../../errors/ApiError'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { corruptedDataHook, invalidInputHook } from '../../middleware/error'
import { serializeError } from '../../middleware/logger'
import { ErrorCode } from '../../models/errorCode'
import { createAuthLink } from '../../utils/authLink'
import { isDuplicateKeyError } from '../../utils/mongo'
import { createId } from '../../utils/id'
import { defaultLang } from '../../emails/localization'
import {
  createOtp,
  INVITE_CHALLENGE_TIMEOUT_MS,
  otpDigits,
} from '../../utils/otp'
import { sendInviteEmail } from '../../utils/email'
import { requiredValue } from '../../utils/values'
import { zValidator } from '../api.validator.ts'
import type {
  InviteUserContext,
  ListUserInvitesContext,
  RevokeUserInviteByIdContext,
} from './user-invites.context.ts'
import {
  InviteUserBody,
  InviteUserResponse,
  ListUserInvitesResponse,
  RevokeUserInviteByIdParams,
} from './user-invites.zod'

const factory = createFactory()

const DEFAULT_EXPIRY_DAYS = 7

function duplicateInvite(): ApiError {
  return new ApiError(
    ErrorCode.UserAlreadyInvitedOrRegistered,
    'A user or pending invite with this email already exists',
  )
}

export const inviteUserHandlers = factory.createHandlers(
  zValidator('json', InviteUserBody, invalidInputHook),
  async (c: InviteUserContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { email, message, expiryDays, lang } = c.req.valid('json')

    if (await c.var.db.users.getByEmail(email)) {
      throw duplicateInvite()
    }

    const existingInvite = await c.var.db.userInvites.getByEmail(email)

    if (existingInvite) {
      if (existingInvite.expiration > new Date().toISOString()) {
        throw duplicateInvite()
      }
      await c.var.db.userInvites.delete(existingInvite.id)
    }

    const now = new Date().toISOString()
    const inviteExpiresAtEpoch =
      Date.now() + (expiryDays || DEFAULT_EXPIRY_DAYS) * 24 * 60 * 60 * 1000

    try {
      const invite = await c.var.db.userInvites.add({
        id: createId('invite'),
        email,
        message,
        expiration: new Date(inviteExpiresAtEpoch).toISOString(),
        audit: {
          createdAt: now,
          createdBy: user.id,
          modifiedAt: now,
          modifiedBy: user.id,
        },
      })

      const challengeId = createId('auth_challenge')
      const otp = createOtp(otpDigits(c.env.OTP_DIGITS))
      const challengeExpiresAtEpoch = Date.now() + INVITE_CHALLENGE_TIMEOUT_MS

      try {
        await c.var.db.authChallenges.insert({
          challengeId,
          type: 'otp',
          code: otp,
          attempts: 0,
          email,
          expiresAtEpoch: challengeExpiresAtEpoch,
        })
      } catch (error) {
        try {
          await c.var.db.userInvites.delete(invite.id)
        } catch (cleanupError) {
          c.var.logger.error(
            'Invite cleanup after challenge-insert failure threw',
            {
              inviteId: invite.id,
              error: serializeError(cleanupError),
            },
          )
        }

        c.var.logger.error('Invite auth challenge creation failed', {
          inviteId: invite.id,
          error: serializeError(error),
        })
        throw error
      }

      try {
        const resolvedLang = lang ?? defaultLang(c.env.DEFAULT_LANG)
        const frontendUrl = requiredValue(c.env, 'FRONTEND_URL')
        const inviteUrl = createAuthLink(
          frontendUrl,
          challengeId,
          otp,
          resolvedLang,
          'invite',
        )

        await sendInviteEmail(email, inviteUrl, resolvedLang, c.env, message)
      } catch (error) {
        try {
          await c.var.db.authChallenges.delete(challengeId)
          await c.var.db.userInvites.delete(invite.id)
        } catch (cleanupError) {
          c.var.logger.error('Invite cleanup after email failure threw', {
            challengeId,
            inviteId: invite.id,
            error: serializeError(cleanupError),
          })
        }

        c.var.logger.error('Invite email delivery failed', {
          challengeId,
          inviteId: invite.id,
          error: serializeError(error),
        })
        throw error
      }

      return c.json(invite, 201)
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        throw duplicateInvite()
      }
      throw error
    }
  },
)
export const listUserInvitesHandlers = factory.createHandlers(
  zValidator('response', ListUserInvitesResponse, corruptedDataHook),
  async (c: ListUserInvitesContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    return c.json(await c.var.db.userInvites.listPending())
  },
)
export const revokeUserInviteByIdHandlers = factory.createHandlers(
  zValidator('param', RevokeUserInviteByIdParams, invalidInputHook),
  async (c: RevokeUserInviteByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { inviteId } = c.req.valid('param')

    if (!(await c.var.db.userInvites.delete(inviteId))) {
      throw new ApiError(ErrorCode.InvalidInput, 'User invite was not found')
    }

    return c.body(null, 204)
  },
)
