/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { UserInviteWrite } from '../../models'

export type PostApiV1UsersInviteContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/invite',
  { in: { json: UserInviteWrite }; out: { json: UserInviteWrite } }
>
export type GetApiV1UsersInvitesContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/invites'
>
export type DeleteApiV1UsersInvitesInviteIdContext<E extends Env = any> =
  Context<
    E,
    '/api/v1/users/invites/:inviteId',
    {
      in: {
        param: {
          inviteId: string
        }
      }
      out: {
        param: {
          inviteId: string
        }
      }
    }
  >
