/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const inviteUserBodyExpiryDaysDefault = 7
export const inviteUserBodyExpiryDaysMax = 30

export const InviteUserBody = zod.object({
  email: zod.email(),
  message: zod.string().optional(),
  expiryDays: zod
    .int()
    .min(1)
    .max(inviteUserBodyExpiryDaysMax)
    .default(inviteUserBodyExpiryDaysDefault),
  lang: zod.enum(['en', 'he', 'ar']).optional(),
})

export const inviteUserResponseTwoIdRegExp = new RegExp('^idhi:invite:.+$')

export const InviteUserResponse = zod
  .object({
    audit: zod
      .object({
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe('UTC date and time'),
        createdBy: zod.email(),
        modifiedAt: zod.iso
          .datetime({ offset: true })
          .describe('UTC date and time'),
        modifiedBy: zod.email(),
      })
      .optional(),
  })
  .and(
    zod.object({
      id: zod.string().regex(inviteUserResponseTwoIdRegExp),
      email: zod.email(),
      message: zod.string().optional(),
      expiration: zod.iso
        .datetime({ offset: true })
        .describe('UTC date and time'),
    }),
  )

export const listUserInvitesResponseTwoIdRegExp = new RegExp('^idhi:invite:.+$')

export const ListUserInvitesResponseItem = zod
  .object({
    audit: zod
      .object({
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe('UTC date and time'),
        createdBy: zod.email(),
        modifiedAt: zod.iso
          .datetime({ offset: true })
          .describe('UTC date and time'),
        modifiedBy: zod.email(),
      })
      .optional(),
  })
  .and(
    zod.object({
      id: zod.string().regex(listUserInvitesResponseTwoIdRegExp),
      email: zod.email(),
      message: zod.string().optional(),
      expiration: zod.iso
        .datetime({ offset: true })
        .describe('UTC date and time'),
    }),
  )
export const ListUserInvitesResponse = zod.array(ListUserInvitesResponseItem)

export const revokeUserInviteByIdPathInviteIdRegExp = new RegExp(
  '^idhi:invite:.+$',
)

export const RevokeUserInviteByIdParams = zod.object({
  inviteId: zod.string().regex(revokeUserInviteByIdPathInviteIdRegExp),
})

export const RevokeUserInviteByIdResponse = zod.void()
