/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorResponse, UserInvite, UserInviteWrite } from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') {continue}
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary Invite a user
 */
export const inviteUser = (
  userInviteWrite: BodyType<UserInviteWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<UserInvite>({
    url: `/api/v1/users/invite`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userInviteWrite,
    signal,
  })
}

export const getInviteUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteUser>>,
    TError,
    { data: BodyType<UserInviteWrite> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteUser>>,
  TError,
  { data: BodyType<UserInviteWrite> },
  TContext
> => {
  const mutationKey = ['inviteUser']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteUser>>,
    { data: BodyType<UserInviteWrite> }
  > = (props) => {
    const { data } = props ?? {}

    return inviteUser(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type InviteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof inviteUser>>
>
export type InviteUserMutationBody = BodyType<UserInviteWrite>
export type InviteUserMutationError = ErrorType<ErrorResponse>

/**
 * @summary Invite a user
 */
export const useInviteUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteUser>>,
      TError,
      { data: BodyType<UserInviteWrite> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inviteUser>>,
  TError,
  { data: BodyType<UserInviteWrite> },
  TContext
> => {
  return useMutation(getInviteUserMutationOptions(options), queryClient)
}
/**
 * @summary List pending users invites
 */
export const listUserInvites = (signal?: AbortSignal) => {
  return customInstance<UserInvite[]>({
    url: `/api/v1/users/invites`,
    method: 'GET',
    signal,
  })
}

export const getListUserInvitesQueryKey = () => {
  return [`/api/v1/users/invites`] as const
}

export const getListUserInvitesQueryOptions = <
  TData = Awaited<ReturnType<typeof listUserInvites>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listUserInvites>>, TError, TData>
  >
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListUserInvitesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserInvites>>> = ({
    signal,
  }) => listUserInvites(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUserInvites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserInvitesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUserInvites>>
>
export type ListUserInvitesQueryError = ErrorType<ErrorResponse>

export function useListUserInvites<
  TData = Awaited<ReturnType<typeof listUserInvites>>,
  TError = ErrorType<ErrorResponse>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUserInvites>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserInvites>>,
          TError,
          Awaited<ReturnType<typeof listUserInvites>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUserInvites<
  TData = Awaited<ReturnType<typeof listUserInvites>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUserInvites>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserInvites>>,
          TError,
          Awaited<ReturnType<typeof listUserInvites>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUserInvites<
  TData = Awaited<ReturnType<typeof listUserInvites>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUserInvites>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List pending users invites
 */

export function useListUserInvites<
  TData = Awaited<ReturnType<typeof listUserInvites>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUserInvites>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListUserInvitesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Revoke a user invite
 */
export const revokeUserInviteById = (
  inviteId: string,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/v1/users/invites/${encodeURIComponent(String(inviteId))}`,
    method: 'DELETE',
    signal,
  })
}

export const getRevokeUserInviteByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeUserInviteById>>,
    TError,
    { inviteId: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeUserInviteById>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['revokeUserInviteById']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeUserInviteById>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {}

    return revokeUserInviteById(inviteId)
  }

  return { mutationFn, ...mutationOptions }
}

export type RevokeUserInviteByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeUserInviteById>>
>

export type RevokeUserInviteByIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Revoke a user invite
 */
export const useRevokeUserInviteById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeUserInviteById>>,
      TError,
      { inviteId: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeUserInviteById>>,
  TError,
  { inviteId: string },
  TContext
> => {
  return useMutation(
    getRevokeUserInviteByIdMutationOptions(options),
    queryClient,
  )
}
