/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { OauthAuthorizeWrite } from '../../models'

export type CompleteOauthAuthorizationContext<E extends Env = any> = Context<
  E,
  '/oauth/authorize',
  { in: { json: OauthAuthorizeWrite }; out: { json: OauthAuthorizeWrite } }
>
