/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { issueAuthorizationCode } from '../../oauth/codes'
import { zValidator } from '../api.validator.ts'
import type { CompleteOauthAuthorizationContext } from './oauth.context.ts'
import {
  CompleteOauthAuthorizationBody,
  CompleteOauthAuthorizationResponse,
} from './oauth.zod.ts'

const factory = createFactory()
export const completeOauthAuthorizationHandlers = factory.createHandlers(
  zValidator('json', CompleteOauthAuthorizationBody),
  zValidator('response', CompleteOauthAuthorizationResponse),
  async (c: CompleteOauthAuthorizationContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const redirectUrl = await issueAuthorizationCode(
      c.var.db,
      user,
      c.req.valid('json'),
    )

    c.var.logger.debug('OAuth authorization code issued', {
      userId: user.id,
    })

    return c.json({ redirectUrl })
  },
)
