/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { zValidator } from '../api.validator'
import {
  GetApiV1RecordsContext,
  PutApiV1RecordsContext,
  GetApiV1RecordsRecordIdContext,
  PostApiV1RecordsRecordIdContext,
  DeleteApiV1RecordsRecordIdContext,
} from './records.context'
import {
  GetApiV1RecordsQueryParams,
  GetApiV1RecordsResponse,
  PutApiV1RecordsBody,
  GetApiV1RecordsRecordIdParams,
  GetApiV1RecordsRecordIdResponse,
  PostApiV1RecordsRecordIdParams,
  PostApiV1RecordsRecordIdBody,
  PostApiV1RecordsRecordIdResponse,
  DeleteApiV1RecordsRecordIdParams,
} from './records.zod'

const factory = createFactory()
export const getApiV1RecordsHandlers = factory.createHandlers(
  zValidator('query', GetApiV1RecordsQueryParams),
  zValidator('response', GetApiV1RecordsResponse),
  async (c: GetApiV1RecordsContext) => {},
)
export const putApiV1RecordsHandlers = factory.createHandlers(
  zValidator('json', PutApiV1RecordsBody),
  async (c: PutApiV1RecordsContext) => {},
)
export const getApiV1RecordsRecordIdHandlers = factory.createHandlers(
  zValidator('param', GetApiV1RecordsRecordIdParams),
  zValidator('response', GetApiV1RecordsRecordIdResponse),
  async (c: GetApiV1RecordsRecordIdContext) => {},
)
export const postApiV1RecordsRecordIdHandlers = factory.createHandlers(
  zValidator('param', PostApiV1RecordsRecordIdParams),
  zValidator('json', PostApiV1RecordsRecordIdBody),
  zValidator('response', PostApiV1RecordsRecordIdResponse),
  async (c: PostApiV1RecordsRecordIdContext) => {},
)
export const deleteApiV1RecordsRecordIdHandlers = factory.createHandlers(
  zValidator('param', DeleteApiV1RecordsRecordIdParams),
  async (c: DeleteApiV1RecordsRecordIdContext) => {},
)
