/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { GetApiV1RecordsParams, Record } from '../../schemas'

export type GetApiV1RecordsContext<E extends Env = any> = Context<
  E,
  '/api/v1/records',
  {
    in: { query: GetApiV1RecordsParams }
    out: { query: GetApiV1RecordsParams }
  }
>
export type PutApiV1RecordsContext<E extends Env = any> = Context<
  E,
  '/api/v1/records',
  { in: { json: Record }; out: { json: Record } }
>
export type GetApiV1RecordsRecordIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/records/:recordId',
  {
    in: {
      param: {
        recordId: string
      }
    }
    out: {
      param: {
        recordId: string
      }
    }
  }
>
export type PostApiV1RecordsRecordIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/records/:recordId',
  {
    in: {
      param: {
        recordId: string
      }
      json: Record
    }
    out: {
      param: {
        recordId: string
      }
      json: Record
    }
  }
>
export type DeleteApiV1RecordsRecordIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/records/:recordId',
  {
    in: {
      param: {
        recordId: string
      }
    }
    out: {
      param: {
        recordId: string
      }
    }
  }
>
