/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const getApiV1RecordsQueryPageDefault = 0
export const getApiV1RecordsQueryPageMin = 0

export const getApiV1RecordsQueryPageSizeDefault = 20
export const getApiV1RecordsQueryPageSizeMax = 100

export const GetApiV1RecordsQueryParams = zod.object({
  q: zod.string().optional(),
  page: zod
    .int()
    .min(getApiV1RecordsQueryPageMin)
    .default(getApiV1RecordsQueryPageDefault),
  pageSize: zod
    .int()
    .min(1)
    .max(getApiV1RecordsQueryPageSizeMax)
    .default(getApiV1RecordsQueryPageSizeDefault),
})

export const getApiV1RecordsResponseResultsItemTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const getApiV1RecordsResponseResultsItemTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const GetApiV1RecordsResponse = zod.strictObject({
  results: zod.array(
    zod.looseObject({}).and(
      zod.strictObject({
        audit: zod
          .strictObject({
            createdAt: zod.iso.date().describe('UTC date'),
            createdBy: zod
              .string()
              .regex(getApiV1RecordsResponseResultsItemTwoAuditCreatedByRegExp),
            modifiedAt: zod.iso.date().describe('UTC date'),
            modifiedBy: zod
              .string()
              .regex(
                getApiV1RecordsResponseResultsItemTwoAuditModifiedByRegExp,
              ),
          })
          .optional(),
      }),
    ),
  ),
  facets: zod.record(
    zod.string(),
    zod.array(
      zod.strictObject({
        value: zod.string(),
        count: zod.int(),
      }),
    ),
  ),
  total: zod.int(),
})

export const PutApiV1RecordsBody = zod.looseObject({})

export const putApiV1RecordsResponseTwoAuditCreatedByRegExp = new RegExp(
  '^idhi:user:.+$',
)
export const putApiV1RecordsResponseTwoAuditModifiedByRegExp = new RegExp(
  '^idhi:user:.+$',
)

export const PutApiV1RecordsResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(putApiV1RecordsResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(putApiV1RecordsResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const GetApiV1RecordsRecordIdParams = zod.object({
  recordId: zod.string(),
})

export const getApiV1RecordsRecordIdResponseTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const getApiV1RecordsRecordIdResponseTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const GetApiV1RecordsRecordIdResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(getApiV1RecordsRecordIdResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(getApiV1RecordsRecordIdResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const PostApiV1RecordsRecordIdParams = zod.object({
  recordId: zod.string(),
})

export const PostApiV1RecordsRecordIdBody = zod.looseObject({})

export const postApiV1RecordsRecordIdResponseTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const postApiV1RecordsRecordIdResponseTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const PostApiV1RecordsRecordIdResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(postApiV1RecordsRecordIdResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(postApiV1RecordsRecordIdResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const DeleteApiV1RecordsRecordIdParams = zod.object({
  recordId: zod.string(),
})

export const DeleteApiV1RecordsRecordIdResponse = zod.void()
