/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import type { DatabaseService } from '../../db/service'
import type { UserWithCredentials } from '../../db/models/UserWithCredentials'
import { ApiError } from '../../errors/ApiError'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { ErrorCode } from '../../models/errorCode'
import type { User } from '../../models/user'
import type { UserWrite } from '../../models/userWrite'
import { isDuplicateKeyError } from '../../utils/mongo'
import { normalizeEmail } from '../../db/services/users'
import { zValidator } from '../api.validator.ts'
import {
  ListUsersContext,
  CreateUserContext,
  GetUserByIdContext,
  ReplaceUserByIdContext,
  UpdateUserByIdContext,
  DeleteUserByIdContext,
} from './user-management.context.ts'
import {
  ListUsersQueryParams,
  ListUsersResponse,
  listUsersQueryPageDefault,
  listUsersQueryPageSizeDefault,
  CreateUserBody,
  CreateUserResponse,
  GetUserByIdParams,
  GetUserByIdResponse,
  ReplaceUserByIdParams,
  ReplaceUserByIdBody,
  ReplaceUserByIdResponse,
  UpdateUserByIdParams,
  UpdateUserByIdBody,
  UpdateUserByIdResponse,
  DeleteUserByIdParams,
} from './user-management.zod'

const factory = createFactory()

function publicUser(user: UserWithCredentials): User {
  const publicValues = { ...user }
  Reflect.deleteProperty(publicValues, 'passkeyCredentials')
  return publicValues
}

function userNotFound(userId: string): ApiError {
  return new ApiError(ErrorCode.UserNotFound, `User ${userId} was not found`)
}

function duplicateUser(): ApiError {
  return new ApiError(ErrorCode.InvalidInput, 'A user with this email exists')
}

function emailCannotBeChanged(): ApiError {
  return new ApiError(
    ErrorCode.InvalidInput,
    "A user's email cannot be changed",
  )
}

async function replaceUser(
  db: DatabaseService,
  userId: string,
  values: UserWrite,
): Promise<User> {
  if (normalizeEmail(values.email) !== normalizeEmail(userId)) {
    throw emailCannotBeChanged()
  }

  const user = await db.users.replace(userId, values)

  if (!user) {
    throw userNotFound(userId)
  }

  return publicUser(user)
}

export const listUsersHandlers = factory.createHandlers(
  zValidator('query', ListUsersQueryParams),
  zValidator('response', ListUsersResponse),
  async (c: ListUsersContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { page, pageSize } = c.req.valid('query')
    const users = await c.var.db.users.list(
      page ?? listUsersQueryPageDefault,
      pageSize ?? listUsersQueryPageSizeDefault,
    )

    return c.json({
      results: users.results.map(publicUser),
      total: users.total,
    })
  },
)
export const createUserHandlers = factory.createHandlers(
  zValidator('json', CreateUserBody),
  async (c: CreateUserContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const values = c.req.valid('json')

    if (await c.var.db.users.getByEmail(values.email)) {
      throw duplicateUser()
    }

    try {
      const createdUser = await c.var.db.users.insert({
        ...values,
        passkeyCredentials: [],
      })

      return c.json(publicUser(createdUser), 201)
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        throw duplicateUser()
      }
      throw error
    }
  },
)
export const getUserByIdHandlers = factory.createHandlers(
  zValidator('param', GetUserByIdParams),
  zValidator('response', GetUserByIdResponse),
  async (c: GetUserByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { userId } = c.req.valid('param')
    const requestedUser = await c.var.db.users.get(userId)

    if (!requestedUser) {
      throw userNotFound(userId)
    }

    return c.json(publicUser(requestedUser))
  },
)
export const replaceUserByIdHandlers = factory.createHandlers(
  zValidator('param', ReplaceUserByIdParams),
  zValidator('json', ReplaceUserByIdBody),
  zValidator('response', ReplaceUserByIdResponse),
  async (c: ReplaceUserByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { userId } = c.req.valid('param')
    return c.json(await replaceUser(c.var.db, userId, c.req.valid('json')))
  },
)
export const updateUserByIdHandlers = factory.createHandlers(
  zValidator('param', UpdateUserByIdParams),
  zValidator('json', UpdateUserByIdBody),
  zValidator('response', UpdateUserByIdResponse),
  async (c: UpdateUserByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { userId } = c.req.valid('param')
    return c.json(await replaceUser(c.var.db, userId, c.req.valid('json')))
  },
)
export const deleteUserByIdHandlers = factory.createHandlers(
  zValidator('param', DeleteUserByIdParams),
  async (c: DeleteUserByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { userId } = c.req.valid('param')

    if (!(await c.var.db.users.delete(userId))) {
      throw userNotFound(userId)
    }

    return c.body(null, 204)
  },
)
