/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { ListUsersParams, UserWrite } from '../../models'

export type ListUsersContext<E extends Env = any> = Context<
  E,
  '/api/v1/users',
  { in: { query: ListUsersParams }; out: { query: ListUsersParams } }
>
export type CreateUserContext<E extends Env = any> = Context<
  E,
  '/api/v1/users',
  { in: { json: UserWrite }; out: { json: UserWrite } }
>
export type GetUserByIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
    }
    out: {
      param: {
        userId: string
      }
    }
  }
>
export type ReplaceUserByIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
      json: UserWrite
    }
    out: {
      param: {
        userId: string
      }
      json: UserWrite
    }
  }
>
export type UpdateUserByIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
      json: UserWrite
    }
    out: {
      param: {
        userId: string
      }
      json: UserWrite
    }
  }
>
export type DeleteUserByIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
    }
    out: {
      param: {
        userId: string
      }
    }
  }
>
