/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { GetApiV1UsersParams, UserWrite } from '../../models'

export type GetApiV1UsersContext<E extends Env = any> = Context<
  E,
  '/api/v1/users',
  { in: { query: GetApiV1UsersParams }; out: { query: GetApiV1UsersParams } }
>
export type PostApiV1UsersContext<E extends Env = any> = Context<
  E,
  '/api/v1/users',
  { in: { json: UserWrite }; out: { json: UserWrite } }
>
export type GetApiV1UsersUserIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
    }
    out: {
      param: {
        userId: string
      }
    }
  }
>
export type PutApiV1UsersUserIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
      json: UserWrite
    }
    out: {
      param: {
        userId: string
      }
      json: UserWrite
    }
  }
>
export type PostApiV1UsersUserIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
      json: UserWrite
    }
    out: {
      param: {
        userId: string
      }
      json: UserWrite
    }
  }
>
export type DeleteApiV1UsersUserIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/users/:userId',
  {
    in: {
      param: {
        userId: string
      }
    }
    out: {
      param: {
        userId: string
      }
    }
  }
>
