/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const listUsersQueryPageDefault = 0
export const listUsersQueryPageMin = 0

export const listUsersQueryPageSizeDefault = 20
export const listUsersQueryPageSizeMax = 100

export const ListUsersQueryParams = zod.object({
  page: zod.coerce
    .number()
    .int()
    .min(listUsersQueryPageMin)
    .default(listUsersQueryPageDefault),
  pageSize: zod.coerce
    .number()
    .int()
    .min(1)
    .max(listUsersQueryPageSizeMax)
    .default(listUsersQueryPageSizeDefault),
})

export const ListUsersResponse = zod.object({
  results: zod.array(
    zod.object({
      id: zod.email(),
      name: zod.string().optional(),
      email: zod.email(),
      isAdmin: zod.boolean(),
    }),
  ),
  total: zod.int(),
})

export const CreateUserBody = zod.object({
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const CreateUserResponse = zod.object({
  id: zod.email(),
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const GetUserByIdParams = zod.object({
  userId: zod.string(),
})

export const GetUserByIdResponse = zod.object({
  id: zod.email(),
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const ReplaceUserByIdParams = zod.object({
  userId: zod.string(),
})

export const ReplaceUserByIdBody = zod.object({
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const ReplaceUserByIdResponse = zod.object({
  id: zod.email(),
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const UpdateUserByIdParams = zod.object({
  userId: zod.string(),
})

export const UpdateUserByIdBody = zod.object({
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const UpdateUserByIdResponse = zod.object({
  id: zod.email(),
  name: zod.string().optional(),
  email: zod.email(),
  isAdmin: zod.boolean(),
})

export const DeleteUserByIdParams = zod.object({
  userId: zod.string(),
})

export const DeleteUserByIdResponse = zod.void()
