/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const getApiV1EntitiesQueryPageDefault = 0
export const getApiV1EntitiesQueryPageMin = 0

export const getApiV1EntitiesQueryPageSizeDefault = 20
export const getApiV1EntitiesQueryPageSizeMax = 100

export const GetApiV1EntitiesQueryParams = zod.object({
  q: zod.string().optional(),
  page: zod
    .int()
    .min(getApiV1EntitiesQueryPageMin)
    .default(getApiV1EntitiesQueryPageDefault),
  pageSize: zod
    .int()
    .min(1)
    .max(getApiV1EntitiesQueryPageSizeMax)
    .default(getApiV1EntitiesQueryPageSizeDefault),
})

export const getApiV1EntitiesResponseResultsItemTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const getApiV1EntitiesResponseResultsItemTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const GetApiV1EntitiesResponse = zod.strictObject({
  results: zod.array(
    zod.looseObject({}).and(
      zod.strictObject({
        audit: zod
          .strictObject({
            createdAt: zod.iso.date().describe('UTC date'),
            createdBy: zod
              .string()
              .regex(
                getApiV1EntitiesResponseResultsItemTwoAuditCreatedByRegExp,
              ),
            modifiedAt: zod.iso.date().describe('UTC date'),
            modifiedBy: zod
              .string()
              .regex(
                getApiV1EntitiesResponseResultsItemTwoAuditModifiedByRegExp,
              ),
          })
          .optional(),
      }),
    ),
  ),
  facets: zod.record(
    zod.string(),
    zod.array(
      zod.strictObject({
        value: zod.string(),
        count: zod.int(),
      }),
    ),
  ),
  total: zod.int(),
})

export const PutApiV1EntitiesBody = zod.looseObject({})

export const putApiV1EntitiesResponseTwoAuditCreatedByRegExp = new RegExp(
  '^idhi:user:.+$',
)
export const putApiV1EntitiesResponseTwoAuditModifiedByRegExp = new RegExp(
  '^idhi:user:.+$',
)

export const PutApiV1EntitiesResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(putApiV1EntitiesResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(putApiV1EntitiesResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const GetApiV1EntitiesEntityIdParams = zod.object({
  entityId: zod.string(),
})

export const getApiV1EntitiesEntityIdResponseTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const getApiV1EntitiesEntityIdResponseTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const GetApiV1EntitiesEntityIdResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(getApiV1EntitiesEntityIdResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(getApiV1EntitiesEntityIdResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const PostApiV1EntitiesEntityIdParams = zod.object({
  entityId: zod.string(),
})

export const PostApiV1EntitiesEntityIdBody = zod.looseObject({})

export const postApiV1EntitiesEntityIdResponseTwoAuditCreatedByRegExp =
  new RegExp('^idhi:user:.+$')
export const postApiV1EntitiesEntityIdResponseTwoAuditModifiedByRegExp =
  new RegExp('^idhi:user:.+$')

export const PostApiV1EntitiesEntityIdResponse = zod.looseObject({}).and(
  zod.strictObject({
    audit: zod
      .strictObject({
        createdAt: zod.iso.date().describe('UTC date'),
        createdBy: zod
          .string()
          .regex(postApiV1EntitiesEntityIdResponseTwoAuditCreatedByRegExp),
        modifiedAt: zod.iso.date().describe('UTC date'),
        modifiedBy: zod
          .string()
          .regex(postApiV1EntitiesEntityIdResponseTwoAuditModifiedByRegExp),
      })
      .optional(),
  }),
)

export const DeleteApiV1EntitiesEntityIdParams = zod.object({
  entityId: zod.string(),
})

export const DeleteApiV1EntitiesEntityIdResponse = zod.void()
