/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import type { EntityWrite } from '../../db/services/entities'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { ApiError } from '../../errors/ApiError'
import { ErrorCode } from '../../models/errorCode'
import { entityIdMatchesType } from '../../utils/entityId'
import { isDuplicateKeyError } from '../../utils/mongo'
import { zValidator } from '../api.validator'
import {
  SearchEntitiesContext,
  CreateEntityContext,
  GetEntityByIdContext,
  UpdateEntityByIdContext,
  DeleteEntityByIdContext,
} from './entities.context'
import {
  SearchEntitiesBody,
  SearchEntitiesResponse,
  searchEntitiesBodyPageDefault,
  searchEntitiesBodyPageSizeDefault,
  CreateEntityBody,
  CreateEntityResponse,
  GetEntityByIdParams,
  GetEntityByIdResponse,
  UpdateEntityByIdParams,
  UpdateEntityByIdBody,
  UpdateEntityByIdResponse,
  DeleteEntityByIdParams,
} from './entities.zod'

const factory = createFactory()

function entityNotFound(entityId: string): ApiError {
  return new ApiError(
    ErrorCode.EntityNotFound,
    `Entity ${entityId} was not found`,
  )
}

export const searchEntitiesHandlers = factory.createHandlers(
  zValidator('json', SearchEntitiesBody),
  zValidator('response', SearchEntitiesResponse),
  async (c: SearchEntitiesContext) => {
    const { q, facets, filter, sort, page, pageSize } = c.req.valid('json')
    return c.json(
      await c.var.db.entities.search(
        q,
        facets,
        filter,
        sort,
        page ?? searchEntitiesBodyPageDefault,
        pageSize ?? searchEntitiesBodyPageSizeDefault,
      ),
    )
  },
)
export const createEntityHandlers = factory.createHandlers(
  zValidator('json', CreateEntityBody),
  async (c: CreateEntityContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    try {
      const entity = await c.var.db.entities.insert(
        c.req.valid('json') as unknown as EntityWrite,
        user.id,
      )

      return c.json(entity, 201)
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        throw new ApiError(
          ErrorCode.InvalidInput,
          'An entity with this ID already exists',
        )
      }
      throw error
    }
  },
)
export const getEntityByIdHandlers = factory.createHandlers(
  zValidator('param', GetEntityByIdParams),
  zValidator('response', GetEntityByIdResponse),
  async (c: GetEntityByIdContext) => {
    const { entityId } = c.req.valid('param')
    const entity = await c.var.db.entities.get(entityId)

    if (!entity) {
      throw entityNotFound(entityId)
    }

    return c.json(entity)
  },
)
export const updateEntityByIdHandlers = factory.createHandlers(
  zValidator('param', UpdateEntityByIdParams),
  zValidator('json', UpdateEntityByIdBody),
  zValidator('response', UpdateEntityByIdResponse),
  async (c: UpdateEntityByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { entityId } = c.req.valid('param')
    const entity = c.req.valid('json') as unknown as EntityWrite
    const requestEntityId = (entity as { id?: unknown }).id

    if (
      requestEntityId !== undefined &&
      requestEntityId !== null &&
      requestEntityId !== '' &&
      requestEntityId !== entityId
    ) {
      throw new ApiError(
        ErrorCode.InvalidInput,
        'The entity ID in the request body must match the URL',
      )
    }

    if (!entityIdMatchesType(entityId, entity.type)) {
      throw new ApiError(
        ErrorCode.InvalidInput,
        'The entity type in the request body must match the URL ID',
      )
    }

    const updatedEntity = await c.var.db.entities.replace(
      entityId,
      entity,
      user.id,
    )

    if (!updatedEntity) {
      throw entityNotFound(entityId)
    }

    return c.json(updatedEntity)
  },
)
export const deleteEntityByIdHandlers = factory.createHandlers(
  zValidator('param', DeleteEntityByIdParams),
  async (c: DeleteEntityByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { entityId } = c.req.valid('param')

    if (!(await c.var.db.entities.delete(entityId, user.id))) {
      throw entityNotFound(entityId)
    }

    return c.body(null, 204)
  },
)
