/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type { Entity, GetApiV1EntitiesParams } from '../../models'

export type GetApiV1EntitiesContext<E extends Env = any> = Context<
  E,
  '/api/v1/entities',
  {
    in: { query: GetApiV1EntitiesParams }
    out: { query: GetApiV1EntitiesParams }
  }
>
export type PutApiV1EntitiesContext<E extends Env = any> = Context<
  E,
  '/api/v1/entities',
  { in: { json: Entity }; out: { json: Entity } }
>
export type GetApiV1EntitiesEntityIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/entities/:entityId',
  {
    in: {
      param: {
        entityId: string
      }
    }
    out: {
      param: {
        entityId: string
      }
    }
  }
>
export type PostApiV1EntitiesEntityIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/entities/:entityId',
  {
    in: {
      param: {
        entityId: string
      }
      json: Entity
    }
    out: {
      param: {
        entityId: string
      }
      json: Entity
    }
  }
>
export type DeleteApiV1EntitiesEntityIdContext<E extends Env = any> = Context<
  E,
  '/api/v1/entities/:entityId',
  {
    in: {
      param: {
        entityId: string
      }
    }
    out: {
      param: {
        entityId: string
      }
    }
  }
>
