/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import type { EntityWrite } from '../../db/services/entities'
import { assertAuthenticatedUser } from '../../middleware/auth'
import {
  createEntity,
  deleteEntity,
  getEntityOrThrow,
  searchEntities,
  updateEntity,
} from '../../utils/entityOps'
import { refineUniqueLangStringLanguages } from '../../utils/langString'
import { zValidator } from '../api.validator'
import type {
  SearchEntitiesContext,
  CreateEntityContext,
  GetEntityByIdContext,
  UpdateEntityByIdContext,
  DeleteEntityByIdContext,
} from './entities.context'
import {
  SearchEntitiesBody,
  SearchEntitiesResponse,
  CreateEntityBody,
  CreateEntityResponse,
  GetEntityByIdParams,
  GetEntityByIdResponse,
  UpdateEntityByIdParams,
  UpdateEntityByIdBody,
  UpdateEntityByIdResponse,
  DeleteEntityByIdParams,
} from './entities.zod'

const factory = createFactory()

export const searchEntitiesHandlers = factory.createHandlers(
  zValidator('json', SearchEntitiesBody),
  zValidator('response', SearchEntitiesResponse),
  async (c: SearchEntitiesContext) => {
    return c.json(await searchEntities(c.var.db.entities, c.req.valid('json')))
  },
)
export const createEntityHandlers = factory.createHandlers(
  zValidator(
    'json',
    CreateEntityBody.superRefine(refineUniqueLangStringLanguages),
  ),
  async (c: CreateEntityContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const entity = await createEntity(
      c.var.db.entities,
      c.req.valid('json') as unknown as EntityWrite,
      user.id,
    )

    return c.json(entity, 201)
  },
)
export const getEntityByIdHandlers = factory.createHandlers(
  zValidator('param', GetEntityByIdParams),
  zValidator('response', GetEntityByIdResponse),
  async (c: GetEntityByIdContext) => {
    const { entityId } = c.req.valid('param')

    return c.json(await getEntityOrThrow(c.var.db.entities, entityId))
  },
)
export const updateEntityByIdHandlers = factory.createHandlers(
  zValidator('param', UpdateEntityByIdParams),
  zValidator(
    'json',
    UpdateEntityByIdBody.superRefine(refineUniqueLangStringLanguages),
  ),
  zValidator('response', UpdateEntityByIdResponse),
  async (c: UpdateEntityByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { entityId } = c.req.valid('param')
    const updatedEntity = await updateEntity(
      c.var.db.entities,
      entityId,
      c.req.valid('json') as unknown as EntityWrite,
      user.id,
    )

    return c.json(updatedEntity)
  },
)
export const deleteEntityByIdHandlers = factory.createHandlers(
  zValidator('param', DeleteEntityByIdParams),
  async (c: DeleteEntityByIdContext) => {
    const user = c.get('user')
    assertAuthenticatedUser(user)
    const { entityId } = c.req.valid('param')
    await deleteEntity(c.var.db.entities, entityId, user.id)

    return c.body(null, 204)
  },
)
