/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AuditedEntity,
  Entity,
  ErrorResponse,
  GetApiV1Entities200,
  GetApiV1EntitiesParams,
} from '../../models'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getApiV1EntitiesResponse200 = {
  data: GetApiV1Entities200
  status: 200
}

export type getApiV1EntitiesResponseSuccess = getApiV1EntitiesResponse200 & {
  headers: Headers
}
export type getApiV1EntitiesResponse = getApiV1EntitiesResponseSuccess

export const getGetApiV1EntitiesUrl = (params?: GetApiV1EntitiesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/entities?${stringifiedParams}`
    : `/api/v1/entities`
}

/**
 * Free text search and facet-based search across all entities. Returns partial entity properties and facets.
 * @summary Search entities
 */
export const getApiV1Entities = async (
  params?: GetApiV1EntitiesParams,
  options?: RequestInit,
): Promise<getApiV1EntitiesResponse> => {
  const res = await fetch(getGetApiV1EntitiesUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getApiV1EntitiesResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1EntitiesResponse
}

export const getGetApiV1EntitiesQueryKey = (
  params?: GetApiV1EntitiesParams,
) => {
  return [`/api/v1/entities`, ...(params ? [params] : [])] as const
}

export const getGetApiV1EntitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = unknown,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiV1EntitiesQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1Entities>>
  > = ({ signal }) => getApiV1Entities(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Entities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1EntitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Entities>>
>
export type GetApiV1EntitiesQueryError = unknown

export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = unknown,
>(
  params: undefined | GetApiV1EntitiesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Entities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Entities>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = unknown,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Entities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Entities>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = unknown,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search entities
 */

export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = unknown,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1EntitiesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export type putApiV1EntitiesResponse201 = {
  data: AuditedEntity
  status: 201
}

export type putApiV1EntitiesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type putApiV1EntitiesResponseSuccess = putApiV1EntitiesResponse201 & {
  headers: Headers
}
export type putApiV1EntitiesResponseError = putApiV1EntitiesResponse400 & {
  headers: Headers
}

export type putApiV1EntitiesResponse =
  putApiV1EntitiesResponseSuccess | putApiV1EntitiesResponseError

export const getPutApiV1EntitiesUrl = () => {
  return `/api/v1/entities`
}

/**
 * @summary Create a new entity
 */
export const putApiV1Entities = async (
  entity: Entity,
  options?: RequestInit,
): Promise<putApiV1EntitiesResponse> => {
  const res = await fetch(getPutApiV1EntitiesUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(entity),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putApiV1EntitiesResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putApiV1EntitiesResponse
}

export const getPutApiV1EntitiesMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1Entities>>,
    TError,
    { data: Entity },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1Entities>>,
  TError,
  { data: Entity },
  TContext
> => {
  const mutationKey = ['putApiV1Entities']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1Entities>>,
    { data: Entity }
  > = (props) => {
    const { data } = props ?? {}

    return putApiV1Entities(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiV1EntitiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1Entities>>
>
export type PutApiV1EntitiesMutationBody = Entity
export type PutApiV1EntitiesMutationError = ErrorResponse

/**
 * @summary Create a new entity
 */
export const usePutApiV1Entities = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1Entities>>,
      TError,
      { data: Entity },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1Entities>>,
  TError,
  { data: Entity },
  TContext
> => {
  return useMutation(getPutApiV1EntitiesMutationOptions(options), queryClient)
}
export type getApiV1EntitiesEntityIdResponse200 = {
  data: AuditedEntity
  status: 200
}

export type getApiV1EntitiesEntityIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getApiV1EntitiesEntityIdResponseSuccess =
  getApiV1EntitiesEntityIdResponse200 & {
    headers: Headers
  }
export type getApiV1EntitiesEntityIdResponseError =
  getApiV1EntitiesEntityIdResponse400 & {
    headers: Headers
  }

export type getApiV1EntitiesEntityIdResponse =
  | getApiV1EntitiesEntityIdResponseSuccess
  | getApiV1EntitiesEntityIdResponseError

export const getGetApiV1EntitiesEntityIdUrl = (entityId: string) => {
  return `/api/v1/entities/${entityId}`
}

/**
 * Returns all properties of a specific entity.
 * @summary Get an entity
 */
export const getApiV1EntitiesEntityId = async (
  entityId: string,
  options?: RequestInit,
): Promise<getApiV1EntitiesEntityIdResponse> => {
  const res = await fetch(getGetApiV1EntitiesEntityIdUrl(entityId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getApiV1EntitiesEntityIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1EntitiesEntityIdResponse
}

export const getGetApiV1EntitiesEntityIdQueryKey = (entityId: string) => {
  return [`/api/v1/entities/${entityId}`] as const
}

export const getGetApiV1EntitiesEntityIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorResponse,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1EntitiesEntityIdQueryKey(entityId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
  > = ({ signal }) =>
    getApiV1EntitiesEntityId(entityId, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: entityId !== null && entityId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1EntitiesEntityIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
>
export type GetApiV1EntitiesEntityIdQueryError = ErrorResponse

export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorResponse,
>(
  entityId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorResponse,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorResponse,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an entity
 */

export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorResponse,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1EntitiesEntityIdQueryOptions(
    entityId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export type postApiV1EntitiesEntityIdResponse200 = {
  data: AuditedEntity
  status: 200
}

export type postApiV1EntitiesEntityIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiV1EntitiesEntityIdResponseSuccess =
  postApiV1EntitiesEntityIdResponse200 & {
    headers: Headers
  }
export type postApiV1EntitiesEntityIdResponseError =
  postApiV1EntitiesEntityIdResponse400 & {
    headers: Headers
  }

export type postApiV1EntitiesEntityIdResponse =
  | postApiV1EntitiesEntityIdResponseSuccess
  | postApiV1EntitiesEntityIdResponseError

export const getPostApiV1EntitiesEntityIdUrl = (entityId: string) => {
  return `/api/v1/entities/${entityId}`
}

/**
 * @summary Update an entity
 */
export const postApiV1EntitiesEntityId = async (
  entityId: string,
  entity: Entity,
  options?: RequestInit,
): Promise<postApiV1EntitiesEntityIdResponse> => {
  const res = await fetch(getPostApiV1EntitiesEntityIdUrl(entityId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(entity),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postApiV1EntitiesEntityIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1EntitiesEntityIdResponse
}

export const getPostApiV1EntitiesEntityIdMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
    TError,
    { entityId: string; data: Entity },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
  TError,
  { entityId: string; data: Entity },
  TContext
> => {
  const mutationKey = ['postApiV1EntitiesEntityId']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
    { entityId: string; data: Entity }
  > = (props) => {
    const { entityId, data } = props ?? {}

    return postApiV1EntitiesEntityId(entityId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1EntitiesEntityIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>
>
export type PostApiV1EntitiesEntityIdMutationBody = Entity
export type PostApiV1EntitiesEntityIdMutationError = ErrorResponse

/**
 * @summary Update an entity
 */
export const usePostApiV1EntitiesEntityId = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
      TError,
      { entityId: string; data: Entity },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
  TError,
  { entityId: string; data: Entity },
  TContext
> => {
  return useMutation(
    getPostApiV1EntitiesEntityIdMutationOptions(options),
    queryClient,
  )
}
export type deleteApiV1EntitiesEntityIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiV1EntitiesEntityIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteApiV1EntitiesEntityIdResponseSuccess =
  deleteApiV1EntitiesEntityIdResponse204 & {
    headers: Headers
  }
export type deleteApiV1EntitiesEntityIdResponseError =
  deleteApiV1EntitiesEntityIdResponse400 & {
    headers: Headers
  }

export type deleteApiV1EntitiesEntityIdResponse =
  | deleteApiV1EntitiesEntityIdResponseSuccess
  | deleteApiV1EntitiesEntityIdResponseError

export const getDeleteApiV1EntitiesEntityIdUrl = (entityId: string) => {
  return `/api/v1/entities/${entityId}`
}

/**
 * @summary Delete an entity
 */
export const deleteApiV1EntitiesEntityId = async (
  entityId: string,
  options?: RequestInit,
): Promise<deleteApiV1EntitiesEntityIdResponse> => {
  const res = await fetch(getDeleteApiV1EntitiesEntityIdUrl(entityId), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteApiV1EntitiesEntityIdResponse['data'] = body
    ? JSON.parse(body)
    : undefined
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteApiV1EntitiesEntityIdResponse
}

export const getDeleteApiV1EntitiesEntityIdMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
    TError,
    { entityId: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
  TError,
  { entityId: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1EntitiesEntityId']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
    { entityId: string }
  > = (props) => {
    const { entityId } = props ?? {}

    return deleteApiV1EntitiesEntityId(entityId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiV1EntitiesEntityIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>
>

export type DeleteApiV1EntitiesEntityIdMutationError = ErrorResponse

/**
 * @summary Delete an entity
 */
export const useDeleteApiV1EntitiesEntityId = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
      TError,
      { entityId: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
  TError,
  { entityId: string },
  TContext
> => {
  return useMutation(
    getDeleteApiV1EntitiesEntityIdMutationOptions(options),
    queryClient,
  )
}
