/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AuditedEntity,
  CreateEntityParams,
  Entity,
  EntitySearch,
  ErrorResponse,
  SearchEntities200,
  SearchEntityTagsParams,
  SuggestEntityFieldValuesParams,
  UpdateEntityByIdParams,
} from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') {
      continue
    }
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * Free text search and facet-based search across all entities. Returns partial entity properties and facets.
 * @summary Search entities
 */
export const searchEntities = (
  entitySearch: BodyType<EntitySearch>,
  signal?: AbortSignal,
) => {
  return customInstance<SearchEntities200>({
    url: `/api/v1/entities`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: entitySearch,
    signal,
  })
}

export const getSearchEntitiesQueryKey = (
  entitySearch?: BodyType<EntitySearch>,
) => {
  return ['POST', `/api/v1/entities`, entitySearch] as const
}

export const getSearchEntitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchEntities>>,
  TError = ErrorType<unknown>,
>(
  entitySearch: BodyType<EntitySearch>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchEntities>>, TError, TData>
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getSearchEntitiesQueryKey(entitySearch)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchEntities>>> = ({
    signal,
  }) => searchEntities(entitySearch, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchEntities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchEntitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchEntities>>
>
export type SearchEntitiesQueryError = ErrorType<unknown>

export function useSearchEntities<
  TData = Awaited<ReturnType<typeof searchEntities>>,
  TError = ErrorType<unknown>,
>(
  entitySearch: BodyType<EntitySearch>,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchEntities>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchEntities>>,
          TError,
          Awaited<ReturnType<typeof searchEntities>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchEntities<
  TData = Awaited<ReturnType<typeof searchEntities>>,
  TError = ErrorType<unknown>,
>(
  entitySearch: BodyType<EntitySearch>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchEntities>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchEntities>>,
          TError,
          Awaited<ReturnType<typeof searchEntities>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchEntities<
  TData = Awaited<ReturnType<typeof searchEntities>>,
  TError = ErrorType<unknown>,
>(
  entitySearch: BodyType<EntitySearch>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchEntities>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search entities
 */

export function useSearchEntities<
  TData = Awaited<ReturnType<typeof searchEntities>>,
  TError = ErrorType<unknown>,
>(
  entitySearch: BodyType<EntitySearch>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchEntities>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getSearchEntitiesQueryOptions(entitySearch, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * Creates an entity with an ID minted by the server. The request ID may be omitted, null, or empty; a non-empty ID is rejected.
 * @summary Create a new entity
 */
export const createEntity = (
  entity: BodyType<Entity>,
  params?: CreateEntityParams,
  signal?: AbortSignal,
) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: entity,
    params,
    signal,
  })
}

export const getCreateEntityMutationKey = () => ['createEntity'] as const

export const getCreateEntityMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEntity>>,
    TError,
    CreateEntityMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEntity>>,
  TError,
  CreateEntityMutationVariables,
  TContext
> => {
  const mutationKey = getCreateEntityMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEntity>>,
    CreateEntityMutationVariables
  > = (props) => {
    const { data, params } = props ?? {}

    return createEntity(data, params)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateEntityMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEntity>>
>
export type CreateEntityMutationBody = BodyType<Entity>
export type CreateEntityMutationError = ErrorType<ErrorResponse>
export type CreateEntityMutationVariables = {
  data: BodyType<Entity>
  params?: CreateEntityParams
}

/**
 * @summary Create a new entity
 */
export const useCreateEntity = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createEntity>>,
      TError,
      CreateEntityMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createEntity>>,
  TError,
  CreateEntityMutationVariables,
  TContext
> => {
  return useMutation(getCreateEntityMutationOptions(options), queryClient)
}
/**
 * Returns distinct tag values used across entities, optionally filtered by a substring, for autocomplete purposes.
 * @summary Search tag values
 */
export const searchEntityTags = (
  params?: SearchEntityTagsParams,
  signal?: AbortSignal,
) => {
  return customInstance<string[]>({
    url: `/api/v1/entities/tags`,
    method: 'GET',
    params,
    signal,
  })
}

export const getSearchEntityTagsQueryKey = (
  params?: SearchEntityTagsParams,
) => {
  return [`/api/v1/entities/tags`, ...(params ? [params] : [])] as const
}

export const getSearchEntityTagsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchEntityTags>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchEntityTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchEntityTags>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getSearchEntityTagsQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchEntityTags>>
  > = ({ signal }) => searchEntityTags(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchEntityTags>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchEntityTagsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchEntityTags>>
>
export type SearchEntityTagsQueryError = ErrorType<unknown>

export function useSearchEntityTags<
  TData = Awaited<ReturnType<typeof searchEntityTags>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | SearchEntityTagsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchEntityTags>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchEntityTags>>,
          TError,
          Awaited<ReturnType<typeof searchEntityTags>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchEntityTags<
  TData = Awaited<ReturnType<typeof searchEntityTags>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchEntityTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchEntityTags>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchEntityTags>>,
          TError,
          Awaited<ReturnType<typeof searchEntityTags>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchEntityTags<
  TData = Awaited<ReturnType<typeof searchEntityTags>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchEntityTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchEntityTags>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search tag values
 */

export function useSearchEntityTags<
  TData = Awaited<ReturnType<typeof searchEntityTags>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchEntityTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchEntityTags>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getSearchEntityTagsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * Returns AI-generated suggestions for a single supported entity field, derived from the prominent fields of the supplied entity. The entity need not be persisted; its ID is ignored.
 * @summary Suggest entity field values
 */
export const suggestEntityFieldValues = (
  entity: BodyType<Entity>,
  params: SuggestEntityFieldValuesParams,
  signal?: AbortSignal,
) => {
  return customInstance<string[]>({
    url: `/api/v1/entities/suggestions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: entity,
    params,
    signal,
  })
}

export const getSuggestEntityFieldValuesMutationKey = () =>
  ['suggestEntityFieldValues'] as const

export const getSuggestEntityFieldValuesMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof suggestEntityFieldValues>>,
    TError,
    SuggestEntityFieldValuesMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof suggestEntityFieldValues>>,
  TError,
  SuggestEntityFieldValuesMutationVariables,
  TContext
> => {
  const mutationKey = getSuggestEntityFieldValuesMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof suggestEntityFieldValues>>,
    SuggestEntityFieldValuesMutationVariables
  > = (props) => {
    const { data, params } = props ?? {}

    return suggestEntityFieldValues(data, params)
  }

  return { mutationFn, ...mutationOptions }
}

export type SuggestEntityFieldValuesMutationResult = NonNullable<
  Awaited<ReturnType<typeof suggestEntityFieldValues>>
>
export type SuggestEntityFieldValuesMutationBody = BodyType<Entity>
export type SuggestEntityFieldValuesMutationError = ErrorType<ErrorResponse>
export type SuggestEntityFieldValuesMutationVariables = {
  data: BodyType<Entity>
  params: SuggestEntityFieldValuesParams
}

/**
 * @summary Suggest entity field values
 */
export const useSuggestEntityFieldValues = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof suggestEntityFieldValues>>,
      TError,
      SuggestEntityFieldValuesMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof suggestEntityFieldValues>>,
  TError,
  SuggestEntityFieldValuesMutationVariables,
  TContext
> => {
  return useMutation(
    getSuggestEntityFieldValuesMutationOptions(options),
    queryClient,
  )
}
/**
 * Returns all properties of a specific entity.
 * @summary Get an entity
 */
export const getEntityById = (entityId: string, signal?: AbortSignal) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'GET',
    signal,
  })
}

export const getGetEntityByIdQueryKey = (entityId: string) => {
  return [`/api/v1/entities/${entityId}`] as const
}

export const getGetEntityByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getEntityById>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEntityById>>, TError, TData>
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetEntityByIdQueryKey(entityId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntityById>>> = ({
    signal,
  }) => getEntityById(entityId, signal)

  return {
    queryKey,
    queryFn,
    enabled: entityId !== null && entityId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEntityById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntityByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEntityById>>
>
export type GetEntityByIdQueryError = ErrorType<ErrorResponse>

export function useGetEntityById<
  TData = Awaited<ReturnType<typeof getEntityById>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEntityById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntityById>>,
          TError,
          Awaited<ReturnType<typeof getEntityById>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetEntityById<
  TData = Awaited<ReturnType<typeof getEntityById>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEntityById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntityById>>,
          TError,
          Awaited<ReturnType<typeof getEntityById>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetEntityById<
  TData = Awaited<ReturnType<typeof getEntityById>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEntityById>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an entity
 */

export function useGetEntityById<
  TData = Awaited<ReturnType<typeof getEntityById>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEntityById>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetEntityByIdQueryOptions(entityId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * Replaces an entity while preserving the server-managed ID from the URL. The request ID may be omitted, null, or empty; a non-empty ID must match the URL.
 * @summary Update an entity
 */
export const updateEntityById = (
  entityId: string,
  entity: BodyType<Entity>,
  params?: UpdateEntityByIdParams,
  signal?: AbortSignal,
) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: entity,
    params,
    signal,
  })
}

export const getUpdateEntityByIdMutationKey = () =>
  ['updateEntityById'] as const

export const getUpdateEntityByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEntityById>>,
    TError,
    UpdateEntityByIdMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEntityById>>,
  TError,
  UpdateEntityByIdMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateEntityByIdMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEntityById>>,
    UpdateEntityByIdMutationVariables
  > = (props) => {
    const { entityId, data, params } = props ?? {}

    return updateEntityById(entityId, data, params)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateEntityByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEntityById>>
>
export type UpdateEntityByIdMutationBody = BodyType<Entity>
export type UpdateEntityByIdMutationError = ErrorType<ErrorResponse>
export type UpdateEntityByIdMutationVariables = {
  entityId: string
  data: BodyType<Entity>
  params?: UpdateEntityByIdParams
}

/**
 * @summary Update an entity
 */
export const useUpdateEntityById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEntityById>>,
      TError,
      UpdateEntityByIdMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateEntityById>>,
  TError,
  UpdateEntityByIdMutationVariables,
  TContext
> => {
  return useMutation(getUpdateEntityByIdMutationOptions(options), queryClient)
}
/**
 * @summary Delete an entity
 */
export const deleteEntityById = (entityId: string, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'DELETE',
    signal,
  })
}

export const getDeleteEntityByIdMutationKey = () =>
  ['deleteEntityById'] as const

export const getDeleteEntityByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEntityById>>,
    TError,
    DeleteEntityByIdMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEntityById>>,
  TError,
  DeleteEntityByIdMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteEntityByIdMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteEntityById>>,
    DeleteEntityByIdMutationVariables
  > = (props) => {
    const { entityId } = props ?? {}

    return deleteEntityById(entityId)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteEntityByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteEntityById>>
>

export type DeleteEntityByIdMutationError = ErrorType<ErrorResponse>
export type DeleteEntityByIdMutationVariables = { entityId: string }

/**
 * @summary Delete an entity
 */
export const useDeleteEntityById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteEntityById>>,
      TError,
      DeleteEntityByIdMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteEntityById>>,
  TError,
  DeleteEntityByIdMutationVariables,
  TContext
> => {
  return useMutation(getDeleteEntityByIdMutationOptions(options), queryClient)
}
