/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AuditedEntity,
  Entity,
  ErrorResponse,
  GetApiV1Entities200,
  GetApiV1EntitiesParams,
} from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * Free text search and facet-based search across all entities. Returns partial entity properties and facets.
 * @summary Search entities
 */
export const getApiV1Entities = (
  params?: GetApiV1EntitiesParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetApiV1Entities200>({
    url: `/api/v1/entities`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetApiV1EntitiesQueryKey = (
  params?: GetApiV1EntitiesParams,
) => {
  return [`/api/v1/entities`, ...(params ? [params] : [])] as const
}

export const getGetApiV1EntitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiV1EntitiesQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1Entities>>
  > = ({ signal }) => getApiV1Entities(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Entities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1EntitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Entities>>
>
export type GetApiV1EntitiesQueryError = ErrorType<unknown>

export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetApiV1EntitiesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Entities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Entities>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Entities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Entities>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search entities
 */

export function useGetApiV1Entities<
  TData = Awaited<ReturnType<typeof getApiV1Entities>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiV1EntitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Entities>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1EntitiesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Create a new entity
 */
export const putApiV1Entities = (
  entity: BodyType<Entity>,
  signal?: AbortSignal,
) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: entity,
    signal,
  })
}

export const getPutApiV1EntitiesMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1Entities>>,
    TError,
    { data: BodyType<Entity> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1Entities>>,
  TError,
  { data: BodyType<Entity> },
  TContext
> => {
  const mutationKey = ['putApiV1Entities']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1Entities>>,
    { data: BodyType<Entity> }
  > = (props) => {
    const { data } = props ?? {}

    return putApiV1Entities(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiV1EntitiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1Entities>>
>
export type PutApiV1EntitiesMutationBody = BodyType<Entity>
export type PutApiV1EntitiesMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create a new entity
 */
export const usePutApiV1Entities = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1Entities>>,
      TError,
      { data: BodyType<Entity> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1Entities>>,
  TError,
  { data: BodyType<Entity> },
  TContext
> => {
  return useMutation(getPutApiV1EntitiesMutationOptions(options), queryClient)
}
/**
 * Returns all properties of a specific entity.
 * @summary Get an entity
 */
export const getApiV1EntitiesEntityId = (
  entityId: string,
  signal?: AbortSignal,
) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'GET',
    signal,
  })
}

export const getGetApiV1EntitiesEntityIdQueryKey = (entityId: string) => {
  return [`/api/v1/entities/${entityId}`] as const
}

export const getGetApiV1EntitiesEntityIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1EntitiesEntityIdQueryKey(entityId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
  > = ({ signal }) => getApiV1EntitiesEntityId(entityId, signal)

  return {
    queryKey,
    queryFn,
    enabled: entityId !== null && entityId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1EntitiesEntityIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
>
export type GetApiV1EntitiesEntityIdQueryError = ErrorType<ErrorResponse>

export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an entity
 */

export function useGetApiV1EntitiesEntityId<
  TData = Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
  TError = ErrorType<ErrorResponse>,
>(
  entityId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1EntitiesEntityId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1EntitiesEntityIdQueryOptions(
    entityId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Update an entity
 */
export const postApiV1EntitiesEntityId = (
  entityId: string,
  entity: BodyType<Entity>,
  signal?: AbortSignal,
) => {
  return customInstance<AuditedEntity>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: entity,
    signal,
  })
}

export const getPostApiV1EntitiesEntityIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
    TError,
    { entityId: string; data: BodyType<Entity> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
  TError,
  { entityId: string; data: BodyType<Entity> },
  TContext
> => {
  const mutationKey = ['postApiV1EntitiesEntityId']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
    { entityId: string; data: BodyType<Entity> }
  > = (props) => {
    const { entityId, data } = props ?? {}

    return postApiV1EntitiesEntityId(entityId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1EntitiesEntityIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>
>
export type PostApiV1EntitiesEntityIdMutationBody = BodyType<Entity>
export type PostApiV1EntitiesEntityIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update an entity
 */
export const usePostApiV1EntitiesEntityId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
      TError,
      { entityId: string; data: BodyType<Entity> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1EntitiesEntityId>>,
  TError,
  { entityId: string; data: BodyType<Entity> },
  TContext
> => {
  return useMutation(
    getPostApiV1EntitiesEntityIdMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Delete an entity
 */
export const deleteApiV1EntitiesEntityId = (
  entityId: string,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/v1/entities/${encodeURIComponent(String(entityId))}`,
    method: 'DELETE',
    signal,
  })
}

export const getDeleteApiV1EntitiesEntityIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
    TError,
    { entityId: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
  TError,
  { entityId: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1EntitiesEntityId']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
    { entityId: string }
  > = (props) => {
    const { entityId } = props ?? {}

    return deleteApiV1EntitiesEntityId(entityId)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiV1EntitiesEntityIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>
>

export type DeleteApiV1EntitiesEntityIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete an entity
 */
export const useDeleteApiV1EntitiesEntityId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
      TError,
      { entityId: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1EntitiesEntityId>>,
  TError,
  { entityId: string },
  TContext
> => {
  return useMutation(
    getDeleteApiV1EntitiesEntityIdMutationOptions(options),
    queryClient,
  )
}
