/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type {
  AuthEmailWrite,
  AuthOtpChallenge,
  AuthOtpStartWrite,
  AuthToken,
  ErrorResponse,
  OtpChallengeCompletion,
  PasskeyAuthenticationChallenge,
  PasskeyAuthenticationResponse,
  PasskeyRegistrationChallenge,
  PasskeyRegistrationResponse,
  PasskeyRegistrationWrite,
} from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

/**
 * @summary Start an OTP challenge
 */
export const startOtpChallenge = (
  authOtpStartWrite: BodyType<AuthOtpStartWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthOtpChallenge>({
    url: `/api/v1/auth/otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: authOtpStartWrite,
    signal,
  })
}

export const getStartOtpChallengeMutationKey = () =>
  ['startOtpChallenge'] as const

export const getStartOtpChallengeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startOtpChallenge>>,
    TError,
    StartOtpChallengeMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof startOtpChallenge>>,
  TError,
  StartOtpChallengeMutationVariables,
  TContext
> => {
  const mutationKey = getStartOtpChallengeMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startOtpChallenge>>,
    StartOtpChallengeMutationVariables
  > = (props) => {
    const { data } = props ?? {}

    return startOtpChallenge(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartOtpChallengeMutationResult = NonNullable<
  Awaited<ReturnType<typeof startOtpChallenge>>
>
export type StartOtpChallengeMutationBody = BodyType<AuthOtpStartWrite>
export type StartOtpChallengeMutationError = ErrorType<ErrorResponse>
export type StartOtpChallengeMutationVariables = {
  data: BodyType<AuthOtpStartWrite>
}

/**
 * @summary Start an OTP challenge
 */
export const useStartOtpChallenge = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startOtpChallenge>>,
      TError,
      StartOtpChallengeMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startOtpChallenge>>,
  TError,
  StartOtpChallengeMutationVariables,
  TContext
> => {
  return useMutation(getStartOtpChallengeMutationOptions(options), queryClient)
}
/**
 * @summary Complete an OTP challenge
 */
export const completeOtpChallenge = (
  challengeId: string,
  otpChallengeCompletion: BodyType<OtpChallengeCompletion>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthToken>({
    url: `/api/v1/auth/otp/${encodeURIComponent(String(challengeId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: otpChallengeCompletion,
    signal,
  })
}

export const getCompleteOtpChallengeMutationKey = () =>
  ['completeOtpChallenge'] as const

export const getCompleteOtpChallengeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeOtpChallenge>>,
    TError,
    CompleteOtpChallengeMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeOtpChallenge>>,
  TError,
  CompleteOtpChallengeMutationVariables,
  TContext
> => {
  const mutationKey = getCompleteOtpChallengeMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeOtpChallenge>>,
    CompleteOtpChallengeMutationVariables
  > = (props) => {
    const { challengeId, data } = props ?? {}

    return completeOtpChallenge(challengeId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompleteOtpChallengeMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeOtpChallenge>>
>
export type CompleteOtpChallengeMutationBody = BodyType<OtpChallengeCompletion>
export type CompleteOtpChallengeMutationError = ErrorType<ErrorResponse>
export type CompleteOtpChallengeMutationVariables = {
  challengeId: string
  data: BodyType<OtpChallengeCompletion>
}

/**
 * @summary Complete an OTP challenge
 */
export const useCompleteOtpChallenge = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeOtpChallenge>>,
      TError,
      CompleteOtpChallengeMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completeOtpChallenge>>,
  TError,
  CompleteOtpChallengeMutationVariables,
  TContext
> => {
  return useMutation(
    getCompleteOtpChallengeMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Start passkey registration
 */
export const startPasskeyRegistration = (
  passkeyRegistrationWrite: BodyType<PasskeyRegistrationWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<PasskeyRegistrationChallenge>({
    url: `/api/v1/auth/passkey/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: passkeyRegistrationWrite,
    signal,
  })
}

export const getStartPasskeyRegistrationMutationKey = () =>
  ['startPasskeyRegistration'] as const

export const getStartPasskeyRegistrationMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startPasskeyRegistration>>,
    TError,
    StartPasskeyRegistrationMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof startPasskeyRegistration>>,
  TError,
  StartPasskeyRegistrationMutationVariables,
  TContext
> => {
  const mutationKey = getStartPasskeyRegistrationMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startPasskeyRegistration>>,
    StartPasskeyRegistrationMutationVariables
  > = (props) => {
    const { data } = props ?? {}

    return startPasskeyRegistration(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartPasskeyRegistrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof startPasskeyRegistration>>
>
export type StartPasskeyRegistrationMutationBody =
  BodyType<PasskeyRegistrationWrite>
export type StartPasskeyRegistrationMutationError = ErrorType<ErrorResponse>
export type StartPasskeyRegistrationMutationVariables = {
  data: BodyType<PasskeyRegistrationWrite>
}

/**
 * @summary Start passkey registration
 */
export const useStartPasskeyRegistration = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startPasskeyRegistration>>,
      TError,
      StartPasskeyRegistrationMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startPasskeyRegistration>>,
  TError,
  StartPasskeyRegistrationMutationVariables,
  TContext
> => {
  return useMutation(
    getStartPasskeyRegistrationMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Complete passkey registration
 */
export const completePasskeyRegistration = (
  challengeId: string,
  passkeyRegistrationResponse: BodyType<PasskeyRegistrationResponse>,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/v1/auth/passkey/create/${encodeURIComponent(String(challengeId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: passkeyRegistrationResponse,
    signal,
  })
}

export const getCompletePasskeyRegistrationMutationKey = () =>
  ['completePasskeyRegistration'] as const

export const getCompletePasskeyRegistrationMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completePasskeyRegistration>>,
    TError,
    CompletePasskeyRegistrationMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof completePasskeyRegistration>>,
  TError,
  CompletePasskeyRegistrationMutationVariables,
  TContext
> => {
  const mutationKey = getCompletePasskeyRegistrationMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completePasskeyRegistration>>,
    CompletePasskeyRegistrationMutationVariables
  > = (props) => {
    const { challengeId, data } = props ?? {}

    return completePasskeyRegistration(challengeId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompletePasskeyRegistrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof completePasskeyRegistration>>
>
export type CompletePasskeyRegistrationMutationBody =
  BodyType<PasskeyRegistrationResponse>
export type CompletePasskeyRegistrationMutationError = ErrorType<ErrorResponse>
export type CompletePasskeyRegistrationMutationVariables = {
  challengeId: string
  data: BodyType<PasskeyRegistrationResponse>
}

/**
 * @summary Complete passkey registration
 */
export const useCompletePasskeyRegistration = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completePasskeyRegistration>>,
      TError,
      CompletePasskeyRegistrationMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completePasskeyRegistration>>,
  TError,
  CompletePasskeyRegistrationMutationVariables,
  TContext
> => {
  return useMutation(
    getCompletePasskeyRegistrationMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Start passkey authentication
 */
export const startPasskeyAuthentication = (
  authEmailWrite: BodyType<AuthEmailWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<PasskeyAuthenticationChallenge>({
    url: `/api/v1/auth/passkey/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: authEmailWrite,
    signal,
  })
}

export const getStartPasskeyAuthenticationMutationKey = () =>
  ['startPasskeyAuthentication'] as const

export const getStartPasskeyAuthenticationMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startPasskeyAuthentication>>,
    TError,
    StartPasskeyAuthenticationMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof startPasskeyAuthentication>>,
  TError,
  StartPasskeyAuthenticationMutationVariables,
  TContext
> => {
  const mutationKey = getStartPasskeyAuthenticationMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startPasskeyAuthentication>>,
    StartPasskeyAuthenticationMutationVariables
  > = (props) => {
    const { data } = props ?? {}

    return startPasskeyAuthentication(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartPasskeyAuthenticationMutationResult = NonNullable<
  Awaited<ReturnType<typeof startPasskeyAuthentication>>
>
export type StartPasskeyAuthenticationMutationBody = BodyType<AuthEmailWrite>
export type StartPasskeyAuthenticationMutationError = ErrorType<ErrorResponse>
export type StartPasskeyAuthenticationMutationVariables = {
  data: BodyType<AuthEmailWrite>
}

/**
 * @summary Start passkey authentication
 */
export const useStartPasskeyAuthentication = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startPasskeyAuthentication>>,
      TError,
      StartPasskeyAuthenticationMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startPasskeyAuthentication>>,
  TError,
  StartPasskeyAuthenticationMutationVariables,
  TContext
> => {
  return useMutation(
    getStartPasskeyAuthenticationMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Complete passkey authentication
 */
export const completePasskeyAuthentication = (
  challengeId: string,
  passkeyAuthenticationResponse: BodyType<PasskeyAuthenticationResponse>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthToken>({
    url: `/api/v1/auth/passkey/login/${encodeURIComponent(String(challengeId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: passkeyAuthenticationResponse,
    signal,
  })
}

export const getCompletePasskeyAuthenticationMutationKey = () =>
  ['completePasskeyAuthentication'] as const

export const getCompletePasskeyAuthenticationMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completePasskeyAuthentication>>,
    TError,
    CompletePasskeyAuthenticationMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof completePasskeyAuthentication>>,
  TError,
  CompletePasskeyAuthenticationMutationVariables,
  TContext
> => {
  const mutationKey = getCompletePasskeyAuthenticationMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completePasskeyAuthentication>>,
    CompletePasskeyAuthenticationMutationVariables
  > = (props) => {
    const { challengeId, data } = props ?? {}

    return completePasskeyAuthentication(challengeId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompletePasskeyAuthenticationMutationResult = NonNullable<
  Awaited<ReturnType<typeof completePasskeyAuthentication>>
>
export type CompletePasskeyAuthenticationMutationBody =
  BodyType<PasskeyAuthenticationResponse>
export type CompletePasskeyAuthenticationMutationError =
  ErrorType<ErrorResponse>
export type CompletePasskeyAuthenticationMutationVariables = {
  challengeId: string
  data: BodyType<PasskeyAuthenticationResponse>
}

/**
 * @summary Complete passkey authentication
 */
export const useCompletePasskeyAuthentication = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completePasskeyAuthentication>>,
      TError,
      CompletePasskeyAuthenticationMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completePasskeyAuthentication>>,
  TError,
  CompletePasskeyAuthenticationMutationVariables,
  TContext
> => {
  return useMutation(
    getCompletePasskeyAuthenticationMutationOptions(options),
    queryClient,
  )
}
