/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Date } from './date.ts'
import type { UserId } from './userId.ts'

export type AuditedAudit = {
  createdAt: Date
  createdBy: UserId
  modifiedAt: Date
  modifiedBy: UserId
}
