/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthChallenge } from './authChallenge.ts'

export type AuthOtpChallenge = AuthChallenge & {
  /**
   * Number of digits required to complete the OTP challenge.
   * @minimum 1
   * @maximum 32
   */
  digits: number
}
