/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Date } from './date.ts'

export interface AuthChallenge {
  challengeId: string
  expiration: Date
}
