/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Languages supported for free-text fields (BCP-47 tags).
 */
export type CatalogNameItemLanguage =
  (typeof CatalogNameItemLanguage)[keyof typeof CatalogNameItemLanguage]

export const CatalogNameItemLanguage = {
  en: 'en',
  he: 'he',
  ar: 'ar',
} as const
