/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * IDHI-governed discovery categories for datasets and dataset-like intellectual objects. Choose the primary form and use tags for secondary characteristics.
 */
export type DatasetDatasetType =
  (typeof DatasetDatasetType)[keyof typeof DatasetDatasetType]

export const DatasetDatasetType = {
  DIGITAL_EDITION: 'DIGITAL_EDITION',
  CORPUS: 'CORPUS',
  DATABASE: 'DATABASE',
  GAZETTEER: 'GAZETTEER',
  IMAGE_COLLECTION: 'IMAGE_COLLECTION',
  ANNOTATION_SET: 'ANNOTATION_SET',
  METADATA_CATALOG: 'METADATA_CATALOG',
  OTHER_RESEARCH_DATA: 'OTHER_RESEARCH_DATA',
} as const
