/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator identifying the record's class; used for polymorphic serialization and deserialization.
 */
export type DatasetType = (typeof DatasetType)[keyof typeof DatasetType]

export const DatasetType = {
  'idhi:Dataset': 'idhi:Dataset',
} as const
