/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Filter } from './filter.ts'
import type { FilterableField } from './filterableField.ts'

export interface EntitySearch {
  /** Optional free-text search query. */
  q?: string
  /** Entity fields for which facet counts should be returned. */
  facets?: FilterableField[]
  filter?: Filter
  /** @minimum 0 */
  page?: number
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
}
