/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export const ErrorCode = {
  Unauthorized: 'Unauthorized',
  InvalidInput: 'InvalidInput',
  InternalServerError: 'InternalServerError',
  EntityNotFound: 'EntityNotFound',
  EntityReferenced: 'EntityReferenced',
  UserNotFound: 'UserNotFound',
  UserAlreadyInvitedOrRegistered: 'UserAlreadyInvitedOrRegistered',
  WrongOtpCode: 'WrongOtpCode',
  TooManyAuthAttempts: 'TooManyAuthAttempts',
  AuthChallengeNotFoundOrExpired: 'AuthChallengeNotFoundOrExpired',
} as const
