/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { EventEventAgentRolesItemEventAgentRole } from './eventEventAgentRolesItemEventAgentRole.ts'

/**
 * A person or organization involved in the containing Event in a defined capacity, with optional dates when the involvement covers only part of a multi-day event or programme. Use in Event.event_agent_roles for organizers, hosts, speakers, panelists, participants or sponsors; do not use it merely because an agent authored a publication presented at the event.
 */
export type EventEventAgentRolesItem = {
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** The person or organization involved in the containing event (by IDHI URN). Use only in Event.event_agent_roles; do not duplicate the relationship on the Agent. */
  event_agent: string
  /** IDHI-governed roles for people and organizations involved in events. Choose the most specific role and use separate EventAgentRole instances for multiple capacities. */
  event_agent_role: EventEventAgentRolesItemEventAgentRole
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
}
