/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Kinds of scholarly events.
 */
export type EventEventType =
  (typeof EventEventType)[keyof typeof EventEventType]

export const EventEventType = {
  CONFERENCE: 'CONFERENCE',
  WORKSHOP: 'WORKSHOP',
  SEMINAR: 'SEMINAR',
  LECTURE: 'LECTURE',
  HACKATHON: 'HACKATHON',
  EXHIBITION: 'EXHIBITION',
} as const
