/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator identifying the record's class; used for polymorphic serialization and deserialization.
 */
export type EventType = (typeof EventType)[keyof typeof EventType]

export const EventType = {
  'idhi:Event': 'idhi:Event',
} as const
