/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { FacilityAddressItem } from './facilityAddressItem.ts'
import type { FacilityDescriptionItem } from './facilityDescriptionItem.ts'
import type { FacilityFacilityAffiliationsItem } from './facilityFacilityAffiliationsItem.ts'
import type { FacilityLocationItem } from './facilityLocationItem.ts'
import type { FacilityNameItem } from './facilityNameItem.ts'
import type { FacilityType } from './facilityType.ts'

/**
 * A physical or virtual facility such as a DH lab, digitization studio or research infrastructure, affiliated with one or more organizations. Use Facility when the unit offers services/tools and has its own identity distinct from its host organization; otherwise just use the Organization.
 */
export interface Facility {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * Postal address, multilingual.
   * @nullable
   */
  address?: FacilityAddressItem[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: FacilityDescriptionItem[] | null
  /**
   * The organization(s) hosting or owning this facility, as reified FacilityAffiliation objects with dates.
   * @nullable
   */
  facility_affiliations?: FacilityFacilityAffiliationsItem[] | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:facility:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Place name where the organization, facility or event is physically situated (e.g. a city), as free multilingual text.
   * @nullable
   */
  location?: FacilityLocationItem[] | null
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name for organizations; for projects, tools and services, use the name the team itself uses.
   * @minItems 1
   * @nullable
   */
  name?: FacilityNameItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Services this facility offers to researchers. Reference Service records by id; the Service's own 'provider' may still point at the parent Organization.
   * @nullable
   */
  services_offered?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /**
   * Tools this facility maintains or gives access to (by id). Use for hosted instances and lab-maintained software, not for every tool staff members happen to use.
   * @nullable
   */
  tools_provided?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: FacilityType
}
