/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator carrying the class URI; used for polymorphic serialization and deserialization.
 */
export type FacilityType = (typeof FacilityType)[keyof typeof FacilityType]

export const FacilityType = {
  'idhi:Facility': 'idhi:Facility',
} as const
