/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * IDHI-governed roles distinguishing the organizations connected to a facility. Use one relationship per organization and role so hosting and ownership are not conflated.
 */
export type FacilityFacilityAffiliationsItemFacilityAffiliationRole =
  (typeof FacilityFacilityAffiliationsItemFacilityAffiliationRole)[keyof typeof FacilityFacilityAffiliationsItemFacilityAffiliationRole]

export const FacilityFacilityAffiliationsItemFacilityAffiliationRole = {
  HOST: 'HOST',
  OWNER: 'OWNER',
} as const
