/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export interface OauthAuthorizeResult {
  /** The client redirect URI with the authorization code and state attached */
  redirectUrl: string
}
