/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Kinds of organization. Canonical discriminator for Organization; pick the value matching the organization's PRIMARY nature.
 */
export type OrganizationOrganizationType =
  (typeof OrganizationOrganizationType)[keyof typeof OrganizationOrganizationType]

export const OrganizationOrganizationType = {
  ACADEMIC_INSTITUTION: 'ACADEMIC_INSTITUTION',
  GLAM_INSTITUTION: 'GLAM_INSTITUTION',
  RESEARCH_CENTER: 'RESEARCH_CENTER',
  FUNDER: 'FUNDER',
  COMPANY: 'COMPANY',
  NON_PROFIT: 'NON_PROFIT',
} as const
