/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export interface PasskeyRegistrationWrite {
  /**
   * Existing credential to replace after successful registration.
   * @minLength 1
   * @pattern ^[A-Za-z0-9_-]+$
   */
  replacingCredentialId?: string
}
