/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Matches @simplewebauthn/PublicKeyCredentialCreationOptionsJSON.
 */
export type PasskeyRegistrationChallengeOptions = { [key: string]: unknown }
