/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthChallenge } from './authChallenge.ts'
import type { PasskeyRegistrationChallengeOptions } from './passkeyRegistrationChallengeOptions.ts'

export type PasskeyRegistrationChallenge = AuthChallenge & {
  /** Matches @simplewebauthn/PublicKeyCredentialCreationOptionsJSON. */
  options: PasskeyRegistrationChallengeOptions
}
