/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * IDHI-governed roles and statuses for a person's formal relationship with an organization. Choose the most specific applicable role, use separate Affiliation instances for distinct concurrent or successive roles, and keep project-specific responsibilities in ProjectParticipation.
 */
export type PersonAffiliationsItemAffiliationRole =
  (typeof PersonAffiliationsItemAffiliationRole)[keyof typeof PersonAffiliationsItemAffiliationRole]

export const PersonAffiliationsItemAffiliationRole = {
  EMPLOYEE: 'EMPLOYEE',
  FACULTY: 'FACULTY',
  RESEARCHER: 'RESEARCHER',
  STUDENT: 'STUDENT',
  INTERN: 'INTERN',
  FOUNDER: 'FOUNDER',
  OWNER: 'OWNER',
  ADVISOR: 'ADVISOR',
  CONTRACTOR: 'CONTRACTOR',
  VOLUNTEER: 'VOLUNTEER',
  MEMBER: 'MEMBER',
  FELLOW: 'FELLOW',
  AFFILIATE: 'AFFILIATE',
} as const
