/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonAffiliationsItemAffiliationRole } from './personAffiliationsItemAffiliationRole.ts'

/**
 * A person's employment or membership at an organization, with a position and dates. Use for the person's institutional home(s), independent of any project.
 */
export type PersonAffiliationsItem = {
  /** A person's position within an organization (job/status). */
  affiliation_role?: PersonAffiliationsItemAffiliationRole
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** The person affiliated with the organization (by IDHI URN). */
  member: string
  /** The organization side of the relationship (by IDHI URN). */
  organization: string
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity (e.g. when a person joined a project or organization).
   * @nullable
   */
  start_date?: string | null
}
