/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonAffiliationsItemAffiliationRole } from './personAffiliationsItemAffiliationRole.ts'

/**
 * A person's formal relationship with an organization, nested in a Person so the person is inferred from the containing record. Use in Person.affiliations for employment, faculty, study, membership, ownership and other organization-level statuses independent of any project; do not provide the containing person's ID in the relationship.
 */
export type PersonAffiliationsItem = {
  /** IDHI-governed roles and statuses for a person's formal relationship with an organization. Choose the most specific applicable role, use separate Affiliation instances for distinct concurrent or successive roles, and keep project-specific responsibilities in ProjectParticipation. */
  affiliation_role?: PersonAffiliationsItemAffiliationRole
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** The organization referenced by a person affiliation or project role (by IDHI URN). The Person or Project containing the relationship supplies its other endpoint. This uses an IDHI-specific property because one slot serves two relationship types whose external terms differ (schema:affiliation for Affiliation, schema:participant for OrganizationProjectRole), so neither can be asserted for both. */
  organization: string
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
}
