/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonAffiliationsItem } from './personAffiliationsItem.ts'
import type { PersonAuthorshipsItem } from './personAuthorshipsItem.ts'
import type { PersonDescriptionItem } from './personDescriptionItem.ts'
import type { PersonProjectParticipationsItem } from './personProjectParticipationsItem.ts'
import type { PersonType } from './personType.ts'

/**
 * A human agent in the DH index: researcher, developer, librarian, student, etc.
 */
export interface Person {
  /**
   * The person's institutional affiliations, as reified Affiliation objects (organization + position + dates). Use for employment or formal membership, NOT for project involvement — that goes in project_participations.
   * @nullable
   */
  affiliations?: PersonAffiliationsItem[] | null
  /**
   * The person's publication contributions, as reified Authorship objects carrying byline order and role.
   * @nullable
   */
  authorships?: PersonAuthorshipsItem[] | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: PersonDescriptionItem[] | null
  /**
   * Contact email addresses (zero or more). Only record addresses the person has agreed to publish in the index.
   * @nullable
   */
  emails?: string[] | null
  /**
   * Family (last) name, in the person's preferred romanization. Use with given_name when the person's name is conventionally expressed in that form.
   * @nullable
   */
  family_name?: string | null
  /**
   * Given (first) name, in the person's preferred romanization. Use with family_name when the person's name is conventionally expressed in that form.
   * @nullable
   */
  given_name?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:person:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * The person's persistent researcher identifier. It supplements the IDHI record id. Strongly recommended for every researcher; enables deduplication and linking to the scholarly record.
   * @nullable
   * @pattern https://orcid.org/\d{4}-\d{4}-\d{4}-\d{3}[0-9X]
   */
  orcid?: string | null
  /**
   * The person's project involvements, as reified ProjectParticipation objects carrying the role (PI, developer...) and dates.
   * @nullable
   */
  project_participations?: PersonProjectParticipationsItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: PersonType
}
