/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Entities200FacetsItem } from './postApiV1Entities200FacetsItem.ts'

export type PostApiV1Entities200Facets = {
  [key: string]: PostApiV1Entities200FacetsItem[]
}
