/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectOrganizationRolesItemOrgProjectRole } from './projectOrganizationRolesItemOrgProjectRole.ts'

/**
 * An organization's engagement in a project. Use one instance per role: an organization that both hosts and funds a project gets two instances.
 */
export type ProjectOrganizationRolesItem = {
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** An organization's role in a project (one instance per role). */
  org_project_role?: ProjectOrganizationRolesItemOrgProjectRole
  /** The organization side of the relationship (by IDHI URN). */
  organization: string
  /** The project side of the relationship (by IDHI URN). */
  project: string
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity (e.g. when a person joined a project or organization).
   * @nullable
   */
  start_date?: string | null
}
