/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A funding award for a project, identifying the organization that provides it and its amount when public. It is inlined within the funded Project and has no independent ID.
 */
export type ProjectFundingItem = {
  /**
   * Amount awarded by the funding organization, if public, in ILS unless noted in the project description. Omit rather than guess.
   * @nullable
   */
  funding_amount?: number | null
  /** The organization that provides this funding award (by IDHI URN). */
  funding_organization: string
}
