/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * IDHI-governed values for the current primary way a project is financially or operationally sustained; no established controlled vocabulary covers these project-maintenance states. Historical grants belong in Funding records; choose the value that best describes the project's present circumstances.
 */
export type ProjectFundingStatus =
  (typeof ProjectFundingStatus)[keyof typeof ProjectFundingStatus]

export const ProjectFundingStatus = {
  ACTIVE_GRANT_FUNDING: 'ACTIVE_GRANT_FUNDING',
  INSTITUTIONALLY_SUSTAINED: 'INSTITUTIONALLY_SUSTAINED',
  IN_KIND_ONLY: 'IN_KIND_ONLY',
  VOLUNTEER_RUN: 'VOLUNTEER_RUN',
  UNFUNDED: 'UNFUNDED',
} as const
