/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * An organization's or facility's role in a project (one instance per role).
 */
export type ProjectFacilityRolesItemOrgProjectRole =
  (typeof ProjectFacilityRolesItemOrgProjectRole)[keyof typeof ProjectFacilityRolesItemOrgProjectRole]

export const ProjectFacilityRolesItemOrgProjectRole = {
  COORDINATOR: 'COORDINATOR',
  PARTNER: 'PARTNER',
  DATA_PROVIDER: 'DATA_PROVIDER',
  HOST: 'HOST',
} as const
