/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * An organization's role in a project (one instance per role).
 */
export type ProjectOrganizationRolesItemOrgProjectRole =
  (typeof ProjectOrganizationRolesItemOrgProjectRole)[keyof typeof ProjectOrganizationRolesItemOrgProjectRole]

export const ProjectOrganizationRolesItemOrgProjectRole = {
  COORDINATOR: 'COORDINATOR',
  PARTNER: 'PARTNER',
  FUNDER: 'FUNDER',
  HOST: 'HOST',
} as const
