/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Currencies in which a funding award amount may be expressed, as ISO 4217 codes. The list covers the currencies relevant to IDHI records; extend it before recording an award in another currency.
 */
export type ProjectFundingItemFundingCurrency =
  (typeof ProjectFundingItemFundingCurrency)[keyof typeof ProjectFundingItemFundingCurrency]

export const ProjectFundingItemFundingCurrency = {
  ILS: 'ILS',
  USD: 'USD',
  EUR: 'EUR',
} as const
