/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator identifying the record's class; used for polymorphic serialization and deserialization.
 */
export type PublicationType =
  (typeof PublicationType)[keyof typeof PublicationType]

export const PublicationType = {
  'idhi:Publication': 'idhi:Publication',
} as const
