/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicationAuthorshipsItem } from './publicationAuthorshipsItem.ts'
import type { PublicationDescriptionItem } from './publicationDescriptionItem.ts'
import type { PublicationNameItem } from './publicationNameItem.ts'
import type { PublicationPublicationType } from './publicationPublicationType.ts'
import type { PublicationPublishedInItem } from './publicationPublishedInItem.ts'
import type { PublicationType } from './publicationType.ts'

/**
 * An academic publication: journal article, book, chapter, conference paper, thesis, report, etc. The precise kind is given by publication_type.
 */
export interface Publication {
  /**
   * The person's publication contributions, as reified Authorship objects carrying byline order and role.
   * @nullable
   */
  authorships?: PublicationAuthorshipsItem[] | null
  /**
   * Formal publication date (or year-01-01 if only the year is known).
   * @nullable
   */
  date_issued?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: PublicationDescriptionItem[] | null
  /**
   * The publication, dataset, tool or training material's DOI persistent identifier. Record it whenever one exists; it is the preferred deduplication key and is supplementary to the IDHI URN.
   * @nullable
   * @pattern https://doi.org/.+
   */
  doi?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:publication:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * A representative image embedded as Base64-encoded binary content. Use for a single image that must travel with the entity record; omit it when no image is available, and use homepage or additional_urls for externally hosted pages rather than encoding a URL here.
   * @nullable
   */
  image?: string | null
  /** The multilingual name or title used to identify the entity. Use one LangString per available language and do not repeat a language. Prefer the official localized name for organizations; for projects, tools and services, use localized names supplied by the team rather than translating branded names without authority. */
  name: PublicationNameItem[]
  /**
   * The containing work (book for a chapter, proceedings for a paper), by IDHI URN or external URI.
   * @nullable
   */
  part_of?: string | null
  /**
   * Event(s) in the index where this publication was presented (by IDHI URN), e.g. the conference where the paper was given. Distinct from published_in, the container it appeared in.
   * @nullable
   */
  presented_at?: string[] | null
  /** The kind of publication, including journal article, book part, conference paper and thesis. */
  publication_type?: PublicationPublicationType
  /**
   * Name of the journal, book or proceedings the publication appeared in, as free multilingual text. If the container work has its own IDHI record or external URI, also link it via part_of.
   * @nullable
   */
  published_in?: PublicationPublishedInItem[] | null
  /**
   * The organization formally publishing the dataset, publication or training material (by IDHI URN); use creators for responsibility for making a training material.
   * @nullable
   */
  publisher?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: PublicationType
}
