/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicationAuthorshipsItem } from './publicationAuthorshipsItem.ts'
import type { PublicationDescriptionItem } from './publicationDescriptionItem.ts'
import type { PublicationNameItem } from './publicationNameItem.ts'
import type { PublicationPublicationType } from './publicationPublicationType.ts'
import type { PublicationPublishedInItem } from './publicationPublishedInItem.ts'
import type { PublicationType } from './publicationType.ts'

/**
 * An academic publication (BIBO document): journal article, book, chapter, conference paper, thesis, report, etc. The precise kind is given by publication_type (COAR resource type).
 */
export interface Publication {
  /**
   * The person's publication contributions, as reified Authorship objects carrying byline order and role.
   * @nullable
   */
  authorships?: PublicationAuthorshipsItem[] | null
  /**
   * Formal publication date (or year-01-01 if only the year is known).
   * @nullable
   */
  date_issued?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: PublicationDescriptionItem[] | null
  /**
   * The publication's DOI, as CURIE (DOI:10.1234/abcd) or full URL. A supplementary external identifier — the record's primary id is always the IDHI URN. Record whenever one exists; it is the preferred dedup key.
   * @nullable
   */
  doi?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name (Organization subclasses use "organization"); each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:publication:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Additional EXTERNAL identifiers beyond the primary IDHI URN and the dedicated ORCID/ROR/DOI slots, as CURIEs/URIs (e.g. Wikidata QIDs, VIAF, ISNI).
   * @nullable
   */
  identifiers?: string[] | null
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name (e.g. "Smith, John" rather than "John Smith") for people and organizations; for projects, tools and services, use the name the team itself uses.
   * @nullable
   */
  name?: PublicationNameItem[] | null
  /**
   * The containing work (book for a chapter, proceedings for a paper), by IDHI URN or external URI.
   * @nullable
   */
  part_of?: string | null
  /**
   * Event(s) in the index where this publication was presented (by IDHI URN), e.g. the conference where the paper was given. Distinct from published_in, the container it appeared in.
   * @nullable
   */
  presented_at?: string[] | null
  /** The kind of publication, as any concept from the COAR Resource Types vocabulary (the de-facto repository standard, required by OpenAIRE) — e.g. coar:c_6501 (journal article), coar:c_3248 (book part), coar:c_5794 (conference paper), coar:c_46ec (thesis). */
  publication_type?: PublicationPublicationType
  /**
   * Name of the journal, book or proceedings the publication appeared in, as free multilingual text. If the container work has its own IDHI record or external URI, also link it via part_of.
   * @nullable
   */
  published_in?: PublicationPublishedInItem[] | null
  /**
   * The organization publishing the catalog, dataset or publication (by IDHI URN).
   * @nullable
   */
  publisher?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /** Discriminator carrying the class URI; used for polymorphic serialization and deserialization. */
  type: PublicationType
}
