/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export type SearchEntityTagsParams = {
  /**
   * Optional case-insensitive substring to filter tag values by.
   */
  q?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
}
