/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entity fields that support AI-backed value suggestion.
 */
export type SuggestibleEntityField =
  (typeof SuggestibleEntityField)[keyof typeof SuggestibleEntityField]

export const SuggestibleEntityField = {
  tags: 'tags',
  digital_humanities_activities: 'digital_humanities_activities',
} as const
