/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { SuggestibleEntityField } from './suggestibleEntityField.ts'

export type SuggestEntityFieldValuesParams = {
  /**
   * The entity field to suggest values for.
   */
  field: SuggestibleEntityField
}
