/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { TimePeriodNameItemLanguage } from './timePeriodNameItemLanguage.ts'

/**
 * A single language-tagged text value. Instances are combined in a multivalued slot to give English/Hebrew/Arabic variants of one field. Follows the LinkML community rdf:langString convention. Use one LangString per language; do not repeat a language within the same field.
 */
export type TimePeriodNameItem = {
  /** Languages supported for free-text fields (BCP-47 tags). */
  language: TimePeriodNameItemLanguage
  /** The text itself, in the language given by 'language'. */
  value: string
}
