/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator identifying the record's class; used for polymorphic serialization and deserialization.
 */
export type ToolType = (typeof ToolType)[keyof typeof ToolType]

export const ToolType = {
  'idhi:Tool': 'idhi:Tool',
} as const
