/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ToolDescriptionItem } from './toolDescriptionItem.ts'
import type { ToolDigitalHumanitiesActivitiesItem } from './toolDigitalHumanitiesActivitiesItem.ts'
import type { ToolLicense } from './toolLicense.ts'
import type { ToolNameItem } from './toolNameItem.ts'
import type { ToolToolType } from './toolToolType.ts'
import type { ToolType } from './toolType.ts'

/**
 * A reusable software tool, typically produced by a project (schema:SoftwareApplication). Use Tool for software that others can install, run or call; for a human-mediated offering use Service instead.
 */
export interface Tool {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * Source-code repository URL (GitHub, GitLab...), if open.
   * @nullable
   */
  code_repository?: string | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: ToolDescriptionItem[] | null
  /**
   * Digital-humanities research activities practiced in this project, tool or service, as TaDiRAH 2.0 concepts. Prefer the most specific applicable concept (e.g. tadirah:topicModeling rather than tadirah:analyzing); multiple values are expected. This is the primary DH-facet for discovery.
   * @nullable
   */
  digital_humanities_activities?: ToolDigitalHumanitiesActivitiesItem[] | null
  /**
   * User or developer documentation for the tool or service (manual, wiki, API reference).
   * @nullable
   */
  documentation_url?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name (Organization subclasses use "organization"); each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:tool:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Additional EXTERNAL identifiers beyond the primary IDHI URN and the dedicated ORCID/ROR/DOI slots, as CURIEs/URIs (e.g. Wikidata QIDs, VIAF, ISNI).
   * @nullable
   */
  identifiers?: string[] | null
  /** Common licenses for tools and datasets. `meaning:` records the canonical URI (SPDX for software licenses, creativecommons.org for CC). Extend as needed; keep meanings canonical. */
  license?: ToolLicense
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name (e.g. "Smith, John" rather than "John Smith") for people and organizations; for projects, tools and services, use the name the team itself uses.
   * @nullable
   */
  name?: ToolNameItem[] | null
  /**
   * Main implementation language(s), comma-free single value preferred.
   * @nullable
   */
  programming_language?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /** Delivery forms for tools and kinds of services. Tool records use the software values; Service records use the service values. */
  tool_type?: ToolToolType
  /** Discriminator carrying the class URI; used for polymorphic serialization and deserialization. */
  type: ToolType
}
