/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Didactic forms of training material. Choose the form that describes the learner's intended mode of engagement rather than the resource's technical format.
 */
export type TrainingMaterialTrainingMaterialType =
  (typeof TrainingMaterialTrainingMaterialType)[keyof typeof TrainingMaterialTrainingMaterialType]

export const TrainingMaterialTrainingMaterialType = {
  TUTORIAL: 'TUTORIAL',
  LESSON: 'LESSON',
  COURSE_MATERIAL: 'COURSE_MATERIAL',
  WORKSHOP_MATERIAL: 'WORKSHOP_MATERIAL',
  SELF_PACED_EXERCISE: 'SELF_PACED_EXERCISE',
  OTHER_DIDACTIC_RESOURCE: 'OTHER_DIDACTIC_RESOURCE',
} as const
