/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingMaterialDescriptionItem } from './trainingMaterialDescriptionItem.ts'
import type { TrainingMaterialDigitalHumanitiesActivitiesItem } from './trainingMaterialDigitalHumanitiesActivitiesItem.ts'
import type { TrainingMaterialEducationalLevelItem } from './trainingMaterialEducationalLevelItem.ts'
import type { TrainingMaterialLearningOutcomesItem } from './trainingMaterialLearningOutcomesItem.ts'
import type { TrainingMaterialLicense } from './trainingMaterialLicense.ts'
import type { TrainingMaterialNameItem } from './trainingMaterialNameItem.ts'
import type { TrainingMaterialPrerequisitesItem } from './trainingMaterialPrerequisitesItem.ts'
import type { TrainingMaterialTargetAudiencesItem } from './trainingMaterialTargetAudiencesItem.ts'
import type { TrainingMaterialTrainingMaterialType } from './trainingMaterialTrainingMaterialType.ts'
import type { TrainingMaterialType } from './trainingMaterialType.ts'

/**
 * A tutorial, lesson or other didactic resource that explains how to perform an action or states learning outcomes gained by using it. Use TrainingMaterial for resources intended to teach; use Publication for scholarly communication and Tool for software that performs the action itself.
 */
export interface TrainingMaterial {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * People or organizations responsible for creating the training material (by IDHI URN). Use publisher for the organization that formally releases it when that differs from its creators.
   * @nullable
   */
  creators?: string[] | null
  /**
   * Formal publication date (or year-01-01 if only the year is known).
   * @nullable
   */
  date_issued?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: TrainingMaterialDescriptionItem[] | null
  /**
   * Digital-humanities research activities practiced in this project, tool or service, or taught by this training material. Prefer the most specific applicable activity; multiple values are expected. This is the primary DH-facet for discovery.
   * @nullable
   */
  digital_humanities_activities?:
    TrainingMaterialDigitalHumanitiesActivitiesItem[] | null
  /**
   * The publication, dataset, tool or training material's DOI persistent identifier. Record it whenever one exists; it is the preferred deduplication key and is supplementary to the IDHI URN.
   * @nullable
   * @pattern https://doi.org/.+
   */
  doi?: string | null
  /**
   * Expected learner level, as multilingual text such as beginner, intermediate or graduate. Use target_audiences for who the material serves rather than their proficiency.
   * @nullable
   */
  educational_level?: TrainingMaterialEducationalLevelItem[] | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:training_material:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * A representative image embedded as Base64-encoded binary content. Use for a single image that must travel with the entity record; omit it when no image is available, and use homepage or additional_urls for externally hosted pages rather than encoding a URL here.
   * @nullable
   */
  image?: string | null
  /**
   * Languages substantially represented in a dataset or in which instructional content is available, using BCP-47 tags. For training material, record every complete language version and do not include a language used only in captions or examples; for datasets, record the languages of the data rather than its metadata page.
   * @nullable
   * @items.pattern ^[A-Za-z]{1,8}(-[A-Za-z0-9]{1,8})*$
   */
  in_languages?: string[] | null
  /**
   * Knowledge or skills a learner should gain by completing the material, as multilingual statements. Use one entry per distinct outcome; do not use this for prerequisites.
   * @nullable
   */
  learning_outcomes?: TrainingMaterialLearningOutcomesItem[] | null
  /** Common licenses for tools, datasets and training materials. Extend as needed with canonical meanings. */
  license?: TrainingMaterialLicense
  /**
   * Direct landing or access URL for the instructional resource. Use homepage for a broader site about the material and material_url for the resource learners open.
   * @nullable
   */
  material_url?: string | null
  /**
   * Technical media type of the primary dataset distribution or training resource, preferably an IANA media type such as text/html, application/pdf, application/vnd.apache.parquet or video/mp4. Dataset records may list multiple formats; do not use this for an intellectual or didactic form, which belongs in dataset_type or training_material_type.
   * @nullable
   */
  media_type?: string | null
  /** The multilingual name or title used to identify the entity. Use one LangString per available language and do not repeat a language. Prefer the official localized name for organizations; for projects, tools and services, use localized names supplied by the team rather than translating branded names without authority. */
  name: TrainingMaterialNameItem[]
  /**
   * The larger training material of which this resource is a module or lesson (by IDHI URN). Use only for formal instructional containment, not loose topical similarity.
   * @nullable
   */
  part_of_training_material?: string | null
  /**
   * Knowledge, skills, software or prior material learners should have before starting, expressed as multilingual text. Omit when no prerequisites apply.
   * @nullable
   */
  prerequisites?: TrainingMaterialPrerequisitesItem[] | null
  /**
   * The organization formally publishing the dataset, publication or training material (by IDHI URN); use creators for responsibility for making a training material.
   * @nullable
   */
  publisher?: string | null
  /**
   * Datasets used as the subject or worked example of the material (by IDHI URN). Do not use this for incidental source data that learners never encounter.
   * @nullable
   */
  related_datasets?: string[] | null
  /**
   * Services that the material explains how to access or use (by IDHI URN). Do not use this for the organization publishing the material.
   * @nullable
   */
  related_services?: string[] | null
  /**
   * Tools whose use the material teaches or demonstrates (by IDHI URN). Do not use this merely for software used to produce the material.
   * @nullable
   */
  related_tools?: string[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /**
   * Intended learner groups, as multilingual labels such as researchers, librarians or students. Use educational_level separately for the expected level of study or expertise.
   * @nullable
   */
  target_audiences?: TrainingMaterialTargetAudiencesItem[] | null
  /** Didactic forms of training material. Choose the form that describes the learner's intended mode of engagement rather than the resource's technical format. */
  training_material_type?: TrainingMaterialTrainingMaterialType
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: TrainingMaterialType
}
