/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Common licenses for tools, datasets and training materials. Extend as needed with canonical meanings.
 */
export type TrainingMaterialLicense =
  (typeof TrainingMaterialLicense)[keyof typeof TrainingMaterialLicense]

export const TrainingMaterialLicense = {
  CC_BY_4_0: 'CC_BY_4_0',
  CC_BY_SA_4_0: 'CC_BY_SA_4_0',
  CC0_1_0: 'CC0_1_0',
  MIT: 'MIT',
  APACHE_2_0: 'APACHE_2_0',
  GPL_3_0: 'GPL_3_0',
} as const
