/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export type UiLanguage = (typeof UiLanguage)[keyof typeof UiLanguage]

export const UiLanguage = {
  en: 'en',
  he: 'he',
  ar: 'ar',
} as const
