/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { IsDraftParameter } from './isDraftParameter.ts'

export type UpdateEntityByIdParams = {
  /**
   * Whether to save the entity as a draft, visible only to its creator, the members of the creator's groups, and administrators, instead of publishing it. Defaults to false (publish).
   * An already-published entity cannot be turned back into a draft; the parameter is ignored on update once the entity is published.
   */
  isDraft?: IsDraftParameter
}
