/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Audited } from './audited.ts'
import type { Date } from './date.ts'
import type { InviteId } from './inviteId.ts'

export type UserInvite = Audited & {
  id: InviteId
  email: string
  message?: string
  expiration: Date
}
