/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

import type {
  AuthEmailWrite,
  AuthOtpStartWrite,
  OtpChallengeCompletion,
  PasskeyAuthenticationResponse,
  PasskeyRegistrationResponse,
  PasskeyRegistrationWrite,
} from '../../models'

export type StartOtpChallengeContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/otp',
  { in: { json: AuthOtpStartWrite }; out: { json: AuthOtpStartWrite } }
>
export type CompleteOtpChallengeContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/otp/:challengeId',
  {
    in: {
      param: {
        challengeId: string
      }
      json: OtpChallengeCompletion
    }
    out: {
      param: {
        challengeId: string
      }
      json: OtpChallengeCompletion
    }
  }
>
export type StartPasskeyRegistrationContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/passkey/create',
  {
    in: { json: PasskeyRegistrationWrite }
    out: { json: PasskeyRegistrationWrite }
  }
>
export type CompletePasskeyRegistrationContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/passkey/create/:challengeId',
  {
    in: {
      param: {
        challengeId: string
      }
      json: PasskeyRegistrationResponse
    }
    out: {
      param: {
        challengeId: string
      }
      json: PasskeyRegistrationResponse
    }
  }
>
export type StartPasskeyAuthenticationContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/passkey/login',
  { in: { json: AuthEmailWrite }; out: { json: AuthEmailWrite } }
>
export type CompletePasskeyAuthenticationContext<E extends Env = any> = Context<
  E,
  '/api/v1/auth/passkey/login/:challengeId',
  {
    in: {
      param: {
        challengeId: string
      }
      json: PasskeyAuthenticationResponse
    }
    out: {
      param: {
        challengeId: string
      }
      json: PasskeyAuthenticationResponse
    }
  }
>
