/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const StartOtpChallengeBody = zod
  .object({
    email: zod.email(),
  })
  .and(
    zod.object({
      lang: zod.enum(['en', 'he', 'ar']).optional(),
    }),
  )

export const startOtpChallengeResponseTwoDigitsMax = 32

export const StartOtpChallengeResponse = zod
  .object({
    challengeId: zod.string(),
    expiration: zod.iso
      .datetime({ offset: true })
      .describe('UTC date and time'),
  })
  .and(
    zod.object({
      digits: zod
        .int()
        .min(1)
        .max(startOtpChallengeResponseTwoDigitsMax)
        .describe('Number of digits required to complete the OTP challenge.'),
    }),
  )

export const CompleteOtpChallengeParams = zod.object({
  challengeId: zod.string(),
})

export const CompleteOtpChallengeBody = zod.object({
  otp: zod.string(),
})

export const CompleteOtpChallengeResponse = zod.object({
  jwt: zod.string().describe('JSON Web Token used as a bearer token'),
})

export const startPasskeyRegistrationBodyReplacingCredentialIdRegExp =
  new RegExp('^[A-Za-z0-9_-]+$')

export const StartPasskeyRegistrationBody = zod.object({
  replacingCredentialId: zod
    .string()
    .min(1)
    .regex(startPasskeyRegistrationBodyReplacingCredentialIdRegExp)
    .optional()
    .describe('Existing credential to replace after successful registration.'),
})

export const StartPasskeyRegistrationResponse = zod
  .object({
    challengeId: zod.string(),
    expiration: zod.iso
      .datetime({ offset: true })
      .describe('UTC date and time'),
  })
  .and(
    zod.object({
      options: zod
        .record(zod.string(), zod.unknown())
        .describe(
          'Matches @simplewebauthn\/PublicKeyCredentialCreationOptionsJSON.',
        ),
    }),
  )

export const CompletePasskeyRegistrationParams = zod.object({
  challengeId: zod.string(),
})

export const CompletePasskeyRegistrationBody = zod
  .record(zod.string(), zod.unknown())
  .describe('Matches @simplewebauthn\/RegistrationResponseJSON.')

export const CompletePasskeyRegistrationResponse = zod.void()

export const StartPasskeyAuthenticationBody = zod.object({
  email: zod.email(),
})

export const StartPasskeyAuthenticationResponse = zod
  .object({
    challengeId: zod.string(),
    expiration: zod.iso
      .datetime({ offset: true })
      .describe('UTC date and time'),
  })
  .and(
    zod.object({
      options: zod
        .record(zod.string(), zod.unknown())
        .describe(
          'Matches @simplewebauthn\/PublicKeyCredentialRequestOptionsJSON.',
        ),
    }),
  )

export const CompletePasskeyAuthenticationParams = zod.object({
  challengeId: zod.string(),
})

export const CompletePasskeyAuthenticationBody = zod
  .record(zod.string(), zod.unknown())
  .describe('Matches @simplewebauthn\/AuthenticationResponseJSON.')

export const CompletePasskeyAuthenticationResponse = zod.object({
  jwt: zod.string().describe('JSON Web Token used as a bearer token'),
})
