/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import {
  generateAuthenticationOptions,
  generateRegistrationOptions,
  verifyAuthenticationResponse,
  verifyRegistrationResponse,
  type AuthenticationResponseJSON,
  type RegistrationResponseJSON,
} from '@simplewebauthn/server'
import type { DatabaseService } from '../../db/service'
import type { AuthChallenge } from '../../db/models/AuthChallenge'
import { ApiError } from '../../errors/ApiError'
import { assertAuthenticatedUser } from '../../middleware/auth'
import { serializeError, type RequestLogger } from '../../middleware/logger'
import { ErrorCode } from '../../models/errorCode'
import { createAuthLink } from '../../utils/authLink'
import { createId } from '../../utils/id'
import { createJwtForUser } from '../../utils/jwt'
import { defaultLang } from '../../emails/localization'
import { createOtp, otpDigits, otpMaxAttempts } from '../../utils/otp'
import { sendOtpEmail } from '../../utils/smtp'
import {
  createInvitedUserAfterAuthentication,
  resolveAuthenticationTarget,
} from '../../utils/users'
import {
  authRateLimits,
  enforceAuthRateLimits,
} from '../../utils/authRateLimit'
import { requiredValue, splitValues } from '../../utils/values'
import { zValidator } from '../api.validator'
import {
  StartOtpChallengeContext,
  CompleteOtpChallengeContext,
  StartPasskeyRegistrationContext,
  CompletePasskeyRegistrationContext,
  StartPasskeyAuthenticationContext,
  CompletePasskeyAuthenticationContext,
} from './user-auth.context'
import {
  StartOtpChallengeBody,
  StartOtpChallengeResponse,
  CompleteOtpChallengeParams,
  CompleteOtpChallengeBody,
  CompleteOtpChallengeResponse,
  StartPasskeyRegistrationBody,
  StartPasskeyRegistrationResponse,
  CompletePasskeyRegistrationParams,
  CompletePasskeyRegistrationBody,
  StartPasskeyAuthenticationBody,
  StartPasskeyAuthenticationResponse,
  CompletePasskeyAuthenticationParams,
  CompletePasskeyAuthenticationBody,
  CompletePasskeyAuthenticationResponse,
} from './user-auth.zod'

const factory = createFactory()
const RP_NAME = 'IDHI'
const DEFAULT_CHALLENGE_TIMEOUT_MS = 5 * 60 * 1000
const LOCK_TTL_MS = 10 * 1000

type OtpChallenge = Extract<AuthChallenge, { type: 'otp' }>
type PasskeyCreateChallenge = Extract<AuthChallenge, { type: 'passkeyCreate' }>
type PasskeyLoginChallenge = Extract<AuthChallenge, { type: 'passkeyLogin' }>

function normalizeOrigin(value: string): string {
  try {
    return new URL(value).origin.toLowerCase()
  } catch {
    throw new ApiError(ErrorCode.InvalidInput, 'Invalid WebAuthn origin')
  }
}

function relyingParty(
  requestUrl: string,
  requestOrigin: string | undefined,
  allowedHosts: string | undefined,
): { origin: string; rpID: string } {
  const origin = normalizeOrigin(requestOrigin ?? requestUrl)
  const allowedOrigins = splitValues(allowedHosts).map(normalizeOrigin)

  if (allowedOrigins.length === 0) {
    throw new Error('Allowed origins must contain at least one origin')
  }

  if (!allowedOrigins.includes(origin)) {
    throw new ApiError(ErrorCode.InvalidInput, 'WebAuthn origin is not allowed')
  }

  return { origin, rpID: new URL(origin).hostname }
}

function expirationFor(options: { timeout?: number }): number {
  return Date.now() + (options.timeout ?? DEFAULT_CHALLENGE_TIMEOUT_MS)
}

function challengeNotFound(): ApiError {
  return new ApiError(
    ErrorCode.AuthChallengeNotFoundOrExpired,
    'Authentication challenge was not found or has expired',
  )
}

async function takeCreateChallenge(
  db: DatabaseService,
  logger: RequestLogger,
  challengeId: string,
): Promise<PasskeyCreateChallenge> {
  const challenge = await db.authChallenges.takeById(challengeId)

  if (
    !challenge ||
    challenge.type !== 'passkeyCreate' ||
    challenge.expiresAtEpoch <= Date.now()
  ) {
    logger.warn('Passkey registration challenge unavailable', {
      challengeId,
      actualType: challenge?.type,
      expired: challenge ? challenge.expiresAtEpoch <= Date.now() : undefined,
    })
    throw challengeNotFound()
  }

  return challenge
}

async function takeLoginChallenge(
  db: DatabaseService,
  logger: RequestLogger,
  challengeId: string,
): Promise<PasskeyLoginChallenge> {
  const challenge = await db.authChallenges.takeById(challengeId)

  if (
    !challenge ||
    challenge.type !== 'passkeyLogin' ||
    challenge.expiresAtEpoch <= Date.now()
  ) {
    logger.warn('Passkey authentication challenge unavailable', {
      challengeId,
      actualType: challenge?.type,
      expired: challenge ? challenge.expiresAtEpoch <= Date.now() : undefined,
    })
    throw challengeNotFound()
  }

  return challenge
}

function invalidPasskey(message: string): ApiError {
  return new ApiError(ErrorCode.InvalidInput, message)
}

async function getOtpChallenge(
  db: DatabaseService,
  logger: RequestLogger,
  challengeId: string,
): Promise<OtpChallenge> {
  const challenge = await db.authChallenges.getById(challengeId)
  const expired = challenge ? challenge.expiresAtEpoch <= Date.now() : false

  if (!challenge || challenge.type !== 'otp' || expired) {
    if (challenge && expired) {
      await db.authChallenges.delete(challengeId)
    }

    logger.warn('OTP challenge unavailable', {
      challengeId,
      actualType: challenge?.type,
      expired,
    })
    throw challengeNotFound()
  }

  return challenge
}

export const startOtpChallengeHandlers = factory.createHandlers(
  zValidator('json', StartOtpChallengeBody),
  zValidator('response', StartOtpChallengeResponse),
  async (c: StartOtpChallengeContext) => {
    const { email, lang } = c.req.valid('json')
    await enforceAuthRateLimits(c, [
      authRateLimits.otpStartEmail(email),
      authRateLimits.otpStartEmailDaily(email),
    ])
    const digits = otpDigits(c.env.OTP_DIGITS)
    const target = await resolveAuthenticationTarget(
      email,
      c.var.db,
      c.var.logger,
    )
    const code = createOtp(digits)
    const challengeId = createId('auth_challenge')
    const expiresAtEpoch = Date.now() + DEFAULT_CHALLENGE_TIMEOUT_MS

    await c.var.db.authChallenges.insert({
      challengeId,
      type: 'otp',
      code,
      attempts: 0,
      email: target.email,
      expiresAtEpoch,
    })

    try {
      const resolvedLang = lang ?? defaultLang(c.env.DEFAULT_LANG)
      const loginUrl = createAuthLink(
        requiredValue(c.env, 'FRONTEND_URL'),
        challengeId,
        code,
        resolvedLang,
        'otp',
      )

      await sendOtpEmail(
        target.email,
        code,
        expiresAtEpoch,
        loginUrl,
        resolvedLang,
        c.env,
      )
    } catch (error) {
      let challengeDeleted = false

      try {
        challengeDeleted = await c.var.db.authChallenges.delete(challengeId)
      } catch (cleanupError) {
        c.var.logger.error('OTP challenge cleanup after email failure threw', {
          challengeId,
          userId: target.user?.id,
          error: serializeError(cleanupError),
        })
      }

      c.var.logger.error('OTP email delivery failed', {
        challengeId,
        userId: target.user?.id,
        challengeDeleted,
        error: serializeError(error),
      })
      throw error
    }

    c.var.logger.debug('OTP challenge created and delivered', {
      challengeId,
      userId: target.user?.id,
      expiresAtEpoch,
    })

    return c.json({
      challengeId,
      expiration: new Date(expiresAtEpoch).toISOString(),
      digits,
    })
  },
)
export const completeOtpChallengeHandlers = factory.createHandlers(
  zValidator('param', CompleteOtpChallengeParams),
  zValidator('json', CompleteOtpChallengeBody),
  zValidator('response', CompleteOtpChallengeResponse),
  async (c: CompleteOtpChallengeContext) => {
    const { challengeId } = c.req.valid('param')
    const { otp } = c.req.valid('json')
    await enforceAuthRateLimits(c, [
      authRateLimits.otpCompletionChallenge(challengeId),
    ])
    const lock = await c.var.db.locks.tryLock(
      `otp_attempt:${challengeId}`,
      LOCK_TTL_MS,
    )

    if (!lock) {
      c.var.logger.warn('OTP challenge attempt lock unavailable', {
        challengeId,
      })
      throw new ApiError(
        ErrorCode.InvalidInput,
        'OTP challenge is currently being processed',
      )
    }

    try {
      const challenge = await getOtpChallenge(
        c.var.db,
        c.var.logger,
        challengeId,
      )
      await enforceAuthRateLimits(
        c,
        [
          authRateLimits.otpCompletionEmail(challenge.email),
          authRateLimits.otpCompletionEmailDaily(challenge.email),
        ],
        { includeClientIp: false },
      )
      const maxAttempts = otpMaxAttempts(c.env.OTP_MAX_ATTEMPTS)

      if (challenge.attempts >= maxAttempts) {
        await c.var.db.authChallenges.delete(challengeId)
        c.var.logger.warn('OTP challenge attempt limit reached', {
          challengeId,
          attempts: challenge.attempts,
          maxAttempts,
        })
        throw new ApiError(
          ErrorCode.TooManyAuthAttempts,
          'Maximum OTP attempts reached',
        )
      }

      if (challenge.code !== otp) {
        const attempts = challenge.attempts + 1

        if (attempts >= maxAttempts) {
          await c.var.db.authChallenges.delete(challengeId)
          c.var.logger.warn('OTP challenge attempt limit reached', {
            challengeId,
            attempts,
            maxAttempts,
          })
          throw new ApiError(
            ErrorCode.TooManyAuthAttempts,
            'Maximum OTP attempts reached',
          )
        }

        challenge.attempts = attempts
        const updatedChallenge = await c.var.db.authChallenges.update(challenge)

        if (!updatedChallenge) {
          throw challengeNotFound()
        }

        c.var.logger.warn('Incorrect OTP submitted', {
          challengeId,
          attempts,
          maxAttempts,
        })
        throw new ApiError(ErrorCode.WrongOtpCode, 'Incorrect OTP code')
      }

      if (!(await c.var.db.authChallenges.delete(challengeId))) {
        throw challengeNotFound()
      }

      const user = await createInvitedUserAfterAuthentication(
        challenge.email,
        c.var.db,
        c.var.logger,
      )

      c.var.logger.debug('OTP authentication completed', {
        challengeId,
        userId: user.id,
        attempts: challenge.attempts,
      })

      return c.json({ jwt: await createJwtForUser(user, c.env) })
    } finally {
      try {
        if (!(await lock.release())) {
          c.var.logger.warn('OTP challenge attempt lock was not released', {
            challengeId,
            lockId: lock.lockId,
          })
        }
      } catch (error) {
        c.var.logger.error('OTP challenge attempt lock release threw', {
          challengeId,
          lockId: lock.lockId,
          error: serializeError(error),
        })
      }
    }
  },
)
export const startPasskeyRegistrationHandlers = factory.createHandlers(
  zValidator('response', StartPasskeyRegistrationResponse),
  zValidator('json', StartPasskeyRegistrationBody),
  async (c: StartPasskeyRegistrationContext) => {
    const { replacingCredentialId } = c.req.valid('json')
    const user = c.get('user')
    assertAuthenticatedUser(user)
    await enforceAuthRateLimits(c, [
      authRateLimits.passkeyCreateStartUser(user.id),
    ])
    const passkeyCredentials = await c.var.db.users.getPasskeyCredentials(
      user.id,
    )

    if (
      replacingCredentialId &&
      !passkeyCredentials.some(
        (credential) => credential.id === replacingCredentialId,
      )
    ) {
      throw invalidPasskey('Passkey to replace is not registered')
    }

    const excludedCredentials = replacingCredentialId
      ? passkeyCredentials.filter(
          (credential) => credential.id !== replacingCredentialId,
        )
      : passkeyCredentials

    const { origin, rpID } = relyingParty(
      c.req.url,
      c.req.header('Origin'),
      c.env.SERVER_ALLOWED_HOSTS,
    )
    const options = await generateRegistrationOptions({
      rpName: RP_NAME,
      rpID,
      userName: user.email,
      userDisplayName: user.name ?? user.email,
      userID: new TextEncoder().encode(user.id),
      attestationType: 'none',
      authenticatorSelection: {
        residentKey: 'preferred',
        userVerification: 'required',
      },
      excludeCredentials: excludedCredentials.map((credential) => ({
        id: credential.id,
        transports: credential.transports,
      })),
    })
    const challengeId = createId('auth_challenge')
    const expiresAtEpoch = expirationFor(options)

    await c.var.db.authChallenges.insert({
      challengeId,
      type: 'passkeyCreate',
      userId: user.id,
      ...(replacingCredentialId ? { replacingCredentialId } : {}),
      expectedOrigin: origin,
      expectedRPID: rpID,
      expiresAtEpoch,
      options,
    })

    c.var.logger.debug('Passkey registration challenge created', {
      challengeId,
      userId: user.id,
      rpID,
      expiresAtEpoch,
      replacingCredentialId,
      excludedCredentialCount: excludedCredentials.length,
    })

    return c.json({
      challengeId,
      expiration: new Date(expiresAtEpoch).toISOString(),
      options,
    })
  },
)
export const completePasskeyRegistrationHandlers = factory.createHandlers(
  zValidator('param', CompletePasskeyRegistrationParams),
  zValidator('json', CompletePasskeyRegistrationBody),
  async (c: CompletePasskeyRegistrationContext) => {
    const authenticatedUser = c.get('user')
    assertAuthenticatedUser(authenticatedUser)
    const { challengeId } = c.req.valid('param')
    await enforceAuthRateLimits(c, [
      authRateLimits.passkeyCreateCompletionUser(authenticatedUser.id),
    ])
    const response = c.req.valid('json') as unknown as RegistrationResponseJSON
    const challenge = await takeCreateChallenge(
      c.var.db,
      c.var.logger,
      challengeId,
    )

    if (challenge.userId !== authenticatedUser.id) {
      c.var.logger.warn('Passkey registration challenge user mismatch', {
        challengeId,
        challengeUserId: challenge.userId,
        authenticatedUserId: authenticatedUser.id,
      })
      throw challengeNotFound()
    }

    let verification

    try {
      verification = await verifyRegistrationResponse({
        response,
        expectedChallenge: challenge.options.challenge,
        expectedOrigin: challenge.expectedOrigin,
        expectedRPID: challenge.expectedRPID,
      })
    } catch (error) {
      c.var.logger.warn('Passkey registration verification threw', {
        challengeId,
        error: serializeError(error),
      })
      throw invalidPasskey('Passkey registration could not be verified')
    }

    if (!verification.verified) {
      c.var.logger.warn('Passkey registration verification failed', {
        challengeId,
      })
      throw invalidPasskey('Passkey registration could not be verified')
    }

    const { credential, credentialDeviceType, credentialBackedUp } =
      verification.registrationInfo
    const passkeyCredential = {
      id: credential.id,
      publicKey: credential.publicKey,
      webauthnUserID: challenge.options.user.id,
      counter: credential.counter,
      deviceType: credentialDeviceType,
      backedUp: credentialBackedUp,
      transports: credential.transports,
    }
    const enrollment = challenge.replacingCredentialId
      ? await c.var.db.users.replacePasskeyCredential(
          challenge.userId,
          challenge.replacingCredentialId,
          passkeyCredential,
        )
      : await c.var.db.users.enrollPasskeyCredential(
          challenge.userId,
          passkeyCredential,
        )

    if (enrollment === 'duplicate') {
      c.var.logger.warn('Passkey is already registered for user', {
        challengeId,
        userId: challenge.userId,
      })
      throw invalidPasskey('Passkey is already registered')
    }

    if (enrollment === 'userNotFound') {
      c.var.logger.warn('Passkey registration user update missed', {
        challengeId,
        userId: challenge.userId,
      })
      throw new ApiError(ErrorCode.UserNotFound, 'User no longer exists')
    }

    if (enrollment === 'credentialNotFound') {
      c.var.logger.warn('Passkey replacement target no longer exists', {
        challengeId,
        userId: challenge.userId,
      })
      throw invalidPasskey('Passkey to replace is no longer registered')
    }

    c.var.logger.debug('Passkey registration completed', {
      challengeId,
      userId: challenge.userId,
      replacedCredential: enrollment === 'replaced',
    })

    return c.body(null, 204)
  },
)
export const startPasskeyAuthenticationHandlers = factory.createHandlers(
  zValidator('response', StartPasskeyAuthenticationResponse),
  zValidator('json', StartPasskeyAuthenticationBody),
  async (c: StartPasskeyAuthenticationContext) => {
    const { email } = c.req.valid('json')
    await enforceAuthRateLimits(c, [
      authRateLimits.passkeyLoginStartEmail(email),
    ])
    const target = await resolveAuthenticationTarget(
      email,
      c.var.db,
      c.var.logger,
    )
    const { origin, rpID } = relyingParty(
      c.req.url,
      c.req.header('Origin'),
      c.env.SERVER_ALLOWED_HOSTS,
    )
    const options = await generateAuthenticationOptions({
      rpID,
      userVerification: 'required',
      allowCredentials: (target.user?.passkeyCredentials ?? []).map(
        (credential) => ({
          id: credential.id,
          transports: credential.transports,
        }),
      ),
    })
    const challengeId = createId('auth_challenge')
    const expiresAtEpoch = expirationFor(options)

    await c.var.db.authChallenges.insert({
      challengeId,
      type: 'passkeyLogin',
      email: target.email,
      expectedOrigin: origin,
      expectedRPID: rpID,
      expiresAtEpoch,
      options,
    })

    c.var.logger.debug('Passkey authentication challenge created', {
      challengeId,
      userId: target.user?.id,
      rpID,
      expiresAtEpoch,
      allowedCredentialCount: target.user?.passkeyCredentials.length ?? 0,
    })

    return c.json({
      challengeId,
      expiration: new Date(expiresAtEpoch).toISOString(),
      options,
    })
  },
)
export const completePasskeyAuthenticationHandlers = factory.createHandlers(
  zValidator('param', CompletePasskeyAuthenticationParams),
  zValidator('json', CompletePasskeyAuthenticationBody),
  zValidator('response', CompletePasskeyAuthenticationResponse),
  async (c: CompletePasskeyAuthenticationContext) => {
    const { challengeId } = c.req.valid('param')
    await enforceAuthRateLimits(c, [
      authRateLimits.passkeyLoginCompletionChallenge(challengeId),
    ])
    const response = c.req.valid(
      'json',
    ) as unknown as AuthenticationResponseJSON
    const challenge = await takeLoginChallenge(
      c.var.db,
      c.var.logger,
      challengeId,
    )
    const user = await c.var.db.users.getByEmail(challenge.email)

    if (!user) {
      c.var.logger.warn('Passkey authentication user no longer exists', {
        challengeId,
      })
      throw new ApiError(ErrorCode.UserNotFound, 'User no longer exists')
    }

    const credential = user.passkeyCredentials.find(
      (candidate) => candidate.id === response.id,
    )

    if (!credential) {
      c.var.logger.warn('Passkey is not registered for user', {
        challengeId,
        userId: user.id,
      })
      throw invalidPasskey('Passkey is not registered for this user')
    }

    let verification

    try {
      verification = await verifyAuthenticationResponse({
        response,
        expectedChallenge: challenge.options.challenge,
        expectedOrigin: challenge.expectedOrigin,
        expectedRPID: challenge.expectedRPID,
        credential: {
          id: credential.id,
          publicKey: new Uint8Array(credential.publicKey),
          counter: credential.counter,
          transports: credential.transports,
        },
      })
    } catch (error) {
      c.var.logger.warn('Passkey authentication verification threw', {
        challengeId,
        userId: user.id,
        error: serializeError(error),
      })
      throw invalidPasskey('Passkey authentication could not be verified')
    }

    if (!verification.verified) {
      c.var.logger.warn('Passkey authentication verification failed', {
        challengeId,
        userId: user.id,
      })
      throw invalidPasskey('Passkey authentication could not be verified')
    }

    credential.counter = verification.authenticationInfo.newCounter
    const updatedUser = await c.var.db.users.update(user)

    if (!updatedUser) {
      c.var.logger.warn('Passkey authentication user update missed', {
        challengeId,
        userId: user.id,
      })
      throw new ApiError(ErrorCode.UserNotFound, 'User no longer exists')
    }

    c.var.logger.debug('Passkey authentication completed', {
      challengeId,
      userId: updatedUser.id,
    })

    return c.json({
      jwt: await createJwtForUser(updatedUser, c.env),
    })
  },
)
