/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

export const PostApiV1AuthOtpBody = zod.object({
  email: zod.email(),
})

export const PostApiV1AuthOtpResponse = zod.strictObject({
  challengeId: zod.string(),
  expiration: zod.iso.datetime({ offset: true }).describe('UTC date and time'),
})

export const PostApiV1AuthOtpChallengeIdParams = zod.object({
  challengeId: zod.string(),
})

export const PostApiV1AuthOtpChallengeIdBody = zod.object({
  otp: zod.string(),
})

export const PostApiV1AuthOtpChallengeIdResponse = zod.strictObject({
  jwt: zod.string().describe('JSON Web Token used as a bearer token'),
})

export const PostApiV1AuthPasskeyCreateResponse = zod.strictObject({
  challengeId: zod.string(),
  expiration: zod.iso.datetime({ offset: true }).describe('UTC date and time'),
  options: zod
    .record(zod.string(), zod.unknown())
    .describe(
      'Matches @simplewebauthn\/PublicKeyCredentialCreationOptionsJSON.',
    ),
})

export const PostApiV1AuthPasskeyCreateChallengeIdParams = zod.object({
  challengeId: zod.string(),
})

export const PostApiV1AuthPasskeyCreateChallengeIdBody = zod
  .record(zod.string(), zod.unknown())
  .describe('Matches @simplewebauthn\/RegistrationResponseJSON.')

export const PostApiV1AuthPasskeyCreateChallengeIdResponse = zod.void()

export const PostApiV1AuthPasskeyLoginBody = zod.object({
  email: zod.email(),
})

export const PostApiV1AuthPasskeyLoginResponse = zod.strictObject({
  challengeId: zod.string(),
  expiration: zod.iso.datetime({ offset: true }).describe('UTC date and time'),
  options: zod
    .record(zod.string(), zod.unknown())
    .describe(
      'Matches @simplewebauthn\/PublicKeyCredentialRequestOptionsJSON.',
    ),
})

export const PostApiV1AuthPasskeyLoginChallengeIdParams = zod.object({
  challengeId: zod.string(),
})

export const PostApiV1AuthPasskeyLoginChallengeIdBody = zod
  .record(zod.string(), zod.unknown())
  .describe('Matches @simplewebauthn\/AuthenticationResponseJSON.')

export const PostApiV1AuthPasskeyLoginChallengeIdResponse = zod.strictObject({
  jwt: zod.string().describe('JSON Web Token used as a bearer token'),
})
