/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { zValidator } from '../api.validator'
import {
  PostApiV1AuthOtpContext,
  PostApiV1AuthOtpChallengeIdContext,
  PostApiV1AuthPasskeyCreateContext,
  PostApiV1AuthPasskeyCreateChallengeIdContext,
  PostApiV1AuthPasskeyLoginContext,
  PostApiV1AuthPasskeyLoginChallengeIdContext,
} from './user-auth.context'
import {
  PostApiV1AuthOtpBody,
  PostApiV1AuthOtpResponse,
  PostApiV1AuthOtpChallengeIdParams,
  PostApiV1AuthOtpChallengeIdBody,
  PostApiV1AuthOtpChallengeIdResponse,
  PostApiV1AuthPasskeyCreateBody,
  PostApiV1AuthPasskeyCreateResponse,
  PostApiV1AuthPasskeyCreateChallengeIdParams,
  PostApiV1AuthPasskeyCreateChallengeIdBody,
  PostApiV1AuthPasskeyLoginBody,
  PostApiV1AuthPasskeyLoginResponse,
  PostApiV1AuthPasskeyLoginChallengeIdParams,
  PostApiV1AuthPasskeyLoginChallengeIdBody,
  PostApiV1AuthPasskeyLoginChallengeIdResponse,
} from './user-auth.zod'

const factory = createFactory()
export const postApiV1AuthOtpHandlers = factory.createHandlers(
  zValidator('json', PostApiV1AuthOtpBody),
  zValidator('response', PostApiV1AuthOtpResponse),
  async (c: PostApiV1AuthOtpContext) => {},
)
export const postApiV1AuthOtpChallengeIdHandlers = factory.createHandlers(
  zValidator('param', PostApiV1AuthOtpChallengeIdParams),
  zValidator('json', PostApiV1AuthOtpChallengeIdBody),
  zValidator('response', PostApiV1AuthOtpChallengeIdResponse),
  async (c: PostApiV1AuthOtpChallengeIdContext) => {},
)
export const postApiV1AuthPasskeyCreateHandlers = factory.createHandlers(
  zValidator('response', PostApiV1AuthPasskeyCreateResponse),
  zValidator('json', PostApiV1AuthPasskeyCreateBody),
  async (c: PostApiV1AuthPasskeyCreateContext) => {},
)
export const postApiV1AuthPasskeyCreateChallengeIdHandlers =
  factory.createHandlers(
    zValidator('param', PostApiV1AuthPasskeyCreateChallengeIdParams),
    zValidator('json', PostApiV1AuthPasskeyCreateChallengeIdBody),
    async (c: PostApiV1AuthPasskeyCreateChallengeIdContext) => {},
  )
export const postApiV1AuthPasskeyLoginHandlers = factory.createHandlers(
  zValidator('response', PostApiV1AuthPasskeyLoginResponse),
  zValidator('json', PostApiV1AuthPasskeyLoginBody),
  async (c: PostApiV1AuthPasskeyLoginContext) => {},
)
export const postApiV1AuthPasskeyLoginChallengeIdHandlers =
  factory.createHandlers(
    zValidator('param', PostApiV1AuthPasskeyLoginChallengeIdParams),
    zValidator('json', PostApiV1AuthPasskeyLoginChallengeIdBody),
    zValidator('response', PostApiV1AuthPasskeyLoginChallengeIdResponse),
    async (c: PostApiV1AuthPasskeyLoginChallengeIdContext) => {},
  )
