/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { GetApiV1HealthContext } from './default.context'

const factory = createFactory()
export const getApiV1HealthHandlers = factory.createHandlers(
  async (c: GetApiV1HealthContext) => {},
)
