/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

export type GetApiV1HealthContext<E extends Env = any> = Context<
  E,
  '/api/v1/health'
>
