/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono'

export type GetHealthContext<E extends Env = any> = Context<E, '/api/v1/health'>
