/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory'
import { ApiError } from '../../errors/ApiError'
import { ErrorCode } from '../../models/errorCode'
import { GetHealthContext } from './default.context.ts'

const factory = createFactory()
export const getHealthHandlers = factory.createHandlers(
  async (c: GetHealthContext) => {
    if (!(await c.var.db.isLive())) {
      throw new ApiError(ErrorCode.InvalidInput, 'Database is unavailable', 503)
    }

    return c.json({ status: 'ok' })
  },
)
