//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'
import jsxA11y from 'eslint-plugin-jsx-a11y'

export default [
  ...tanstackConfig,
  {
    files: ['**/*.{js,mjs,cjs,jsx,mjsx,ts,tsx,mtsx}'],
    ...jsxA11y.flatConfigs.recommended,
  },
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'never' },
      ],
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
      'no-console': 'error',
      'jsx-a11y/no-autofocus': ['error', { ignoreNonDOM: true }],
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      curly: ['error', 'all'],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/oklch\\(/]',
          message:
            'Do not use raw oklch() in class strings — it is not a valid Tailwind class. Use theme tokens (e.g. bg-foreground) instead.',
        },
        {
          selector: 'TemplateElement[value.raw=/oklch\\(/]',
          message:
            'Do not use raw oklch() in class strings — it is not a valid Tailwind class. Use theme tokens (e.g. bg-foreground) instead.',
        },
      ],
    },
  },
  {
    files: ['src/api/**'],
    rules: {
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
    },
  },
  {
    files: ['src/api/hooks/**', 'src/api/models/**'],
    rules: {
      // Generated by Orval; assertions must be changed at the generator level.
      '@typescript-eslint/consistent-type-assertions': 'off',
    },
  },
  {
    ignores: ['eslint.config.js', 'prettier.config.js'],
  },
]
