/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedAudit } from './auditedAudit.ts'

export interface Audited {
  audit?: AuditedAudit
}
