/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Audited } from './audited'
import type { Entity } from './entity'

export type AuditedEntity = Entity &
  Audited & {
    /** Whether the entity is a draft, visible only to its creator and administrators. */
    isDraft?: boolean
  }
