/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthEmailWrite } from './authEmailWrite.ts'
import type { UiLanguage } from './uiLanguage.ts'

export type AuthOtpStartWrite = AuthEmailWrite & {
  lang?: UiLanguage
}
