/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthEmailWrite } from './authEmailWrite'
import type { Language } from './language'

export type AuthOtpStartWrite = AuthEmailWrite & {
  lang?: Language
}
