/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { DatasetResourceContributionsItemResourceContributionRole } from './datasetResourceContributionsItemResourceContributionRole'

/**
 * A person or organization contributing to the containing Tool or Dataset in a defined capacity, with optional dates for time-bounded responsibility. Use in Tool.resource_contributions or Dataset.resource_contributions for creation, software development, maintenance, data curation or other named contributions; use publisher where supported for formal publication responsibility and Project.project_participations for project-level work.
 */
export type DatasetResourceContributionsItem = {
  /** The person or organization contributing to the containing Tool or Dataset (by IDHI URN). Use only in resource_contributions; do not duplicate the relationship on the Agent. */
  contributor: string
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** Roles for named contributions to tools and datasets. Use the most specific responsibility and record separate contributions when one agent holds multiple materially different roles. */
  resource_contribution_role: DatasetResourceContributionsItemResourceContributionRole
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
}
