/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { EventAddressItemLanguage } from './eventAddressItemLanguage'

/**
 * A single language-tagged text value. Instances are combined in a multivalued slot to give English/Hebrew/Arabic variants of one field. Use one LangString per language; do not repeat a language within the same field.
 */
export type EventAddressItem = {
  /** Languages supported for free-text fields (BCP-47 tags). */
  language: EventAddressItemLanguage
  /** A localized text, in the language given by 'language'. */
  value: string
}
