/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * IDHI-governed roles for people and organizations involved in events. Choose the most specific role and use separate EventAgentRole instances for multiple capacities.
 */
export type EventEventAgentRolesItemEventAgentRole =
  (typeof EventEventAgentRolesItemEventAgentRole)[keyof typeof EventEventAgentRolesItemEventAgentRole]

export const EventEventAgentRolesItemEventAgentRole = {
  ORGANIZER: 'ORGANIZER',
  HOST: 'HOST',
  SPEAKER: 'SPEAKER',
  PANELIST: 'PANELIST',
  PARTICIPANT: 'PARTICIPANT',
  SPONSOR: 'SPONSOR',
} as const
