/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { EventDescriptionItem } from './eventDescriptionItem'
import type { EventEventType } from './eventEventType'
import type { EventNameItem } from './eventNameItem'
import type { EventType } from './eventType'

/**
 * A scholarly event: conference, workshop, seminar, lecture, hackathon or exhibition. Use Event for time-bounded gatherings; recurring series should be modeled as one Event per occurrence.
 */
export interface Event {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: EventDescriptionItem[] | null
  /**
   * End of the event, relationship or time period. Omit for ongoing relationships and open-ended periods.
   * @nullable
   */
  end_date?: string | null
  /** Kinds of scholarly events. */
  event_type?: EventEventType
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name (Organization subclasses use "organization"); each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:event:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Additional EXTERNAL identifiers beyond the primary IDHI URN and the dedicated ORCID/ROR/DOI slots, as CURIEs/URIs (e.g. Wikidata QIDs, VIAF, ISNI).
   * @nullable
   */
  identifiers?: string[] | null
  /**
   * Where the organization, facility or event is physically situated.
   * @nullable
   */
  location?: string | null
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name (e.g. "Smith, John" rather than "John Smith") for people and organizations; for projects, tools and services, use the name the team itself uses.
   * @nullable
   */
  name?: EventNameItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Start of the event or of a relationship's validity (e.g. when a person joined a project or organization).
   * @nullable
   */
  start_date?: string | null
  /** Discriminator carrying the class URI; used for polymorphic serialization and deserialization. */
  type: EventType
}
