/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A facility's affiliation with an organization. Use one instance per hosting/owning organization; joint labs get several.
 */
export type FacilityFacilityAffiliationsItem = {
  /**
   * End of the event, relationship or time period. Omit for ongoing relationships and open-ended periods.
   * @nullable
   */
  end_date?: string | null
  /** The facility side of the relationship (by IDHI URN). */
  facility: string
  /** The organization side of the relationship (by IDHI URN). */
  organization: string
  /**
   * Start of the event or of a relationship's validity (e.g. when a person joined a project or organization).
   * @nullable
   */
  start_date?: string | null
}
