/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterableField } from './filterableField.ts'
import type { FilterOperator } from './filterOperator.ts'

export type Filter =
  | {
      field: FilterableField
      op: FilterOperator
      value: unknown
    }
  | {
      /** @minItems 1 */
      and: Filter[]
    }
  | {
      /** @minItems 1 */
      or: Filter[]
    }
