/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedEntity } from './auditedEntity'
import type { GetApiV1Entities200Facets } from './getApiV1Entities200Facets'

export type GetApiV1Entities200 = {
  results: AuditedEntity[]
  facets: GetApiV1Entities200Facets
  total: number
}
