/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user.ts'

export type ListUsers200 = {
  results: User[]
  total: number
}
