/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { LocationAddressItem } from './locationAddressItem'
import type { LocationDescriptionItem } from './locationDescriptionItem'
import type { LocationNameItem } from './locationNameItem'
import type { LocationType } from './locationType'

/**
 * A place, optionally with geographic coordinates. Used both for where things ARE (org/facility/event location) and for places STUDIED by a project (studied_places).
 */
export interface Location {
  /**
   * Postal address, multilingual.
   * @nullable
   */
  address?: LocationAddressItem[] | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: LocationDescriptionItem[] | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name (Organization subclasses use "organization"); each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:location:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Additional EXTERNAL identifiers beyond the primary IDHI URN and the dedicated ORCID/ROR/DOI slots, as CURIEs/URIs (e.g. Wikidata QIDs, VIAF, ISNI).
   * @nullable
   */
  identifiers?: string[] | null
  /**
   * WGS84 latitude in decimal degrees.
   * @nullable
   */
  latitude?: number | null
  /**
   * WGS84 longitude in decimal degrees.
   * @nullable
   */
  longitude?: number | null
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name (e.g. "Smith, John" rather than "John Smith") for people and organizations; for projects, tools and services, use the name the team itself uses.
   * @nullable
   */
  name?: LocationNameItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /** Discriminator carrying the class URI; used for polymorphic serialization and deserialization. */
  type: LocationType
}
