/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

export type OauthAuthorizeWriteCodeChallengeMethod =
  (typeof OauthAuthorizeWriteCodeChallengeMethod)[keyof typeof OauthAuthorizeWriteCodeChallengeMethod]

export const OauthAuthorizeWriteCodeChallengeMethod = {
  S256: 'S256',
} as const
