/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationAddressItem } from './organizationAddressItem.ts'
import type { OrganizationDescriptionItem } from './organizationDescriptionItem.ts'
import type { OrganizationLocationItem } from './organizationLocationItem.ts'
import type { OrganizationNameItem } from './organizationNameItem.ts'
import type { OrganizationOrganizationStructureItem } from './organizationOrganizationStructureItem.ts'
import type { OrganizationOrganizationType } from './organizationOrganizationType.ts'
import type { OrganizationType } from './organizationType.ts'

/**
 * An organization of any kind. Its kind (academic institution, GLAM, research center, funder, company, non-profit or informal group) is given by organization_type. All organizations use the idhi:organization:<shortid> URN form.
 */
export interface Organization {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * Postal address, multilingual.
   * @nullable
   */
  address?: OrganizationAddressItem[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: OrganizationDescriptionItem[] | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:organization:[0-9a-z]{4,12}$
   */
  readonly id: string
  /**
   * A representative image embedded as Base64-encoded binary content. Use for a single image that must travel with the entity record; omit it when no image is available, and use homepage or additional_urls for externally hosted pages rather than encoding a URL here.
   * @nullable
   */
  image?: string | null
  /**
   * Place name where the organization, facility or event is physically situated (e.g. a city), as free multilingual text.
   * @nullable
   */
  location?: OrganizationLocationItem[] | null
  /** The multilingual name or title used to identify the entity. Use one LangString per available language and do not repeat a language. Prefer the official localized name for organizations; for projects, tools and services, use localized names supplied by the team rather than translating branded names without authority. */
  name: OrganizationNameItem[]
  /**
   * Formal parent relationships of the containing organization, with the parent and optional start and end dates. Define each containment relationship only on the child organization; use organization_roles for project partnerships and omit this slot for informal associations. This uses an IDHI-specific property because established parent-organization properties point directly to the parent and cannot carry relationship dates.
   * @nullable
   */
  organization_structure?: OrganizationOrganizationStructureItem[] | null
  /** Kinds of organization. Canonical discriminator for Organization; pick the value matching the organization's PRIMARY nature. */
  organization_type?: OrganizationOrganizationType
  /**
   * The organization's persistent registry identifier. It supplements the IDHI record id. Record it whenever the organization is registered in ROR — most universities and research institutes are.
   * @nullable
   * @pattern https://ror.org/0[a-hj-km-np-tv-z0-9]{6}[0-9]{2}
   */
  ror?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: OrganizationType
}
