/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Matches @simplewebauthn/PublicKeyCredentialRequestOptionsJSON.
 */
export type PasskeyAuthenticationChallengeOptions = { [key: string]: unknown }
