/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthChallenge } from './authChallenge'
import type { PasskeyAuthenticationChallengeOptions } from './passkeyAuthenticationChallengeOptions'

export type PasskeyAuthenticationChallenge = AuthChallenge & {
  /** Matches @simplewebauthn/PublicKeyCredentialRequestOptionsJSON. */
  options: PasskeyAuthenticationChallengeOptions
}
