/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator identifying the record's class; used for polymorphic serialization and deserialization.
 */
export type PersonType = (typeof PersonType)[keyof typeof PersonType]

export const PersonType = {
  'idhi:Person': 'idhi:Person',
} as const
