/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A person's role in a project. Where a CRediT (Contributor Roles Taxonomy) concept approximates the role, `meaning:` records it.
 */
export type PersonProjectParticipationsItemParticipationRole =
  (typeof PersonProjectParticipationsItemParticipationRole)[keyof typeof PersonProjectParticipationsItemParticipationRole]

export const PersonProjectParticipationsItemParticipationRole = {
  PRINCIPAL_INVESTIGATOR: 'PRINCIPAL_INVESTIGATOR',
  CO_PI: 'CO_PI',
  RESEARCHER: 'RESEARCHER',
  DEVELOPER: 'DEVELOPER',
  STUDENT: 'STUDENT',
  ADVISOR: 'ADVISOR',
  CONTRIBUTOR: 'CONTRIBUTOR',
} as const
