/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedEntity } from './auditedEntity'
import type { PostApiV1Entities200Facets } from './postApiV1Entities200Facets'

export type PostApiV1Entities200 = {
  results: AuditedEntity[]
  facets: PostApiV1Entities200Facets
  /** Total number of matching entities across all pages. */
  total: number
}
