/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectDescriptionItem } from './projectDescriptionItem.ts'
import type { ProjectDigitalHumanitiesActivitiesItem } from './projectDigitalHumanitiesActivitiesItem.ts'
import type { ProjectFundingItem } from './projectFundingItem.ts'
import type { ProjectFundingStatus } from './projectFundingStatus.ts'
import type { ProjectNameItem } from './projectNameItem.ts'
import type { ProjectOrganizationRolesItem } from './projectOrganizationRolesItem.ts'
import type { ProjectProjectParticipationsItem } from './projectProjectParticipationsItem.ts'
import type { ProjectResearchDisciplinesItem } from './projectResearchDisciplinesItem.ts'
import type { ProjectStudiedPeriodsItem } from './projectStudiedPeriodsItem.ts'
import type { ProjectStudiedPlacesItem } from './projectStudiedPlacesItem.ts'
import type { ProjectType } from './projectType.ts'

/**
 * A Digital Humanities research project, classified by its research activities and disciplines. This is the central entity of the index; people, organizations, outputs and studied periods/places all hang off it.
 */
export interface Project {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: ProjectDescriptionItem[] | null
  /**
   * Digital-humanities research activities practiced in this project, tool, service or dataset, or taught by this training material. Prefer the most specific applicable activity; multiple values are expected. This is the primary DH-facet for discovery.
   * @nullable
   */
  digital_humanities_activities?:
    ProjectDigitalHumanitiesActivitiesItem[] | null
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /**
   * Funding awards received by the project. Use one entry per distinct award, including successive awards from the same organization, and record award dates here rather than duplicating the same fact as a FUNDER organization role.
   * @nullable
   */
  funding?: ProjectFundingItem[] | null
  /** IDHI-governed values for the current primary way a project is financially or operationally sustained; no established controlled vocabulary covers these project-maintenance states. Historical grants belong in Funding records; choose the value that best describes the project's present circumstances. */
  funding_status?: ProjectFundingStatus
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:project:[0-9a-z]{4,12}$
   */
  readonly id: string
  /**
   * A representative image embedded as Base64-encoded binary content. Use for a single image that must travel with the entity record; omit it when no image is available, and use homepage or additional_urls for externally hosted pages rather than encoding a URL here.
   * @nullable
   */
  image?: string | null
  /** The multilingual name or title used to identify the entity. Use one LangString per available language and do not repeat a language. Prefer the official localized name for organizations; for projects, tools and services, use localized names supplied by the team rather than translating branded names without authority. */
  name: ProjectNameItem[]
  /**
   * Organizations engaged in the containing project, as reified OrganizationProjectRole objects carrying a coordinator, partner, data provider, funder or host role. Reference each organization and infer the project from its containing record; use FUNDER only when no distinct award can be represented in funding.
   * @nullable
   */
  organization_roles?: ProjectOrganizationRolesItem[] | null
  /**
   * Datasets produced or curated by this project (by id).
   * @nullable
   */
  outputs_datasets?: string[] | null
  /**
   * Publications resulting from this project (by id).
   * @nullable
   */
  outputs_publications?: string[] | null
  /**
   * Tools produced by this project (by id).
   * @nullable
   */
  outputs_tools?: string[] | null
  /**
   * Training materials produced by this project (by IDHI URN); use only for project outputs, not materials merely used by the project.
   * @nullable
   */
  outputs_training_materials?: string[] | null
  /**
   * People involved in the containing project, as reified ProjectParticipation objects carrying participant, role and dates. Define each participation only here on its Project; do not duplicate it on the Person.
   * @nullable
   */
  project_participations?: ProjectProjectParticipationsItem[] | null
  /**
   * Humanities discipline(s) of the project (history, linguistics, archaeology...). Free multilingual text for now; a controlled vocabulary is a planned upgrade.
   * @nullable
   */
  research_disciplines?: ProjectResearchDisciplinesItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
  /**
   * Historical period(s) the project studies (e.g. Ottoman period), as free multilingual labels — distinct from the project's own start_date/end_date.
   * @nullable
   */
  studied_periods?: ProjectStudiedPeriodsItem[] | null
  /**
   * Geographic focus of the research (places studied), as free multilingual labels — distinct from where the project team sits.
   * @nullable
   */
  studied_places?: ProjectStudiedPlacesItem[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: ProjectType
  /**
   * Existing datasets used as research inputs by the containing project (by IDHI URN). Use for source or reference data consumed by the project, not datasets produced by it, which belong in outputs_datasets.
   * @nullable
   */
  uses_datasets?: string[] | null
  /**
   * Services used by the containing project (by IDHI URN). Use for externally or institutionally delivered services that support the work, not services produced as project outputs.
   * @nullable
   */
  uses_services?: string[] | null
  /**
   * Tools used to conduct the containing project (by IDHI URN). Use for substantive research or technical dependencies, not tools produced by the project, which belong in outputs_tools.
   * @nullable
   */
  uses_tools?: string[] | null
}
