/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectProjectParticipationsItemParticipationRole } from './projectProjectParticipationsItemParticipationRole'

/**
 * A person's participation nested in a Project, so the project is inferred from the containing record. Use one instance per participant and role in Project.project_participations and do not define project participation in Person; if a person changed roles over time, create one instance per role with start and end dates.
 */
export type ProjectProjectParticipationsItem = {
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /** The person taking part in the containing project (by IDHI URN). Use in Project.project_participations; do not define the relationship on the Person. */
  participant: string
  /** A person's role in a project. Where a CRediT (Contributor Roles Taxonomy) concept approximates the role, `meaning:` records it. */
  participation_role?: ProjectProjectParticipationsItemParticipationRole
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
}
