/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicationAuthorshipsItemAuthorshipRole } from './publicationAuthorshipsItemAuthorshipRole'

/**
 * A person's contribution to a publication, with author order and role. Create one instance per (person, publication); author_order preserves the byline sequence (1 = first author).
 */
export type PublicationAuthorshipsItem = {
  /** The contributing person (by IDHI URN). */
  author: string
  /**
   * Position in the byline; 1 = first author.
   * @nullable
   */
  author_order?: number | null
  /** The kind of contribution to a publication. */
  authorship_role?: PublicationAuthorshipsItemAuthorshipRole
  /**
   * End of the event, relationship or time period. Omit for ongoing relationships and open-ended periods.
   * @nullable
   */
  end_date?: string | null
  /** The publication contributed to (by IDHI URN). */
  publication: string
  /**
   * Start of the event or of a relationship's validity (e.g. when a person joined a project or organization).
   * @nullable
   */
  start_date?: string | null
}
