/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicationAuthorshipsItemAuthorshipRole } from './publicationAuthorshipsItemAuthorshipRole.ts'

/**
 * A person's contribution nested in a Publication, so the publication is inferred from the containing record. Use one instance per author in Publication.authorships and do not define authorship in Person; author_order preserves the byline sequence with 1 as the first author.
 */
export type PublicationAuthorshipsItem = {
  /** The person contributing to the containing publication (by IDHI URN). Use in Publication.authorships; do not define the relationship on the Person. */
  author: string
  /**
   * Position in the byline; 1 = first author.
   * @nullable
   */
  author_order?: number | null
  /** The kind of contribution to a publication. */
  authorship_role?: PublicationAuthorshipsItemAuthorshipRole
  /**
   * End of the event, project runtime or relationship. Omit for ongoing relationships and open-ended projects.
   * @nullable
   */
  end_date?: string | null
  /**
   * Start of the event, of the project's runtime, or of a relationship's validity, such as when participation, affiliation, maintenance responsibility or formal containment began.
   * @nullable
   */
  start_date?: string | null
}
