/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedEntity } from './auditedEntity.ts'
import type { SearchEntities200Facets } from './searchEntities200Facets.ts'

export type SearchEntities200 = {
  results: AuditedEntity[]
  facets: SearchEntities200Facets
  /** Total number of matching entities across all pages. */
  total: number
}
