/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDescriptionItem } from './serviceDescriptionItem.ts'
import type { ServiceDigitalHumanitiesActivitiesItem } from './serviceDigitalHumanitiesActivitiesItem.ts'
import type { ServiceNameItem } from './serviceNameItem.ts'
import type { ServiceServiceType } from './serviceServiceType.ts'
import type { ServiceType } from './serviceType.ts'

/**
 * A reusable, human- or organization-mediated service offered by a facility or organization (e.g., digitization on demand, OCR consulting, data curation support). Use Service when the offering requires the provider to act; use Tool for self-service software.
 */
export interface Service {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: ServiceDescriptionItem[] | null
  /**
   * Digital-humanities research activities practiced in this project, tool, service or dataset, or taught by this training material. Prefer the most specific applicable activity; multiple values are expected. This is the primary DH-facet for discovery.
   * @nullable
   */
  digital_humanities_activities?:
    ServiceDigitalHumanitiesActivitiesItem[] | null
  /**
   * User or developer documentation for the tool or service (manual, wiki, API reference).
   * @nullable
   */
  documentation_url?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:service:[0-9a-z]{4,12}$
   */
  readonly id: string
  /**
   * A representative image embedded as Base64-encoded binary content. Use for a single image that must travel with the entity record; omit it when no image is available, and use homepage or additional_urls for externally hosted pages rather than encoding a URL here.
   * @nullable
   */
  image?: string | null
  /** The multilingual name or title used to identify the entity. Use one LangString per available language and do not repeat a language. Prefer the official localized name for organizations; for projects, tools and services, use localized names supplied by the team rather than translating branded names without authority. */
  name: ServiceNameItem[]
  /**
   * The organization formally responsible for delivering the service (the one you'd contact or contract with) — set this even when the service is listed under a Facility.
   * @nullable
   */
  provider?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /** Delivery forms for tools and kinds of services. Tool records use the software values; Service records use the service values. */
  service_type?: ServiceServiceType
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: ServiceType
}
