/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Delivery forms for tools and kinds of services. Tool records use the software values; Service records use the service values.
 */
export type ServiceServiceType =
  (typeof ServiceServiceType)[keyof typeof ServiceServiceType]

export const ServiceServiceType = {
  WEB_APPLICATION: 'WEB_APPLICATION',
  DESKTOP_APPLICATION: 'DESKTOP_APPLICATION',
  LIBRARY: 'LIBRARY',
  COMMAND_LINE_TOOL: 'COMMAND_LINE_TOOL',
  DATABASE: 'DATABASE',
  API_SERVICE: 'API_SERVICE',
  DIGITIZATION_SERVICE: 'DIGITIZATION_SERVICE',
  CONSULTING_SERVICE: 'CONSULTING_SERVICE',
} as const
