/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { FilterableField } from './filterableField.ts'
import type { SortDirection } from './sortDirection.ts'

export interface SortCriterion {
  property: FilterableField
  direction: SortDirection
}
