/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Discriminator carrying the class URI; used for polymorphic serialization and deserialization.
 */
export type TimePeriodType =
  (typeof TimePeriodType)[keyof typeof TimePeriodType]

export const TimePeriodType = {
  'idhi:TimePeriod': 'idhi:TimePeriod',
} as const
