/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { TimePeriodDescriptionItem } from './timePeriodDescriptionItem'
import type { TimePeriodNameItem } from './timePeriodNameItem'
import type { TimePeriodType } from './timePeriodType'

/**
 * A time span (EDM TimeSpan). Deliberately reused for two purposes: a project's runtime (project_period) and historical periods studied by a project (studied_periods), e.g. "Second Temple period". For historical periods, prefer linking same_as to a PeriodO or Wikidata URI.
 */
export interface TimePeriod {
  /**
   * Start of the time span. A string (not date) on purpose: historical periods need values like "-0100" or "circa 1500". Prefer ISO 8601 / EDTF where possible.
   * @nullable
   */
  begin_date?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: TimePeriodDescriptionItem[] | null
  /**
   * End of the event, relationship or time period. Omit for ongoing relationships and open-ended periods.
   * @nullable
   */
  end_date?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name (Organization subclasses use "organization"); each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:time_period:[0-9a-z]{4,12}$
   */
  id: string
  /**
   * Additional EXTERNAL identifiers beyond the primary IDHI URN and the dedicated ORCID/ROR/DOI slots, as CURIEs/URIs (e.g. Wikidata QIDs, VIAF, ISNI).
   * @nullable
   */
  identifiers?: string[] | null
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name (e.g. "Smith, John" rather than "John Smith") for people and organizations; for projects, tools and services, use the name the team itself uses.
   * @nullable
   */
  name?: TimePeriodNameItem[] | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /** Discriminator carrying the class URI; used for polymorphic serialization and deserialization. */
  type: TimePeriodType
}
