/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ToolDescriptionItem } from './toolDescriptionItem'
import type { ToolDigitalHumanitiesActivitiesItem } from './toolDigitalHumanitiesActivitiesItem'
import type { ToolLicense } from './toolLicense'
import type { ToolNameItem } from './toolNameItem'
import type { ToolToolType } from './toolToolType'
import type { ToolType } from './toolType'

/**
 * A reusable software tool, typically produced by a project. Use Tool for software that others can install, run or call; for a human-mediated offering use Service instead.
 */
export interface Tool {
  /**
   * Further relevant web pages beyond the homepage (blog, social-media profile, registry entry, press coverage...). For records describing the same entity in other systems use same_as instead.
   * @nullable
   */
  additional_urls?: string[] | null
  /**
   * Source-code repository URL (GitHub, GitLab...), if open.
   * @nullable
   */
  code_repository?: string | null
  /**
   * A published contact address for the entity (office, team or service-desk mailbox). For a person's own addresses use 'emails'.
   * @nullable
   */
  contact_email?: string | null
  /**
   * Multilingual free-text description (a few sentences aimed at index visitors, not internal notes).
   * @nullable
   */
  description?: ToolDescriptionItem[] | null
  /**
   * Digital-humanities research activities practiced in this project, tool or service. Prefer the most specific applicable activity; multiple values are expected. This is the primary DH-facet for discovery.
   * @nullable
   */
  digital_humanities_activities?: ToolDigitalHumanitiesActivitiesItem[] | null
  /**
   * User or developer documentation for the tool or service (manual, wiki, API reference).
   * @nullable
   */
  documentation_url?: string | null
  /**
   * Public landing page of the entity, if one exists.
   * @nullable
   */
  homepage?: string | null
  /**
   * The entity's primary identifier: an IDHI URN of the form
   *   idhi:<class name>:<random short alphanumeric id>
   * e.g. idhi:person:x7k2m9 or idhi:project:a83bq1. Minted by IDHI at record creation and never reused or changed. The class token is the lowercase snake_case class name; each concrete class enforces its own token via slot_usage. External identifiers (ORCID, ROR, DOI...) are supplementary and go in their dedicated slots — never here.
   * @pattern ^idhi:tool:[0-9a-z]{4,12}$
   */
  id: string
  /** Common licenses for tools and datasets. Extend as needed with canonical meanings. */
  license?: ToolLicense
  /**
   * Multilingual name/title. Provide at least one language; English, Hebrew and Arabic variants are each a separate LangString. Preferably a sortable name for organizations; for projects, tools and services, use the name the team itself uses.
   * @minItems 1
   * @nullable
   */
  name?: ToolNameItem[] | null
  /**
   * Main implementation language(s), comma-free single value preferred.
   * @nullable
   */
  programming_language?: string | null
  /**
   * URIs of records in OTHER systems describing the same real-world entity (Wikidata, PeriodO, GeoNames...). Use for linked-data alignment, not for the entity's own pages (use homepage).
   * @nullable
   */
  same_as?: string[] | null
  /**
   * Free-text tags for discovery, filtering and grouping; usable on any top-level entity. Deliberately NOT a controlled enum, but prefer wording that matches a concept in an established ontology or thesaurus (e.g. Wikidata, Getty AAT, TaDiRAH) so tags can later be reconciled against it.
   * @nullable
   */
  tags?: string[] | null
  /** Delivery forms for tools and kinds of services. Tool records use the software values; Service records use the service values. */
  tool_type?: ToolToolType
  /** Discriminator identifying the record's class; used for polymorphic serialization and deserialization. */
  type: ToolType
}
