/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Roles for named contributions to tools and datasets. Use the most specific responsibility and record separate contributions when one agent holds multiple materially different roles.
 */
export type ToolResourceContributionsItemResourceContributionRole =
  (typeof ToolResourceContributionsItemResourceContributionRole)[keyof typeof ToolResourceContributionsItemResourceContributionRole]

export const ToolResourceContributionsItemResourceContributionRole = {
  CREATOR: 'CREATOR',
  DEVELOPER: 'DEVELOPER',
  MAINTAINER: 'MAINTAINER',
  DATA_CURATOR: 'DATA_CURATOR',
  CONTRIBUTOR: 'CONTRIBUTOR',
} as const
