/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { IsDraftParameter } from './isDraftParameter'

export type UpdateEntityByIdParams = {
  /**
   * Whether to save the entity as a draft, visible only to its creator and administrators, instead of publishing it. Defaults to false (publish).
   * An already-published entity cannot be turned back into a draft; the parameter is ignored on update once the entity is published.
   */
  isDraft?: IsDraftParameter
}
