/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedEntity } from './auditedEntity'
import type { Date } from './date'
import type { InviteId } from './inviteId'

export type UserInvite = AuditedEntity & {
  id: InviteId
  email: string
  message?: string
  expiration: Date
}
