/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Names of the groups the user belongs to. Groups have no records of their own and exist only as the names listed here. Users who share a group may read and write the entity drafts created by one another, so the groups of the user who created a draft determine who may access it.
 * @items.minLength 1
 * @items.maxLength 64
 */
export type UserGroups = string[]
