/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { UserId } from './userId.ts'

export interface User {
  id: UserId
  name?: string
  email: string
  isAdmin: boolean
}
