/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { UiLanguage } from './uiLanguage.ts'

export interface UserInviteWrite {
  email: string
  message?: string
  /**
   * @minimum 1
   * @maximum 30
   */
  expiryDays?: number
  lang?: UiLanguage
}
