/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppPrivacyPolicyRouteImport } from './routes/_app/privacy-policy'
import { Route as AppTermsOfUseRouteImport } from './routes/_app/terms-of-use'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as AppAboutIndexRouteImport } from './routes/_app/about.index'
import { Route as AppAboutAiRouteImport } from './routes/_app/about.ai'
import { Route as AppEntitiesIndexRouteImport } from './routes/_app/entities/index'
import { Route as AppEntitiesNewRouteImport } from './routes/_app/entities/new'
import { Route as AppEntitiesEntityIdIndexRouteImport } from './routes/_app/entities/$entityId/index'
import { Route as AppEntitiesEntityIdEditRouteImport } from './routes/_app/entities/$entityId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyPolicyRoute = AppPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsOfUseRoute = AppTermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => AppRoute,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutIndexRoute = AppAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutAiRoute = AppAboutAiRouteImport.update({
  id: '/about/ai',
  path: '/about/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesIndexRoute = AppEntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesNewRoute = AppEntitiesNewRouteImport.update({
  id: '/entities/new',
  path: '/entities/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesEntityIdIndexRoute =
  AppEntitiesEntityIdIndexRouteImport.update({
    id: '/entities/$entityId/',
    path: '/entities/$entityId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEntitiesEntityIdEditRoute = AppEntitiesEntityIdEditRouteImport.update({
  id: '/entities/$entityId/edit',
  path: '/entities/$entityId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/privacy-policy': typeof AppPrivacyPolicyRoute
  '/terms-of-use': typeof AppTermsOfUseRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/about/ai': typeof AppAboutAiRoute
  '/entities/new': typeof AppEntitiesNewRoute
  '/about/': typeof AppAboutIndexRoute
  '/entities/': typeof AppEntitiesIndexRoute
  '/entities/$entityId/edit': typeof AppEntitiesEntityIdEditRoute
  '/entities/$entityId/': typeof AppEntitiesEntityIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/privacy-policy': typeof AppPrivacyPolicyRoute
  '/terms-of-use': typeof AppTermsOfUseRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/': typeof AppIndexRoute
  '/about/ai': typeof AppAboutAiRoute
  '/entities/new': typeof AppEntitiesNewRoute
  '/about': typeof AppAboutIndexRoute
  '/entities': typeof AppEntitiesIndexRoute
  '/entities/$entityId/edit': typeof AppEntitiesEntityIdEditRoute
  '/entities/$entityId': typeof AppEntitiesEntityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/privacy-policy': typeof AppPrivacyPolicyRoute
  '/_app/terms-of-use': typeof AppTermsOfUseRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/about/ai': typeof AppAboutAiRoute
  '/_app/entities/new': typeof AppEntitiesNewRoute
  '/_app/about/': typeof AppAboutIndexRoute
  '/_app/entities/': typeof AppEntitiesIndexRoute
  '/_app/entities/$entityId/edit': typeof AppEntitiesEntityIdEditRoute
  '/_app/entities/$entityId/': typeof AppEntitiesEntityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/oauth/authorize'
    | '/about/ai'
    | '/entities/new'
    | '/about/'
    | '/entities/'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/oauth/authorize'
    | '/'
    | '/about/ai'
    | '/entities/new'
    | '/about'
    | '/entities'
    | '/entities/$entityId/edit'
    | '/entities/$entityId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/privacy-policy'
    | '/_app/terms-of-use'
    | '/oauth/authorize'
    | '/_app/'
    | '/_app/about/ai'
    | '/_app/entities/new'
    | '/_app/about/'
    | '/_app/entities/'
    | '/_app/entities/$entityId/edit'
    | '/_app/entities/$entityId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy-policy': {
      id: '/_app/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AppPrivacyPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms-of-use': {
      id: '/_app/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof AppTermsOfUseRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AppAboutIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about/ai': {
      id: '/_app/about/ai'
      path: '/about/ai'
      fullPath: '/about/ai'
      preLoaderRoute: typeof AppAboutAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/': {
      id: '/_app/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof AppEntitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/new': {
      id: '/_app/entities/new'
      path: '/entities/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof AppEntitiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/$entityId/': {
      id: '/_app/entities/$entityId/'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId/'
      preLoaderRoute: typeof AppEntitiesEntityIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/$entityId/edit': {
      id: '/_app/entities/$entityId/edit'
      path: '/entities/$entityId/edit'
      fullPath: '/entities/$entityId/edit'
      preLoaderRoute: typeof AppEntitiesEntityIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppPrivacyPolicyRoute: typeof AppPrivacyPolicyRoute
  AppTermsOfUseRoute: typeof AppTermsOfUseRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAboutAiRoute: typeof AppAboutAiRoute
  AppEntitiesNewRoute: typeof AppEntitiesNewRoute
  AppAboutIndexRoute: typeof AppAboutIndexRoute
  AppEntitiesIndexRoute: typeof AppEntitiesIndexRoute
  AppEntitiesEntityIdEditRoute: typeof AppEntitiesEntityIdEditRoute
  AppEntitiesEntityIdIndexRoute: typeof AppEntitiesEntityIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppPrivacyPolicyRoute: AppPrivacyPolicyRoute,
  AppTermsOfUseRoute: AppTermsOfUseRoute,
  AppIndexRoute: AppIndexRoute,
  AppAboutAiRoute: AppAboutAiRoute,
  AppEntitiesNewRoute: AppEntitiesNewRoute,
  AppAboutIndexRoute: AppAboutIndexRoute,
  AppEntitiesIndexRoute: AppEntitiesIndexRoute,
  AppEntitiesEntityIdEditRoute: AppEntitiesEntityIdEditRoute,
  AppEntitiesEntityIdIndexRoute: AppEntitiesEntityIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
