/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  GetApiV1Users200,
  GetApiV1UsersParams,
  User,
  UserWrite,
} from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary List users
 */
export const getApiV1Users = (
  params?: GetApiV1UsersParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetApiV1Users200>({
    url: `/api/v1/users`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetApiV1UsersQueryKey = (params?: GetApiV1UsersParams) => {
  return [`/api/v1/users`, ...(params ? [params] : [])] as const
}

export const getGetApiV1UsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Users>>> = ({
    signal,
  }) => getApiV1Users(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Users>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Users>>
>
export type GetApiV1UsersQueryError = ErrorType<ErrorResponse>

export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | GetApiV1UsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List users
 */

export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1UsersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Create a new user
 */
export const postApiV1Users = (
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getPostApiV1UsersMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Users>>,
    TError,
    { data: BodyType<UserWrite> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1Users>>,
  TError,
  { data: BodyType<UserWrite> },
  TContext
> => {
  const mutationKey = ['postApiV1Users']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1Users>>,
    { data: BodyType<UserWrite> }
  > = (props) => {
    const { data } = props ?? {}

    return postApiV1Users(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1UsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1Users>>
>
export type PostApiV1UsersMutationBody = BodyType<UserWrite>
export type PostApiV1UsersMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create a new user
 */
export const usePostApiV1Users = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1Users>>,
      TError,
      { data: BodyType<UserWrite> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1Users>>,
  TError,
  { data: BodyType<UserWrite> },
  TContext
> => {
  return useMutation(getPostApiV1UsersMutationOptions(options), queryClient)
}
/**
 * @summary Get a user
 */
export const getApiV1UsersUserId = (userId: string, signal?: AbortSignal) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'GET',
    signal,
  })
}

export const getGetApiV1UsersUserIdQueryKey = (userId: string) => {
  return [`/api/v1/users/${userId}`] as const
}

export const getGetApiV1UsersUserIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1UsersUserIdQueryKey(userId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1UsersUserId>>
  > = ({ signal }) => getApiV1UsersUserId(userId, signal)

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1UsersUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersUserIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1UsersUserId>>
>
export type GetApiV1UsersUserIdQueryError = ErrorType<ErrorResponse>

export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersUserId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersUserId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a user
 */

export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1UsersUserIdQueryOptions(userId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Replace a user
 */
export const putApiV1UsersUserId = (
  userId: string,
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getPutApiV1UsersUserIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1UsersUserId>>,
    TError,
    { userId: string; data: BodyType<UserWrite> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>,
  TError,
  { userId: string; data: BodyType<UserWrite> },
  TContext
> => {
  const mutationKey = ['putApiV1UsersUserId']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1UsersUserId>>,
    { userId: string; data: BodyType<UserWrite> }
  > = (props) => {
    const { userId, data } = props ?? {}

    return putApiV1UsersUserId(userId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>
>
export type PutApiV1UsersUserIdMutationBody = BodyType<UserWrite>
export type PutApiV1UsersUserIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Replace a user
 */
export const usePutApiV1UsersUserId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1UsersUserId>>,
      TError,
      { userId: string; data: BodyType<UserWrite> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>,
  TError,
  { userId: string; data: BodyType<UserWrite> },
  TContext
> => {
  return useMutation(
    getPutApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Update a user
 */
export const postApiV1UsersUserId = (
  userId: string,
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getPostApiV1UsersUserIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1UsersUserId>>,
    TError,
    { userId: string; data: BodyType<UserWrite> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>,
  TError,
  { userId: string; data: BodyType<UserWrite> },
  TContext
> => {
  const mutationKey = ['postApiV1UsersUserId']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1UsersUserId>>,
    { userId: string; data: BodyType<UserWrite> }
  > = (props) => {
    const { userId, data } = props ?? {}

    return postApiV1UsersUserId(userId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>
>
export type PostApiV1UsersUserIdMutationBody = BodyType<UserWrite>
export type PostApiV1UsersUserIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update a user
 */
export const usePostApiV1UsersUserId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1UsersUserId>>,
      TError,
      { userId: string; data: BodyType<UserWrite> },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>,
  TError,
  { userId: string; data: BodyType<UserWrite> },
  TContext
> => {
  return useMutation(
    getPostApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Delete a user
 */
export const deleteApiV1UsersUserId = (
  userId: string,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'DELETE',
    signal,
  })
}

export const getDeleteApiV1UsersUserIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
    TError,
    { userId: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1UsersUserId']
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {}

    return deleteApiV1UsersUserId(userId)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>
>

export type DeleteApiV1UsersUserIdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete a user
 */
export const useDeleteApiV1UsersUserId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
      TError,
      { userId: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(
    getDeleteApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
