/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  GetApiV1Users200,
  GetApiV1UsersParams,
  User,
  UserWrite,
} from '../../models'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getApiV1UsersResponse200 = {
  data: GetApiV1Users200
  status: 200
}

export type getApiV1UsersResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getApiV1UsersResponseSuccess = getApiV1UsersResponse200 & {
  headers: Headers
}
export type getApiV1UsersResponseError = getApiV1UsersResponse400 & {
  headers: Headers
}

export type getApiV1UsersResponse =
  getApiV1UsersResponseSuccess | getApiV1UsersResponseError

export const getGetApiV1UsersUrl = (params?: GetApiV1UsersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/users?${stringifiedParams}`
    : `/api/v1/users`
}

/**
 * @summary List users
 */
export const getApiV1Users = async (
  params?: GetApiV1UsersParams,
  options?: RequestInit,
): Promise<getApiV1UsersResponse> => {
  const res = await fetch(getGetApiV1UsersUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getApiV1UsersResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1UsersResponse
}

export const getGetApiV1UsersQueryKey = (params?: GetApiV1UsersParams) => {
  return [`/api/v1/users`, ...(params ? [params] : [])] as const
}

export const getGetApiV1UsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorResponse,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Users>>> = ({
    signal,
  }) => getApiV1Users(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Users>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Users>>
>
export type GetApiV1UsersQueryError = ErrorResponse

export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorResponse,
>(
  params: undefined | GetApiV1UsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorResponse,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorResponse,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List users
 */

export function useGetApiV1Users<
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = ErrorResponse,
>(
  params?: GetApiV1UsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1UsersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export type postApiV1UsersResponse201 = {
  data: User
  status: 201
}

export type postApiV1UsersResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiV1UsersResponseSuccess = postApiV1UsersResponse201 & {
  headers: Headers
}
export type postApiV1UsersResponseError = postApiV1UsersResponse400 & {
  headers: Headers
}

export type postApiV1UsersResponse =
  postApiV1UsersResponseSuccess | postApiV1UsersResponseError

export const getPostApiV1UsersUrl = () => {
  return `/api/v1/users`
}

/**
 * @summary Create a new user
 */
export const postApiV1Users = async (
  userWrite: UserWrite,
  options?: RequestInit,
): Promise<postApiV1UsersResponse> => {
  const res = await fetch(getPostApiV1UsersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userWrite),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postApiV1UsersResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1UsersResponse
}

export const getPostApiV1UsersMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Users>>,
    TError,
    { data: UserWrite },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1Users>>,
  TError,
  { data: UserWrite },
  TContext
> => {
  const mutationKey = ['postApiV1Users']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1Users>>,
    { data: UserWrite }
  > = (props) => {
    const { data } = props ?? {}

    return postApiV1Users(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1UsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1Users>>
>
export type PostApiV1UsersMutationBody = UserWrite
export type PostApiV1UsersMutationError = ErrorResponse

/**
 * @summary Create a new user
 */
export const usePostApiV1Users = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1Users>>,
      TError,
      { data: UserWrite },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1Users>>,
  TError,
  { data: UserWrite },
  TContext
> => {
  return useMutation(getPostApiV1UsersMutationOptions(options), queryClient)
}
export type getApiV1UsersUserIdResponse200 = {
  data: User
  status: 200
}

export type getApiV1UsersUserIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getApiV1UsersUserIdResponseSuccess =
  getApiV1UsersUserIdResponse200 & {
    headers: Headers
  }
export type getApiV1UsersUserIdResponseError =
  getApiV1UsersUserIdResponse400 & {
    headers: Headers
  }

export type getApiV1UsersUserIdResponse =
  getApiV1UsersUserIdResponseSuccess | getApiV1UsersUserIdResponseError

export const getGetApiV1UsersUserIdUrl = (userId: string) => {
  return `/api/v1/users/${userId}`
}

/**
 * @summary Get a user
 */
export const getApiV1UsersUserId = async (
  userId: string,
  options?: RequestInit,
): Promise<getApiV1UsersUserIdResponse> => {
  const res = await fetch(getGetApiV1UsersUserIdUrl(userId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getApiV1UsersUserIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1UsersUserIdResponse
}

export const getGetApiV1UsersUserIdQueryKey = (userId: string) => {
  return [`/api/v1/users/${userId}`] as const
}

export const getGetApiV1UsersUserIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1UsersUserIdQueryKey(userId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1UsersUserId>>
  > = ({ signal }) => getApiV1UsersUserId(userId, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1UsersUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersUserIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1UsersUserId>>
>
export type GetApiV1UsersUserIdQueryError = ErrorResponse

export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorResponse,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersUserId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersUserId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a user
 */

export function useGetApiV1UsersUserId<
  TData = Awaited<ReturnType<typeof getApiV1UsersUserId>>,
  TError = ErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1UsersUserId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiV1UsersUserIdQueryOptions(userId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export type putApiV1UsersUserIdResponse200 = {
  data: User
  status: 200
}

export type putApiV1UsersUserIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type putApiV1UsersUserIdResponseSuccess =
  putApiV1UsersUserIdResponse200 & {
    headers: Headers
  }
export type putApiV1UsersUserIdResponseError =
  putApiV1UsersUserIdResponse400 & {
    headers: Headers
  }

export type putApiV1UsersUserIdResponse =
  putApiV1UsersUserIdResponseSuccess | putApiV1UsersUserIdResponseError

export const getPutApiV1UsersUserIdUrl = (userId: string) => {
  return `/api/v1/users/${userId}`
}

/**
 * @summary Replace a user
 */
export const putApiV1UsersUserId = async (
  userId: string,
  userWrite: UserWrite,
  options?: RequestInit,
): Promise<putApiV1UsersUserIdResponse> => {
  const res = await fetch(getPutApiV1UsersUserIdUrl(userId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userWrite),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putApiV1UsersUserIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putApiV1UsersUserIdResponse
}

export const getPutApiV1UsersUserIdMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1UsersUserId>>,
    TError,
    { userId: string; data: UserWrite },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>,
  TError,
  { userId: string; data: UserWrite },
  TContext
> => {
  const mutationKey = ['putApiV1UsersUserId']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1UsersUserId>>,
    { userId: string; data: UserWrite }
  > = (props) => {
    const { userId, data } = props ?? {}

    return putApiV1UsersUserId(userId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>
>
export type PutApiV1UsersUserIdMutationBody = UserWrite
export type PutApiV1UsersUserIdMutationError = ErrorResponse

/**
 * @summary Replace a user
 */
export const usePutApiV1UsersUserId = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1UsersUserId>>,
      TError,
      { userId: string; data: UserWrite },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1UsersUserId>>,
  TError,
  { userId: string; data: UserWrite },
  TContext
> => {
  return useMutation(
    getPutApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
export type postApiV1UsersUserIdResponse200 = {
  data: User
  status: 200
}

export type postApiV1UsersUserIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiV1UsersUserIdResponseSuccess =
  postApiV1UsersUserIdResponse200 & {
    headers: Headers
  }
export type postApiV1UsersUserIdResponseError =
  postApiV1UsersUserIdResponse400 & {
    headers: Headers
  }

export type postApiV1UsersUserIdResponse =
  postApiV1UsersUserIdResponseSuccess | postApiV1UsersUserIdResponseError

export const getPostApiV1UsersUserIdUrl = (userId: string) => {
  return `/api/v1/users/${userId}`
}

/**
 * @summary Update a user
 */
export const postApiV1UsersUserId = async (
  userId: string,
  userWrite: UserWrite,
  options?: RequestInit,
): Promise<postApiV1UsersUserIdResponse> => {
  const res = await fetch(getPostApiV1UsersUserIdUrl(userId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userWrite),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postApiV1UsersUserIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1UsersUserIdResponse
}

export const getPostApiV1UsersUserIdMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1UsersUserId>>,
    TError,
    { userId: string; data: UserWrite },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>,
  TError,
  { userId: string; data: UserWrite },
  TContext
> => {
  const mutationKey = ['postApiV1UsersUserId']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1UsersUserId>>,
    { userId: string; data: UserWrite }
  > = (props) => {
    const { userId, data } = props ?? {}

    return postApiV1UsersUserId(userId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>
>
export type PostApiV1UsersUserIdMutationBody = UserWrite
export type PostApiV1UsersUserIdMutationError = ErrorResponse

/**
 * @summary Update a user
 */
export const usePostApiV1UsersUserId = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1UsersUserId>>,
      TError,
      { userId: string; data: UserWrite },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1UsersUserId>>,
  TError,
  { userId: string; data: UserWrite },
  TContext
> => {
  return useMutation(
    getPostApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
export type deleteApiV1UsersUserIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiV1UsersUserIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteApiV1UsersUserIdResponseSuccess =
  deleteApiV1UsersUserIdResponse204 & {
    headers: Headers
  }
export type deleteApiV1UsersUserIdResponseError =
  deleteApiV1UsersUserIdResponse400 & {
    headers: Headers
  }

export type deleteApiV1UsersUserIdResponse =
  deleteApiV1UsersUserIdResponseSuccess | deleteApiV1UsersUserIdResponseError

export const getDeleteApiV1UsersUserIdUrl = (userId: string) => {
  return `/api/v1/users/${userId}`
}

/**
 * @summary Delete a user
 */
export const deleteApiV1UsersUserId = async (
  userId: string,
  options?: RequestInit,
): Promise<deleteApiV1UsersUserIdResponse> => {
  const res = await fetch(getDeleteApiV1UsersUserIdUrl(userId), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteApiV1UsersUserIdResponse['data'] = body
    ? JSON.parse(body)
    : undefined
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteApiV1UsersUserIdResponse
}

export const getDeleteApiV1UsersUserIdMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
    TError,
    { userId: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1UsersUserId']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {}

    return deleteApiV1UsersUserId(userId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiV1UsersUserIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>
>

export type DeleteApiV1UsersUserIdMutationError = ErrorResponse

/**
 * @summary Delete a user
 */
export const useDeleteApiV1UsersUserId = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
      TError,
      { userId: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1UsersUserId>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(
    getDeleteApiV1UsersUserIdMutationOptions(options),
    queryClient,
  )
}
