/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  ListUsers200,
  ListUsersParams,
  User,
  UserGroups,
  UserWrite,
} from '../../models'

import { customInstance } from '../../client.ts'
import type { ErrorType, BodyType } from '../../client.ts'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') {
      continue
    }
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary List users
 */
export const listUsers = (params?: ListUsersParams, signal?: AbortSignal) => {
  return customInstance<ListUsers200>({
    url: `/api/v1/users`,
    method: 'GET',
    params,
    signal,
  })
}

export const getListUsersQueryKey = (params?: ListUsersParams) => {
  return [`/api/v1/users`, ...(params ? [params] : [])] as const
}

export const getListUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: ListUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
    signal,
  }) => listUsers(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>
export type ListUsersQueryError = ErrorType<ErrorResponse>

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | ListUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: ListUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: ListUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List users
 */

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: ListUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListUsersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Create a new user
 */
export const createUser = (
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getCreateUserMutationKey = () => ['createUser'] as const

export const getCreateUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    CreateUserMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  CreateUserMutationVariables,
  TContext
> => {
  const mutationKey = getCreateUserMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUser>>,
    CreateUserMutationVariables
  > = (props) => {
    const { data } = props ?? {}

    return createUser(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationBody = BodyType<UserWrite>
export type CreateUserMutationError = ErrorType<ErrorResponse>
export type CreateUserMutationVariables = { data: BodyType<UserWrite> }

/**
 * @summary Create a new user
 */
export const useCreateUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUser>>,
      TError,
      CreateUserMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  CreateUserMutationVariables,
  TContext
> => {
  return useMutation(getCreateUserMutationOptions(options), queryClient)
}
/**
 * @summary List the group names currently assigned to users
 */
export const listUserGroups = (signal?: AbortSignal) => {
  return customInstance<UserGroups>({
    url: `/api/v1/users/groups`,
    method: 'GET',
    signal,
  })
}

export const getListUserGroupsQueryKey = () => {
  return [`/api/v1/users/groups`] as const
}

export const getListUserGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof listUserGroups>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listUserGroups>>, TError, TData>
  >
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListUserGroupsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserGroups>>> = ({
    signal,
  }) => listUserGroups(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUserGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUserGroups>>
>
export type ListUserGroupsQueryError = ErrorType<ErrorResponse>

export function useListUserGroups<
  TData = Awaited<ReturnType<typeof listUserGroups>>,
  TError = ErrorType<ErrorResponse>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserGroups>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserGroups>>,
          TError,
          Awaited<ReturnType<typeof listUserGroups>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUserGroups<
  TData = Awaited<ReturnType<typeof listUserGroups>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserGroups>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserGroups>>,
          TError,
          Awaited<ReturnType<typeof listUserGroups>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUserGroups<
  TData = Awaited<ReturnType<typeof listUserGroups>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserGroups>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List the group names currently assigned to users
 */

export function useListUserGroups<
  TData = Awaited<ReturnType<typeof listUserGroups>>,
  TError = ErrorType<ErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserGroups>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListUserGroupsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get a user
 */
export const getUserById = (userId: string, signal?: AbortSignal) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'GET',
    signal,
  })
}

export const getGetUserByIdQueryKey = (userId: string) => {
  return [`/api/v1/users/${userId}`] as const
}

export const getGetUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({
    signal,
  }) => getUserById(userId, signal)

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>
export type GetUserByIdQueryError = ErrorType<ErrorResponse>

export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a user
 */

export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserByIdQueryOptions(userId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Replace a user
 */
export const replaceUserById = (
  userId: string,
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getReplaceUserByIdMutationKey = () => ['replaceUserById'] as const

export const getReplaceUserByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof replaceUserById>>,
    TError,
    ReplaceUserByIdMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof replaceUserById>>,
  TError,
  ReplaceUserByIdMutationVariables,
  TContext
> => {
  const mutationKey = getReplaceUserByIdMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof replaceUserById>>,
    ReplaceUserByIdMutationVariables
  > = (props) => {
    const { userId, data } = props ?? {}

    return replaceUserById(userId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReplaceUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof replaceUserById>>
>
export type ReplaceUserByIdMutationBody = BodyType<UserWrite>
export type ReplaceUserByIdMutationError = ErrorType<ErrorResponse>
export type ReplaceUserByIdMutationVariables = {
  userId: string
  data: BodyType<UserWrite>
}

/**
 * @summary Replace a user
 */
export const useReplaceUserById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof replaceUserById>>,
      TError,
      ReplaceUserByIdMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof replaceUserById>>,
  TError,
  ReplaceUserByIdMutationVariables,
  TContext
> => {
  return useMutation(getReplaceUserByIdMutationOptions(options), queryClient)
}
/**
 * @summary Update a user
 */
export const updateUserById = (
  userId: string,
  userWrite: BodyType<UserWrite>,
  signal?: AbortSignal,
) => {
  return customInstance<User>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userWrite,
    signal,
  })
}

export const getUpdateUserByIdMutationKey = () => ['updateUserById'] as const

export const getUpdateUserByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserById>>,
    TError,
    UpdateUserByIdMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserById>>,
  TError,
  UpdateUserByIdMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateUserByIdMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserById>>,
    UpdateUserByIdMutationVariables
  > = (props) => {
    const { userId, data } = props ?? {}

    return updateUserById(userId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserById>>
>
export type UpdateUserByIdMutationBody = BodyType<UserWrite>
export type UpdateUserByIdMutationError = ErrorType<ErrorResponse>
export type UpdateUserByIdMutationVariables = {
  userId: string
  data: BodyType<UserWrite>
}

/**
 * @summary Update a user
 */
export const useUpdateUserById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserById>>,
      TError,
      UpdateUserByIdMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserById>>,
  TError,
  UpdateUserByIdMutationVariables,
  TContext
> => {
  return useMutation(getUpdateUserByIdMutationOptions(options), queryClient)
}
/**
 * @summary Delete a user
 */
export const deleteUserById = (userId: string, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/v1/users/${encodeURIComponent(String(userId))}`,
    method: 'DELETE',
    signal,
  })
}

export const getDeleteUserByIdMutationKey = () => ['deleteUserById'] as const

export const getDeleteUserByIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserById>>,
    TError,
    DeleteUserByIdMutationVariables,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserById>>,
  TError,
  DeleteUserByIdMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteUserByIdMutationKey()
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserById>>,
    DeleteUserByIdMutationVariables
  > = (props) => {
    const { userId } = props ?? {}

    return deleteUserById(userId)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserById>>
>

export type DeleteUserByIdMutationError = ErrorType<ErrorResponse>
export type DeleteUserByIdMutationVariables = { userId: string }

/**
 * @summary Delete a user
 */
export const useDeleteUserById = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserById>>,
      TError,
      DeleteUserByIdMutationVariables,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserById>>,
  TError,
  DeleteUserByIdMutationVariables,
  TContext
> => {
  return useMutation(getDeleteUserByIdMutationOptions(options), queryClient)
}
