/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { Date } from './date'
import type { UserId } from './userId'

export type AuditedAudit = {
  createdAt: Date
  createdBy: UserId
  modifiedAt: Date
  modifiedBy: UserId
}
