/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode } from './errorCode'

export interface Error {
  errorCode: ErrorCode
  message: string
  entityId?: string
}
