/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditedRecord } from './auditedRecord'
import type { GetApiV1Records200Facets } from './getApiV1Records200Facets'

export type GetApiV1Records200 = {
  results: AuditedRecord[]
  facets: GetApiV1Records200Facets
  total: number
}
