/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Records200FacetsItem } from './getApiV1Records200FacetsItem'

export type GetApiV1Records200Facets = {
  [key: string]: GetApiV1Records200FacetsItem[]
}
