/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IDHI API
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono'
import { getHealthHandlers } from './handlers/default/default.handlers.ts'
import {
  startOtpChallengeHandlers,
  completeOtpChallengeHandlers,
  startPasskeyRegistrationHandlers,
  completePasskeyRegistrationHandlers,
  startPasskeyAuthenticationHandlers,
  completePasskeyAuthenticationHandlers,
} from './handlers/user-auth/user-auth.handlers.ts'
import {
  searchEntitiesHandlers,
  createEntityHandlers,
  getEntityByIdHandlers,
  updateEntityByIdHandlers,
  deleteEntityByIdHandlers,
} from './handlers/entities/entities.handlers.ts'
import {
  listUsersHandlers,
  createUserHandlers,
  getUserByIdHandlers,
  replaceUserByIdHandlers,
  updateUserByIdHandlers,
  deleteUserByIdHandlers,
} from './handlers/user-management/user-management.handlers.ts'
import {
  inviteUserHandlers,
  listUserInvitesHandlers,
  revokeUserInviteByIdHandlers,
} from './handlers/user-invites/user-invites.handlers.ts'
import { completeOauthAuthorizationHandlers } from './handlers/oauth/oauth.handlers.ts'

const app = new Hono()
  .get('/api/v1/health', ...getHealthHandlers)
  .post('/api/v1/auth/otp', ...startOtpChallengeHandlers)
  .post('/api/v1/auth/otp/:challengeId', ...completeOtpChallengeHandlers)
  .post('/api/v1/auth/passkey/create', ...startPasskeyRegistrationHandlers)
  .post(
    '/api/v1/auth/passkey/create/:challengeId',
    ...completePasskeyRegistrationHandlers,
  )
  .post('/api/v1/auth/passkey/login', ...startPasskeyAuthenticationHandlers)
  .post(
    '/api/v1/auth/passkey/login/:challengeId',
    ...completePasskeyAuthenticationHandlers,
  )
  .post('/api/v1/entities', ...searchEntitiesHandlers)
  .put('/api/v1/entities', ...createEntityHandlers)
  .get('/api/v1/entities/:entityId', ...getEntityByIdHandlers)
  .post('/api/v1/entities/:entityId', ...updateEntityByIdHandlers)
  .delete('/api/v1/entities/:entityId', ...deleteEntityByIdHandlers)
  .get('/api/v1/users', ...listUsersHandlers)
  .post('/api/v1/users', ...createUserHandlers)
  .post('/api/v1/users/invite', ...inviteUserHandlers)
  .get('/api/v1/users/invites', ...listUserInvitesHandlers)
  .delete('/api/v1/users/invites/:inviteId', ...revokeUserInviteByIdHandlers)
  .get('/api/v1/users/:userId', ...getUserByIdHandlers)
  .put('/api/v1/users/:userId', ...replaceUserByIdHandlers)
  .post('/api/v1/users/:userId', ...updateUserByIdHandlers)
  .delete('/api/v1/users/:userId', ...deleteUserByIdHandlers)
  .post('/oauth/authorize', ...completeOauthAuthorizationHandlers)

export default app
