import type {
  Dataset,
  Event,
  Facility,
  Organization,
  Person,
  Project,
  Publication,
  Service,
  Tool,
  TrainingMaterial,
} from '@/api/models'

type Present<T> = Exclude<T, null | undefined>

type LeafPaths<T, TPrefix extends string = ''> =
  Present<T> extends readonly (infer Item)[]
    ? Present<Item> extends object
      ? LeafPaths<Present<Item>, `${TPrefix}[]`>
      : TPrefix
    : Present<T> extends object
      ? {
          [Key in keyof Present<T> & string]-?: LeafPaths<
            Present<T>[Key],
            TPrefix extends '' ? Key : `${TPrefix}.${Key}`
          >
        }[keyof Present<T> & string]
      : TPrefix

type FieldDisposition = 'rendered' | `omitted: ${string}`
type FormCoverage<T> = Record<LeafPaths<T>, FieldDisposition>

const COMMON_ENTITY_FIELDS = {
  'description[].language': 'rendered',
  'description[].value': 'rendered',
  homepage: 'rendered',
  id: 'rendered',
  image: 'rendered',
  same_as: 'rendered',
  tags: 'rendered',
  type: 'omitted: selected before the form and immutable',
} satisfies Record<string, FieldDisposition>

export const ENTITY_FORM_FIELD_COVERAGE = {
  person: {
    ...COMMON_ENTITY_FIELDS,
    'affiliations[].affiliation_role': 'rendered',
    'affiliations[].end_date': 'rendered',
    'affiliations[].organization': 'rendered',
    'affiliations[].start_date': 'rendered',
    emails: 'rendered',
    'family_name[].language': 'rendered',
    'family_name[].value': 'rendered',
    'given_name[].language': 'rendered',
    'given_name[].value': 'rendered',
    orcid: 'rendered',
  } satisfies FormCoverage<Person>,
  organization: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    'address[].language': 'rendered',
    'address[].value': 'rendered',
    contact_email: 'rendered',
    'location[].language': 'rendered',
    'location[].value': 'rendered',
    marketplace_sync: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    'organization_hierarchy[].end_date': 'rendered',
    'organization_hierarchy[].parent_organization': 'rendered',
    'organization_hierarchy[].start_date': 'rendered',
    organization_type: 'rendered',
    ror: 'rendered',
  } satisfies FormCoverage<Organization>,
  facility: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    'address[].language': 'rendered',
    'address[].value': 'rendered',
    contact_email: 'rendered',
    'facility_affiliations[].end_date': 'rendered',
    'facility_affiliations[].facility_affiliation_role': 'rendered',
    'facility_affiliations[].organization': 'rendered',
    'facility_affiliations[].start_date': 'rendered',
    'location[].language': 'rendered',
    'location[].value': 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    services_offered: 'rendered',
    tools_provided: 'rendered',
  } satisfies FormCoverage<Facility>,
  project: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    contact_email: 'rendered',
    digital_humanities_activities: 'rendered',
    end_date: 'rendered',
    'funding[].end_date': 'rendered',
    'funding[].funding_amount': 'rendered',
    'funding[].funding_organization': 'rendered',
    'funding[].funding_program[].language': 'rendered',
    'funding[].funding_program[].value': 'rendered',
    'funding[].funding_url': 'rendered',
    'funding[].grant_name[].language': 'rendered',
    'funding[].grant_name[].value': 'rendered',
    'funding[].grant_number': 'rendered',
    'funding[].start_date': 'rendered',
    funding_status: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    'organization_roles[].end_date': 'rendered',
    'organization_roles[].org_project_role': 'rendered',
    'organization_roles[].organization': 'rendered',
    'organization_roles[].start_date': 'rendered',
    outputs_datasets: 'rendered',
    outputs_publications: 'rendered',
    outputs_tools: 'rendered',
    outputs_training_materials: 'rendered',
    'project_participations[].end_date': 'rendered',
    'project_participations[].participant': 'rendered',
    'project_participations[].participation_role': 'rendered',
    'project_participations[].start_date': 'rendered',
    'research_disciplines[].language': 'rendered',
    'research_disciplines[].value': 'rendered',
    start_date: 'rendered',
    'studied_periods[].language': 'rendered',
    'studied_periods[].value': 'rendered',
    'studied_places[].language': 'rendered',
    'studied_places[].value': 'rendered',
    uses_datasets: 'rendered',
    uses_services: 'rendered',
    uses_tools: 'rendered',
  } satisfies FormCoverage<Project>,
  tool: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    code_repository: 'rendered',
    contact_email: 'rendered',
    digital_humanities_activities: 'rendered',
    documentation_url: 'rendered',
    doi: 'rendered',
    license: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    programming_language: 'rendered',
    'resource_contributions[].contributor': 'rendered',
    'resource_contributions[].end_date': 'rendered',
    'resource_contributions[].resource_contribution_role': 'rendered',
    'resource_contributions[].start_date': 'rendered',
    tool_type: 'rendered',
  } satisfies FormCoverage<Tool>,
  service: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    contact_email: 'rendered',
    digital_humanities_activities: 'rendered',
    documentation_url: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    provider: 'rendered',
    service_type: 'rendered',
  } satisfies FormCoverage<Service>,
  publication: {
    ...COMMON_ENTITY_FIELDS,
    'authorships[].author': 'rendered',
    'authorships[].author_order': 'rendered',
    'authorships[].authorship_role': 'rendered',
    'authorships[].end_date': 'rendered',
    'authorships[].start_date': 'rendered',
    date_issued: 'rendered',
    doi: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    part_of: 'rendered',
    presented_at: 'rendered',
    publication_type: 'rendered',
    'published_in[].language': 'rendered',
    'published_in[].value': 'rendered',
    publisher: 'rendered',
  } satisfies FormCoverage<Publication>,
  event: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    'address[].language': 'rendered',
    'address[].value': 'rendered',
    contact_email: 'rendered',
    end_date: 'rendered',
    'event_agent_roles[].end_date': 'rendered',
    'event_agent_roles[].event_agent': 'rendered',
    'event_agent_roles[].event_agent_role': 'rendered',
    'event_agent_roles[].start_date': 'rendered',
    event_type: 'rendered',
    'location[].language': 'rendered',
    'location[].value': 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    start_date: 'rendered',
  } satisfies FormCoverage<Event>,
  dataset: {
    ...COMMON_ENTITY_FIELDS,
    byte_size: 'rendered',
    dataset_type: 'rendered',
    datasets: 'rendered',
    date_issued: 'rendered',
    derived_from: 'rendered',
    distribution_url: 'rendered',
    doi: 'rendered',
    extent: 'rendered',
    in_languages: 'rendered',
    license: 'rendered',
    media_type: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    publisher: 'rendered',
    related_publications: 'rendered',
    'resource_contributions[].contributor': 'rendered',
    'resource_contributions[].end_date': 'rendered',
    'resource_contributions[].resource_contribution_role': 'rendered',
    'resource_contributions[].start_date': 'rendered',
    'themes[].language': 'rendered',
    'themes[].value': 'rendered',
  } satisfies FormCoverage<Dataset>,
  trainingMaterial: {
    ...COMMON_ENTITY_FIELDS,
    additional_urls: 'rendered',
    contact_email: 'rendered',
    creators: 'rendered',
    date_issued: 'rendered',
    digital_humanities_activities: 'rendered',
    doi: 'rendered',
    'educational_level[].language': 'rendered',
    'educational_level[].value': 'rendered',
    in_languages: 'rendered',
    'learning_outcomes[].language': 'rendered',
    'learning_outcomes[].value': 'rendered',
    license: 'rendered',
    material_url: 'rendered',
    media_type: 'rendered',
    'name[].language': 'rendered',
    'name[].value': 'rendered',
    part_of_training_material: 'rendered',
    'prerequisites[].language': 'rendered',
    'prerequisites[].value': 'rendered',
    publisher: 'rendered',
    related_datasets: 'rendered',
    related_services: 'rendered',
    related_tools: 'rendered',
    'target_audiences[].language': 'rendered',
    'target_audiences[].value': 'rendered',
    training_material_type: 'rendered',
  } satisfies FormCoverage<TrainingMaterial>,
}
